# Generated by Django 3.1.8 on 2021-04-23 09:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    replaces = [
        ("compliance", "0001_initial"),
        ("compliance", "0002_compliancesitecase"),
        ("compliance", "0003_complianceperson_compliancevisitcase"),
        ("compliance", "0004_auto_20200625_0823"),
        ("compliance", "0005_auto_20200625_0857"),
    ]

    initial = True

    dependencies = [
        ("cases", "0040_auto_20200624_1218"),
        ("licences", "0005_auto_20200616_0837"),
        ("organisations", "0008_auto_20200601_0814"),
        ("cases", "0038_auto_20200615_1400"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenLicenceReturns",
            fields=[
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created_at"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("returns_data", models.TextField()),
                ("year", models.PositiveSmallIntegerField()),
                ("licences", models.ManyToManyField(related_name="open_licence_returns", to="licences.Licence")),
                (
                    "organisation",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="organisations.organisation"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ComplianceSiteCase",
            fields=[
                (
                    "case_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cases.case",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="compliance",
                        to="organisations.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("cases.case",),
        ),
        migrations.CreateModel(
            name="ComplianceVisitCase",
            fields=[
                (
                    "case_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cases.case",
                    ),
                ),
                (
                    "visit_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("first_contact", "First contact"),
                            ("first_visit", "First visit"),
                            ("routine_visit", "Routine visit"),
                            ("revisit", "Revisit"),
                        ],
                        default=None,
                        max_length=15,
                        null=True,
                    ),
                ),
                ("visit_date", models.DateField(default=None, null=True)),
                (
                    "overall_risk_value",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("very_low", "Very low risk"),
                            ("lower", "Lower risk"),
                            ("medium", "Medium risk"),
                            ("higher", "Higher risk"),
                            ("highest", "Highest risk"),
                        ],
                        default=None,
                        max_length=10,
                        null=True,
                    ),
                ),
                ("licence_risk_value", models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ("overview", models.TextField(default=None, null=True)),
                ("inspection", models.TextField(default=None, null=True)),
                ("compliance_overview", models.TextField(default=None, null=True)),
                (
                    "compliance_risk_value",
                    models.CharField(
                        choices=[
                            ("very_low", "Very low risk"),
                            ("lower", "Lower risk"),
                            ("medium", "Medium risk"),
                            ("higher", "Higher risk"),
                            ("highest", "Highest risk"),
                        ],
                        default=None,
                        max_length=10,
                        null=True,
                    ),
                ),
                ("individuals_overview", models.TextField(default=None, null=True)),
                (
                    "individuals_risk_value",
                    models.CharField(
                        choices=[
                            ("very_low", "Very low risk"),
                            ("lower", "Lower risk"),
                            ("medium", "Medium risk"),
                            ("higher", "Higher risk"),
                            ("highest", "Highest risk"),
                        ],
                        default=None,
                        max_length=10,
                        null=True,
                    ),
                ),
                ("products_overview", models.TextField(default=None, null=True)),
                (
                    "products_risk_value",
                    models.CharField(
                        choices=[
                            ("very_low", "Very low risk"),
                            ("lower", "Lower risk"),
                            ("medium", "Medium risk"),
                            ("higher", "Higher risk"),
                            ("highest", "Highest risk"),
                        ],
                        default=None,
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "site_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="visit_case",
                        to="compliance.compliancesitecase",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("cases.case",),
        ),
        migrations.CreateModel(
            name="CompliancePerson",
            fields=[
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created_at"
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="updated_at"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("job_title", models.CharField(max_length=100)),
                (
                    "visit_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="people_present",
                        to="compliance.compliancevisitcase",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
