# Generated by Django 4.2.16 on 2024-12-13 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0001_squashed_0005_auto_20200625_0857"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OpenLicenceReturns",
        ),
    ]
