# Generated by Django 4.2.9 on 2024-02-16 14:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("document_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(null=True)),
                ("task_id", models.UUIDField()),
            ],
        ),
    ]
