# Generated by Django 4.2.9 on 2024-02-16 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("document_data", "0002_backuplog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="backuplog",
            options={"ordering": ["-started_at"]},
        ),
    ]
