# Generated by Django 4.2.9 on 2024-02-16 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("document_data", "0003_alter_backuplog_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="backuplog",
            options={"get_latest_by": ["started_at"], "ordering": ["started_at"]},
        ),
    ]
