# Generated by Django 2.2 on 2019-04-30 15:48

import uuid

from django.db import migrations, models


def init(apps, schema_editor):
    # We can't import the Address model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Address = apps.get_model('addresses', 'Address')
    if not Address.objects.all():
        address = Address(id='00000000-0000-0000-0000-000000000000',
                          country='ENG',
                          address_line_1='DOES NOT EXIST',
                          region='none',
                          postcode='AA11AA',
                          city='none')
        address.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.TextField(default=None)),
                ('address_line_1', models.TextField(default=None)),
                ('address_line_2', models.TextField(blank=True, null=True, default=None)),
                ('region', models.TextField(default=None)),
                ('postcode', models.CharField(max_length=10)),
                ('city', models.TextField(default=None)),
            ],
        ),
        migrations.RunPython(init),
    ]
