# Generated by Django 2.2.11 on 2020-03-19 14:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("countries", "0001_initial"),
        ("addresses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForeignAddress",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("address", models.TextField(default=None)),
                ("country", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="countries.Country")),
            ],
        ),
    ]
