# Generated by Django 2.2.11 on 2020-03-22 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0002_foreignaddress"),
    ]

    operations = [
        migrations.AlterModelTable(name="address", table="address",),
        migrations.AlterModelTable(name="foreignaddress", table="foreign_address",),
    ]
