# Generated by Django 2.2.11 on 2020-04-27 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_auto_20200307_1805"),
    ]

    operations = [
        migrations.AlterModelTable(name="team", table="team",),
    ]
