# Generated by Django 2.2.9 on 2020-01-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flags", "0002_timestampable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flag", name="name", field=models.CharField(default="Untitled Flag", max_length=25),
        ),
    ]
