# Generated by Django 2.2.9 on 2020-01-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0002_timestampable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='name',
            field=models.TextField(default='Untitled Flag', max_length=25),
        ),
    ]
