# Generated by Django 2.2.11 on 2020-03-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flags", "0004_auto_20200326_1548"),
    ]

    operations = [
        migrations.AddField(
            model_name="flag",
            name="colour",
            field=models.CharField(
                choices=[
                    ("Default", "Default"),
                    ("Red", "Red"),
                    ("Yellow", "Yellow"),
                    ("Green", "Green"),
                    ("Blue", "Blue"),
                    ("Purple", "Purple"),
                    ("Orange", "Orange"),
                    ("Brown", "Brown"),
                    ("Turquoise", "Turquoise"),
                    ("Pink", "Pink"),
                ],
                default="Default",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="flag", name="label", field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
