# Generated by Django 2.2.11 on 2020-04-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0005_auto_20200331_1537'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='flaggingrule',
            name='flags_flagg_created_0d8cd4_idx',
        ),
        migrations.AddIndex(
            model_name='flaggingrule',
            index=models.Index(fields=['created_at'], name='flagging_ru_created_7400b0_idx'),
        ),
        migrations.AlterModelTable(
            name='flag',
            table='flag',
        ),
        migrations.AlterModelTable(
            name='flaggingrule',
            table='flagging_rule',
        ),
    ]
