# Generated by Django 2.1.7 on 2019-03-20 15:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0002_organisation_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, default=None, max_length=254)),
                ('password', models.TextField(blank=True, default=None)),
                ('organisation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation')),
            ],
        ),
    ]
