# Generated by Django 2.2.4 on 2019-11-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="name",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
