# Generated by Django 2.2.4 on 2019-11-28 16:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="permission", options={"ordering": ["name"]},),
        migrations.AddField(
            model_name="permission",
            name="type",
            field=models.CharField(
                choices=[("exporter", "Exporter"), ("internal", "Internal")], default="internal", max_length=30
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="organisation",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="organisations.Organisation"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="type",
            field=models.CharField(
                choices=[("exporter", "Exporter"), ("internal", "Internal")], default="internal", max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="permission", name="name", field=models.CharField(default="permission - FIX", max_length=80),
        ),
        migrations.CreateModel(
            name="UserOrganisationRelationship",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Deactivated", "Deactivated")], default="Active", max_length=20
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="organisations.Organisation"),
                ),
                (
                    "role",
                    models.ForeignKey(
                        default=uuid.UUID("00000000-0000-0000-0000-000000000004"),
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exporter_role",
                        to="users.Role",
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.ExporterUser")),
            ],
            options={"abstract": False,},
        ),
    ]
