# Generated by Django 2.2.3 on 2019-07-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_govuserrevisionmeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254),
        ),
    ]
