# Generated by Django 2.2.3 on 2019-07-12 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_notifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='note_id',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='notifications',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='notifications',
            old_name='viewed',
            new_name='viewed_at',
        ),
    ]
