# Generated by Django 2.2.8 on 2020-02-07 17:52

from django.db import migrations, models

from users.enums import UserType


def forward_step(apps, schema_editor):
    ExporterUser = apps.get_model("users", "ExporterUser")
    for exporter in ExporterUser.objects.all():
        exporter.type = UserType.EXPORTER
        exporter.save()
    GovUser = apps.get_model("users", "GovUser")
    for govuser in GovUser.objects.all():
        govuser.type = UserType.INTERNAL
        govuser.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_role_statuses"),
    ]

    operations = [
        migrations.AlterModelOptions(name="baseuser", options={},),
        migrations.AddField(
            model_name="baseuser",
            name="type",
            field=models.CharField(
                choices=[("exporter", "Exporter"), ("internal", "Internal")], max_length=8, blank=True, null=True
            ),
            preserve_default=False,
        ),
        migrations.RunPython(forward_step),
        migrations.AlterField(
            model_name="baseuser",
            name="type",
            field=models.CharField(choices=[("exporter", "Exporter"), ("internal", "Internal")], max_length=8,),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(name="baseuser", unique_together={("email", "type")},),
    ]
