# Generated by Django 2.1.7 on 2019-03-20 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190320_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='organisation',
            new_name='organisation_id',
        ),
    ]
