# Generated by Django 2.2.4 on 2019-08-19 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_auto_20190819_1511"),
    ]

    operations = [
        migrations.RemoveField(model_name="baseuser", name="password",),
    ]
