# Generated by Django 2.2.11 on 2020-03-22 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_auto_20200319_2300"),
    ]

    operations = [
        migrations.AlterModelOptions(name="baseuser", options={"ordering": ["first_name", "last_name"]},),
    ]
