# Generated by Django 2.2.4 on 2019-08-15 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userorganisationrelationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorganisationrelationship',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='userorganisationrelationship',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_organisation_assignments', to='organisations.Organisation'),
        ),
        migrations.AlterField(
            model_name='userorganisationrelationship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_organisation_assignments', to='users.ExporterUser'),
        ),
    ]
