# Generated by Django 2.1.7 on 2019-03-20 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190320_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='organisation_id',
            new_name='organisation',
        ),
    ]
