# Generated by Django 2.2.4 on 2019-08-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190815_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorganisationrelationship',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
