# Generated by Django 2.2.11 on 2020-04-24 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_auto_20200322_1547"),
    ]

    operations = [
        migrations.AlterModelOptions(name="baseuser", options={"ordering": ["first_name", "last_name", "created_at"]},),
    ]
