# Generated by Django 2.2.11 on 2020-04-07 15:46

from django.db import migrations


def remove_duplicates(apps, schema_editor):
    UserOrganisationRelationship = apps.get_model("users", "UserOrganisationRelationship")
    relationships = UserOrganisationRelationship.objects.all()
    organisations = relationships.values_list("organisation", flat=True)
    users = relationships.values_list("user", flat=True)
    for organisation in organisations:
        for user in users:
            matches = UserOrganisationRelationship.objects.filter(organisation__id=organisation, user__id=user)
            if matches.count() > 1:
                matches.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_auto_20200326_1420'),
        ('users', '0005_auto_20200322_1547'),
    ]

    operations = [
        migrations.RunPython(remove_duplicates),
    ]
