# Generated by Django 2.2.4 on 2019-09-14 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_auto_20190819_1523"),
    ]

    operations = [
        migrations.DeleteModel(name="GovUserRevisionMeta",),
    ]
