# Generated by Django 2.2.4 on 2019-08-15 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190815_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorganisationrelationship',
            name='email',
        ),
    ]
