# Generated by Django 2.2 on 2019-04-29 15:38

import enumchoicefield.fields
from django.db import migrations

import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190418_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=enumchoicefield.fields.EnumChoiceField(default=users.models.UserStatuses(2), enum_class=users.models.UserStatuses, max_length=11),
        ),
    ]
