# Generated by Django 2.2.11 on 2020-04-29 15:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_auto_20200424_1136"),
    ]

    operations = [
        migrations.AddField(
            model_name="govuser",
            name="default_queue",
            field=models.UUIDField(default=uuid.UUID("00000000-0000-0000-0000-000000000001")),
        ),
    ]
