# Generated by Django 2.2.11 on 2020-04-07 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_auto_20200326_1420'),
        ('users', '0006_auto_20200407_1546'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userorganisationrelationship',
            unique_together={('user', 'organisation')},
        ),
    ]
