# Generated by Django 2.2.4 on 2019-11-25 17:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0007_organisation_flags'),
        ('users', '0008_auto_20191120_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='permission',
            name='type',
            field=models.CharField(choices=[('exporter', 'Exporter'), ('internal', 'Internal')], default='internal', max_length=30),
        ),
        migrations.AddField(
            model_name='role',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation'),
        ),
        migrations.AddField(
            model_name='role',
            name='type',
            field=models.CharField(choices=[('exporter', 'Exporter'), ('internal', 'Internal')], default='internal', max_length=30),
        ),
        migrations.AddField(
            model_name='userorganisationrelationship',
            name='role',
            field=models.ForeignKey(default=uuid.UUID('00000000-0000-0000-0000-000000000004'), on_delete=django.db.models.deletion.PROTECT, related_name='exporter_role', to='users.Role'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(default='permission - FIX', max_length=80),
        ),
    ]
