# Generated by Django 2.2.4 on 2019-11-15 11:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_assess_goods_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='govuser',
            name='role',
            field=models.ForeignKey(default=uuid.UUID('00000000-0000-0000-0000-000000000001'), on_delete=django.db.models.deletion.PROTECT, related_name='role', to='users.Role'),
        ),
    ]
