# Generated by Django 2.2.4 on 2019-11-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_auto_20191114_1621"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="name",
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
