# Generated by Django 2.2.4 on 2019-11-15 17:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0007_organisation_flags'),
        ('users', '0009_auto_20191114_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='exporteruser',
            name='role',
            field=models.ForeignKey(default=uuid.UUID('00000000-0000-0000-0000-000000000004'), on_delete=django.db.models.deletion.PROTECT, related_name='exporter_role', to='users.Role'),
        ),
        migrations.AddField(
            model_name='permission',
            name='type',
            field=models.CharField(choices=[('exporter', 'Exporter'), ('internal', 'Internal')], default='internal', max_length=30),
        ),
        migrations.AddField(
            model_name='role',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation'),
        ),
        migrations.AddField(
            model_name='role',
            name='type',
            field=models.CharField(choices=[('exporter', 'Exporter'), ('internal', 'Internal')], default='internal', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='govuser',
            name='role',
            field=models.ForeignKey(default=uuid.UUID('00000000-0000-0000-0000-000000000001'), on_delete=django.db.models.deletion.PROTECT, related_name='internal_role', to='users.Role'),
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('id', 'type')},
        ),
    ]
