# Generated by Django 2.2.12 on 2020-06-03 12:52

from django.db import migrations


def forward_migration(apps, schema_editor):
    BaseUser = apps.get_model("users", "BaseUser")

    base_users = BaseUser.objects.all()
    for base_user in base_users:
        base_user.email = base_user.email.lower()
        base_user.save()


def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_auto_20200603_1252"),
    ]

    operations = [migrations.RunPython(forward_migration, reverse_migration)]
