# Generated by Django 2.2.10 on 2020-02-14 16:39

from django.db import migrations, models
import django.db.models.deletion
import separatedvaluesfield.models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "004_remove_baseapplication_application_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="F680ClearanceApplication",
            fields=[
                (
                    "baseapplication_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="applications.BaseApplication",
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("applications.baseapplication",),
        ),
        migrations.CreateModel(
            name="GiftingClearanceApplication",
            fields=[
                (
                    "baseapplication_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="applications.BaseApplication",
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("applications.baseapplication",),
        ),
        migrations.AddField(
            model_name="standardapplication",
            name="goods_categories",
            field=separatedvaluesfield.models.SeparatedValuesField(
                blank=True,
                choices=[
                    ("anti_piracy", "Anti-piracy"),
                    ("maritime_anti_piracy", "Maritime anti-piracy"),
                    ("firearms", "Firearms"),
                    ("incorporated_goods", "Incorporated goods"),
                ],
                default=None,
                max_length=150,
                null=True,
            ),
        ),
    ]
