# Generated by Django 2.2.10 on 2020-02-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0006_auto_20200217_1634"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseapplication",
            name="clearance_level",
            field=models.CharField(
                choices=[
                    ("uk_unclassified", "UK unclassified"),
                    ("uk_official", "UK official"),
                    ("uk_official_sensitive", "UK official - sensitive"),
                    ("uk_secret", "UK secret"),
                    ("uk_top_secret", "UK top secret"),
                    ("nato_unclassified", "NATO unclassified"),
                    ("nato_confidential", "NATO confidential"),
                    ("nato_restricted", "NATO restricted"),
                    ("nato_secret", "NATO secret"),
                    ("occar_unclassified", "OCCAR unclassified"),
                    ("occar_confidential", "OCCAR confidential"),
                    ("occar_restricted", "OCCAR restricted"),
                    ("occar_secret", "OCCAR secret"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
