# Generated by Django 2.2.10 on 2020-03-06 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0010_auto_20200304_1344"),
        ("applications", "0010_auto_20200303_1626"),
    ]

    operations = []
