# Generated by Django 2.2.10 on 2020-03-11 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0012_auto_20200309_1335"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="baseapplication",
            options={"ordering": ["created_at"]},
        ),
    ]
