# Generated by Django 2.2.11 on 2020-03-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0020_auto_20200326_1644"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseapplication",
            name="agreed_to_foi",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
