# Generated by Django 2.2.11 on 2020-04-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0024_auto_20200401_1542"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodonapplication",
            name="licenced_quantity",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="goodonapplication",
            name="licenced_value",
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=256, null=True),
        ),
        migrations.AddField(
            model_name="goodonapplication",
            name="usage",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
