# Generated by Django 2.2.12 on 2020-05-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0030_auto_20200518_1530"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exhibitionclearanceapplication",
            name="reason_for_clearance",
            field=models.TextField(blank=True, default=None, max_length=2000, null=True),
        ),
    ]
