# Generated by Django 2.2.13 on 2020-07-03 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0033_auto_20200612_1342"),
        ("licences", "0011_map_goodonapplication_to_goodonlicence"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goodonapplication",
            name="licenced_quantity",
        ),
        migrations.RemoveField(
            model_name="goodonapplication",
            name="licenced_value",
        ),
        migrations.RemoveField(
            model_name="goodonapplication",
            name="usage",
        ),
    ]
