# Generated by Django 2.2.13 on 2020-07-09 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0034_auto_20200703_1021"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="standardapplication",
            name="contains_firearm_goods",
        ),
    ]
