# Generated by Django 2.2.16 on 2020-09-24 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("control_list_entries", "0005_auto_20200519_1617"),
        ("goodstype", "0005_auto_20200924_1731"),
        ("applications", "0035_remove_standardapplication_contains_firearm_goods"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodonapplication",
            name="comment",
            field=models.TextField(blank=True, default=None, help_text="control review comment", null=True),
        ),
        migrations.AddField(
            model_name="goodonapplication",
            name="control_list_entries",
            field=models.ManyToManyField(to="control_list_entries.ControlListEntry"),
        ),
        migrations.AddField(
            model_name="goodonapplication",
            name="is_good_controlled",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="goodonapplication",
            name="report_summary",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="goodonapplication",
            name="application",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="applications.BaseApplication"),
        ),
    ]
