# Generated by Django 2.2.16 on 2020-09-24 10:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('control_list_entries', '0005_auto_20200519_1617'),
        ('goods', '0014_auto_20200702_1113'),
        ('goodstype', '0004_auto_20200423_1456'),
        ('applications', '0035_remove_standardapplication_contains_firearm_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodControlReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created_at')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='updated_at')),
                ('is_controlled', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unsure', "I don't know")], default='unsure', max_length=20)),
                ('comment', models.TextField(blank=True, default=None, max_length=2000, null=True)),
                ('control_list_entries', models.ManyToManyField(related_name='good_control_reviews', to='control_list_entries.ControlListEntry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='goodonapplication',
            name='control_review',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.GoodControlReview'),
        ),
    ]
