# Generated by Django 2.2.16 on 2020-09-25 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0036_auto_20200924_1731"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodonapplication",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="goods", to="applications.BaseApplication"
            ),
        ),
    ]
