# Generated by Django 2.2.16 on 2020-11-04 10:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0038_goodonapplication_end_use_control"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodonapplication",
            name="end_use_control",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                default=list,
                help_text="Control code given to good due to the end use e.g, a wood screw may be used in a Harrier jump jet.",
                size=None,
            ),
        ),
    ]
