# Generated by Django 2.2.16 on 2020-11-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0038_goodonapplication_end_use_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseapplication',
            name='foi_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
