# Generated by Django 2.2.16 on 2020-12-13 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0041_goodonapplication_is_precedent"),
        ("applications", "0041_goodonapplicationdocument"),
    ]

    operations = []
