# Generated by Django 2.2.17 on 2021-01-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0042_merge_20201213_0228"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseapplication", name="foi_reason", field=models.TextField(blank=True, default=""),
        ),
    ]
