# Generated by Django 2.2.17 on 2021-01-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flags", "0010_flaggingrule_excluded_values"),
        ("applications", "0045_remove_denialmatchonapplication_denial"),
    ]

    operations = [
        migrations.AddField(
            model_name="partyonapplication",
            name="flags",
            field=models.ManyToManyField(related_name="parties_on_application", to="flags.Flag"),
        ),
    ]
