# Generated by Django 3.1.8 on 2021-08-09 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("control_list_entries", "0002_controllistentry_controlled"),
        ("applications", "0046_partyonapplication_flags"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="GoodOnApplicationControlListEntry",
                    fields=[
                        (
                            "id",
                            models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                        ),
                        (
                            "controllistentry",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="controllistentry",
                                to="control_list_entries.controllistentry",
                            ),
                        ),
                        (
                            "goodonapplication",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="goods",
                                to="applications.goodonapplication",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "applications_goodonapplication_control_list_entries",
                    },
                ),
                migrations.AlterField(
                    model_name="goodonapplication",
                    name="control_list_entries",
                    field=models.ManyToManyField(
                        through="applications.GoodOnApplicationControlListEntry",
                        to="control_list_entries.ControlListEntry",
                    ),
                ),
            ]
        )
    ]
