# Generated by Django 3.1.12 on 2021-11-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0047_auto_20210809_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardapplication',
            name='goods_recipients',
            field=models.CharField(choices=[('direct_to_end_user', 'Directly to the end-user'), ('via_consignee', 'To an end-user via a consignee'), ('via_consignee_and_third_parties', 'To an end-user via a consignee, with additional third parties')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='standardapplication',
            name='goods_starting_point',
            field=models.CharField(choices=[('GB', 'Great Britain'), ('NI', 'Northern Ireland')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='standardapplication',
            name='export_type',
            field=models.CharField(blank=True, choices=[('permanent', 'Permanent'), ('temporary', 'Temporary')], default='', max_length=50),
        ),
    ]
