# Generated by Django 3.1.13 on 2021-12-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0048_auto_20211124_1526"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="standardapplication",
            name="goods_recipients",
        ),
        migrations.RemoveField(
            model_name="standardapplication",
            name="goods_starting_point",
        ),
        migrations.AlterField(
            model_name="standardapplication",
            name="export_type",
            field=models.CharField(
                choices=[("permanent", "Permanent"), ("temporary", "Temporary")], default=None, max_length=50
            ),
        ),
    ]
