# Generated by Django 2.2.10 on 2020-02-11 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_auto_20200210_1326"),
    ]

    operations = [
        migrations.RemoveField(model_name="baseapplication", name="application_type",),
    ]
