# Generated by Django 3.2.12 on 2022-04-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0050_auto_20211210_1618"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationdocument",
            name="document_type",
            field=models.TextField(
                blank=True,
                choices=[
                    ("section-one-certificate", "Firearm Section 1 certificate"),
                    ("section-two-certificate", "Firearm Section 2 certificate"),
                    ("section-five-certificate", "Firearm Section 5 certificate"),
                    ("rfd-certificate", "Registered Firearm Dealer certificate"),
                ],
                default=None,
                null=True,
            ),
        ),
    ]
