# Generated by Django 3.2.13 on 2022-05-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0051_applicationdocument_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodonapplicationdocument",
            name="document_type",
            field=models.TextField(
                blank=True,
                choices=[
                    ("section-one-certificate", "Firearm Section 1 certificate"),
                    ("section-two-certificate", "Firearm Section 2 certificate"),
                    ("section-five-certificate", "Firearm Section 5 certificate"),
                    ("rfd-certificate", "Registered Firearm Dealer certificate"),
                ],
                default=None,
                null=True,
            ),
        ),
    ]
