# Generated by Django 3.2.13 on 2022-05-03 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0052_goodonapplicationdocument_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodonapplicationdocument",
            name="good_on_application",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="applications.goodonapplication"
            ),
        ),
    ]
