# Generated by Django 3.2.13 on 2022-05-03 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0053_goodonapplicationdocument_good_on_application"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodonapplicationdocument",
            name="good_on_application",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="applications.goodonapplication"
            ),
        ),
    ]
