# Generated by Django 3.2.13 on 2022-05-13 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
        ("applications", "0054_alter_goodonapplicationdocument_good_on_application"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoodOnApplicationInternalDocument",
            fields=[
                (
                    "document_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="documents.document",
                    ),
                ),
                ("document_title", models.TextField(blank=True, default="", null=True)),
                (
                    "good_on_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="good_on_application_internal_documents",
                        to="applications.goodonapplication",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("documents.document",),
        ),
    ]
