# Generated by Django 3.2.15 on 2022-09-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0056_auto_20220808_1433"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodonapplication",
            name="unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TON", "Tonne(s)"),
                    ("KGM", "Kilogram(s)"),
                    ("GRM", "Gram(s)"),
                    ("MIM", "Milligrams(s)"),
                    ("MCM", "Micrograms(s)"),
                    ("NAR", "Number of articles"),
                    ("MTK", "Square metre(s)"),
                    ("MTR", "Metre(s)"),
                    ("LTR", "Litre(s)"),
                    ("MTR", "Millilitre(s)"),
                    ("MTQ", "Cubic metre(s)"),
                    ("ITG", "Intangible"),
                ],
                default=None,
                max_length=50,
                null=True,
            ),
        ),
    ]
