# Generated by Django 3.2.15 on 2022-09-21 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0060_alter_goodonapplication_unit"),
        ("applications", "0060_auto_20220920_1725"),
    ]

    operations = []
