# Generated by Django 3.2.15 on 2022-09-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0061_merge_20220921_1040"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="standardapplication",
            name="is_f1686_approval_document_available",
        ),
    ]
