# Generated by Django 3.2.15 on 2022-09-22 15:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("regimes", "0001_initial"),
        ("applications", "0062_auto_20220921_1148"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoodOnApplicationRegimeEntry",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "good_on_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="good_on_applications",
                        to="applications.goodonapplication",
                    ),
                ),
                (
                    "regime_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regime_entries",
                        to="regimes.regimeentry",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="goodonapplication",
            name="regime_entries",
            field=models.ManyToManyField(through="applications.GoodOnApplicationRegimeEntry", to="regimes.RegimeEntry"),
        ),
    ]
