# Generated by Django 3.2.16 on 2022-11-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0063_auto_20220922_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdocument',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
