# Generated by Django 3.2.16 on 2022-11-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0064_alter_applicationdocument_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="f680clearanceapplication",
            name="electronic_warfare_requirement",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="f680clearanceapplication",
            name="expedited",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="f680clearanceapplication",
            name="foreign_technology",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="f680clearanceapplication",
            name="locally_manufactured",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="f680clearanceapplication",
            name="uk_service_equipment",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
