# Generated by Django 3.2.15 on 2022-12-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0065_auto_20221125_1118"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodonapplication",
            name="is_nca_applicable",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="goodonapplication",
            name="nsg_assessment_note",
            field=models.TextField(blank=True, default="", help_text="Trigger list assessment note"),
        ),
        migrations.AddField(
            model_name="goodonapplication",
            name="nsg_list_type",
            field=models.CharField(
                blank=True,
                choices=[("TRIGGER_LIST", "Trigger List"), ("DUAL_USE", "Dual Use")],
                default="",
                max_length=32,
            ),
        ),
    ]
