# Generated by Django 3.2.16 on 2023-01-26 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("report_summaries", "0005_update_picklist_casing"),
        ("applications", "0066_auto_20221208_1426"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodonapplication",
            name="report_summary_prefix",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="report_summaries.reportsummaryprefix"
            ),
        ),
        migrations.AddField(
            model_name="goodonapplication",
            name="report_summary_subject",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="report_summaries.reportsummarysubject"
            ),
        ),
    ]
