# Generated by Django 3.2.16 on 2023-02-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0067_auto_20230201_1528"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodonapplication",
            name="is_trigger_list_guidelines_applicable",
            field=models.BooleanField(
                blank=True, default=None, help_text="Do the trigger list guidelines apply to this product?", null=True
            ),
        ),
    ]
