# Generated by Django 3.2.18 on 2023-02-23 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("report_summaries", "0005_update_picklist_casing"),
        ("applications", "0068_goodonapplication_is_trigger_list_guidelines_applicable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodonapplication",
            name="report_summary_prefix",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prefix_good_on_application",
                to="report_summaries.reportsummaryprefix",
            ),
        ),
        migrations.AlterField(
            model_name="goodonapplication",
            name="report_summary_subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subject_good_on_application",
                to="report_summaries.reportsummarysubject",
            ),
        ),
    ]
