# Generated by Django 3.2.20 on 2023-08-17 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("appeals", "0001_initial"),
        ("applications", "0070_goodonapplication_is_ncsc_military_information_security"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseapplication",
            name="appeal",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="appeals.appeal"
            ),
        ),
    ]
