# Generated by Django 3.2.18 on 2023-08-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0071_baseapplication_appeal"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseapplication",
            name="appeal_deadline",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="Date before which Exporter can initiate an appeal on a refusal",
                null=True,
            ),
        ),
    ]
