# Generated by Django 3.2.21 on 2023-10-16 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_value_for_pending_field"),
        ("applications", "0072_baseapplication_appeal_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodonapplication",
            name="assessed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="assessed_by",
                to="users.govuser",
            ),
        ),
        migrations.AddField(
            model_name="goodonapplication",
            name="assessment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
