# Generated by Django 4.2.9 on 2024-03-12 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0078_remove_f680clearanceapplication_baseapplication_ptr_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="openapplication",
            name="baseapplication_ptr",
        ),
        migrations.DeleteModel(
            name="CountryOnApplication",
        ),
        migrations.DeleteModel(
            name="OpenApplication",
        ),
    ]
