# Generated by Django 4.2.11 on 2024-05-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report_summaries", "0006_reportsummary"),
        ("applications", "0079_remove_openapplication_baseapplication_ptr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodonapplication",
            name="report_summaries",
            field=models.ManyToManyField(related_name="goods_on_application", to="report_summaries.reportsummary"),
        ),
    ]
