# Generated by Django 4.2.11 on 2024-03-14 14:21

from django.db import migrations, models


def populate_moved_fields(apps, schema_editor):
    BaseApplication = apps.get_model("applications", "BaseApplication")
    StandardApplication = apps.get_model("applications", "StandardApplication")

    for standard_application in StandardApplication.objects.all():
        base_application = standard_application.baseapplication

        standard_application.is_military_end_use_controls = base_application.is_military_end_use_controls_base
        standard_application.military_end_use_controls_ref = base_application.military_end_use_controls_ref_base
        standard_application.is_informed_wmd = base_application.is_informed_wmd_base
        standard_application.informed_wmd_ref = base_application.informed_wmd_ref_base
        standard_application.is_suspected_wmd = base_application.is_suspected_wmd_base
        standard_application.suspected_wmd_ref = base_application.suspected_wmd_ref_base
        standard_application.is_eu_military = base_application.is_eu_military_base
        standard_application.is_compliant_limitations_eu = base_application.is_compliant_limitations_eu_base
        standard_application.compliant_limitations_eu_ref = base_application.compliant_limitations_eu_ref_base
        standard_application.save()


def reverse_populate_moved_fields(apps, schema_editor):
    BaseApplication = apps.get_model("applications", "BaseApplication")
    StandardApplication = apps.get_model("applications", "StandardApplication")

    for standard_application in StandardApplication.objects.all():
        base_application = standard_application.baseapplication

        base_application.is_military_end_use_controls_base = standard_application.is_military_end_use_controls
        base_application.military_end_use_controls_ref_base = standard_application.military_end_use_controls_ref
        base_application.is_informed_wmd_base = standard_application.is_informed_wmd
        base_application.informed_wmd_ref_base = standard_application.informed_wmd_ref
        base_application.is_suspected_wmd_base = standard_application.is_suspected_wmd
        base_application.suspected_wmd_ref_base = standard_application.suspected_wmd_ref
        base_application.is_eu_military_base = standard_application.is_eu_military
        base_application.is_compliant_limitations_eu_base = standard_application.is_compliant_limitations_eu
        base_application.compliant_limitations_eu_ref_base = standard_application.compliant_limitations_eu_ref
        base_application.save()


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0079_delete_applicationdenialreason"),
    ]

    operations = [
        migrations.RenameField(
            model_name="baseapplication",
            old_name="compliant_limitations_eu_ref",
            new_name="compliant_limitations_eu_ref_base",
        ),
        migrations.RenameField(
            model_name="baseapplication",
            old_name="informed_wmd_ref",
            new_name="informed_wmd_ref_base",
        ),
        migrations.RenameField(
            model_name="baseapplication",
            old_name="is_compliant_limitations_eu",
            new_name="is_compliant_limitations_eu_base",
        ),
        migrations.RenameField(
            model_name="baseapplication",
            old_name="is_eu_military",
            new_name="is_eu_military_base",
        ),
        migrations.RenameField(
            model_name="baseapplication",
            old_name="is_informed_wmd",
            new_name="is_informed_wmd_base",
        ),
        migrations.RenameField(
            model_name="baseapplication",
            old_name="is_military_end_use_controls",
            new_name="is_military_end_use_controls_base",
        ),
        migrations.RenameField(
            model_name="baseapplication",
            old_name="is_suspected_wmd",
            new_name="is_suspected_wmd_base",
        ),
        migrations.RenameField(
            model_name="baseapplication",
            old_name="military_end_use_controls_ref",
            new_name="military_end_use_controls_ref_base",
        ),
        migrations.RenameField(
            model_name="baseapplication",
            old_name="suspected_wmd_ref",
            new_name="suspected_wmd_ref_base",
        ),
        migrations.AddField(
            model_name="standardapplication",
            name="compliant_limitations_eu_ref",
            field=models.CharField(blank=True, default=None, max_length=2200, null=True),
        ),
        migrations.AddField(
            model_name="standardapplication",
            name="informed_wmd_ref",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="standardapplication",
            name="is_compliant_limitations_eu",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="standardapplication",
            name="is_eu_military",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="standardapplication",
            name="is_informed_wmd",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="standardapplication",
            name="is_military_end_use_controls",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="standardapplication",
            name="is_suspected_wmd",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="standardapplication",
            name="military_end_use_controls_ref",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="standardapplication",
            name="suspected_wmd_ref",
            field=models.CharField(blank=True, default=None, max_length=2200, null=True),
        ),
        migrations.RunPython(populate_moved_fields, reverse_populate_moved_fields),
        migrations.RemoveField(
            model_name="baseapplication",
            name="compliant_limitations_eu_ref",
        ),
        migrations.RemoveField(
            model_name="baseapplication",
            name="informed_wmd_ref",
        ),
        migrations.RemoveField(
            model_name="baseapplication",
            name="is_compliant_limitations_eu",
        ),
        migrations.RemoveField(
            model_name="baseapplication",
            name="is_eu_military",
        ),
        migrations.RemoveField(
            model_name="baseapplication",
            name="is_informed_wmd",
        ),
        migrations.RemoveField(
            model_name="baseapplication",
            name="is_military_end_use_controls",
        ),
        migrations.RemoveField(
            model_name="baseapplication",
            name="is_suspected_wmd",
        ),
        migrations.RemoveField(
            model_name="baseapplication",
            name="military_end_use_controls_ref",
        ),
        migrations.RemoveField(
            model_name="baseapplication",
            name="suspected_wmd_ref",
        ),
    ]
