# Generated by Django 4.2.11 on 2024-04-03 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0079_remove_openapplication_baseapplication_ptr_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="F680Application",
            fields=[
                (
                    "baseapplication_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="applications.baseapplication",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("applications.baseapplication",),
        ),
    ]
