# Generated by Django 4.2.11 on 2024-03-13 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0079_remove_openapplication_baseapplication_ptr_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ApplicationDenialReason",
        ),
    ]
