# Generated by Django 4.2.9 on 2024-04-03 23:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0080_f680application"),
    ]

    operations = [
        migrations.AddField(
            model_name="f680application",
            name="armed_forces_usage",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="f680application",
            name="armed_forces_usage_details",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="f680application",
            name="clearances",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("MARKET_SURVEY_DISCUSSION_PROMOTION", "Market Survey/Initial Discussions/Promotion"),
                        ("DEMO_UK_OVERSEAS_CUSTOMERS", "Demonstration in the United Kingdom to overseas customers"),
                        ("DEMO_OVERSEAS", "Demonstration overseas"),
                        ("TRAINING", "Training"),
                        ("THROUGH_LIFE_SUPPORT", "Through Life Support"),
                    ],
                    max_length=255,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="f680application",
            name="cryptography",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="indicates whether any of the items designed or modified to use cryptographic techniques",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="f680application",
            name="ew_data",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="f680application",
            name="exceptional_circumstances",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="f680application",
            name="foreign_technology_information",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="f680application",
            name="foreign_technology_information_details",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="f680application",
            name="is_list_X_company",
            field=models.BooleanField(
                blank=True, default=None, help_text="indicates whether it is a list X company or site", null=True
            ),
        ),
        migrations.AddField(
            model_name="f680application",
            name="is_list_X_company_other_information",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="f680application",
            name="is_local_assembly_manufacture",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="f680application",
            name="is_local_assembly_manufacture_details",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="f680application",
            name="open_licence_more_details",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="f680application",
            name="other_information",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="f680application",
            name="product_funding",
            field=models.TextField(
                blank=True,
                choices=[("MOD", "MOD"), ("PART_MOD", "Part MOD"), ("PRIVATE_VENTURE", "Private venture")],
                default="",
            ),
        ),
        migrations.AddField(
            model_name="f680application",
            name="product_mtcr_rating_type",
            field=models.TextField(
                blank=True,
                choices=[
                    ("YES_MTCR_CAT1", "Yes - MTCR Cat 1"),
                    ("YES_MTCR_CAT2", "Yes - MTCR Cat 2"),
                    ("NO", "No"),
                    ("DONT_KNOW", "Don't know"),
                ],
                default="",
            ),
        ),
        migrations.AddField(
            model_name="f680application",
            name="product_mtcr_rating_type_details",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="f680application",
            name="requires_open_licence",
            field=models.BooleanField(
                blank=True, default=None, help_text="does this clearance requires an open licence", null=True
            ),
        ),
    ]
