# Generated by Django 4.2.13 on 2024-06-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0081_rename_denial_denialmatchonapplication_denial_entity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodonapplication",
            name="unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NAR", "Items"),
                    ("TON", "Tonnes"),
                    ("KGM", "Kilograms"),
                    ("GRM", "Grams"),
                    ("MGM", "Milligrams"),
                    ("MCG", "Micrograms"),
                    ("MTR", "Metres"),
                    ("MTK", "Square metres"),
                    ("MTQ", "Cubic metres"),
                    ("LTR", "Litres"),
                    ("MLT", "Millilitres"),
                    ("MCL", "Microlitres"),
                ],
                default=None,
                max_length=50,
                null=True,
            ),
        ),
    ]
