# Generated by Django 4.2.11 on 2024-03-18 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0081_remove_baseapplication_compliant_limitations_eu_ref_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="baseapplication",
            name="usage",
        ),
    ]
