# Generated by Django 4.2.11 on 2024-04-25 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0081_f680application_armed_forces_usage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenApplication",
            fields=[
                (
                    "baseapplication_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="applications.baseapplication",
                    ),
                ),
                (
                    "goods_category",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("military", "Military or dual use"),
                            ("cryptographic", "Cryptographic"),
                            ("media", "Media"),
                            ("uk_continental_shelf", "UK continental shelf"),
                            ("dealer", "Dealer"),
                        ],
                        default="",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("applications.baseapplication",),
        ),
    ]
