# Generated by Django 4.2.13 on 2024-07-03 15:48

from django.db import migrations
from api.staticdata.units.enums import Units


def change_legacy_unit_codes(apps, schema_editor):
    GoodOnApplication = apps.get_model("applications", "GoodOnApplication")

    legacy_unit_codes = ["MIM", "MCM", "MIR", "MCR"]

    for good in GoodOnApplication.objects.filter(unit__in=legacy_unit_codes):
        if good.unit == legacy_unit_codes[0]:
            good.unit = Units.MGM
        elif good.unit == legacy_unit_codes[1]:
            good.unit = Units.MCG
        elif good.unit == legacy_unit_codes[2]:
            good.unit = Units.MLT
        elif good.unit == legacy_unit_codes[3]:
            good.unit = Units.MCL
        good.save()


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0082_alter_goodonapplication_unit"),
    ]

    operations = [migrations.RunPython(change_legacy_unit_codes, migrations.RunPython.noop)]
