# Generated by Django 4.2.11 on 2024-04-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0082_openapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="openapplication",
            name="destination_countries",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="openapplication",
            name="nature_of_products",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="openapplication",
            name="number_of_siels_last_year",
            field=models.CharField(blank=True, default="", max_length=5),
        ),
        migrations.AddField(
            model_name="openapplication",
            name="purely_commercial",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="openapplication",
            name="siels_issued_last_year",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
