# Generated by Django 4.2.13 on 2024-08-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0083_amend_existing_goodonapplication_unit_legacy_codes"),
    ]

    operations = [
        migrations.AddField(
            model_name="standardapplication",
            name="subject_to_itar_controls",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
