# Generated by Django 4.2.11 on 2024-05-20 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("countries", "0006_update_trading_country_code"),
        ("applications", "0083_openapplication_destination_countries_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenDestination",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "destination_permitted",
                    models.TextField(choices=[("allowed", "Allowed"), ("prohibited", "Prohibited")]),
                ),
                (
                    "application",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="applications.openapplication"),
                ),
                ("country", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="countries.country")),
            ],
        ),
        migrations.AddField(
            model_name="openapplication",
            name="open_destinations",
            field=models.ManyToManyField(through="applications.OpenDestination", to="countries.country"),
        ),
    ]
