# Generated by Django 4.2.13 on 2024-05-20 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0084_opendestination_openapplication_open_destinations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opendestination",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="all_open_destinations",
                to="applications.openapplication",
            ),
        ),
    ]
