# Generated by Django 4.2.17 on 2025-02-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0084_standardapplication_subject_to_itar_controls"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="partyonapplication",
            index=models.Index(fields=["created_at"], name="application_created_a502bc_idx"),  # /PS-IGNORE
        ),
    ]
