# Generated by Django 4.2.17 on 2025-02-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0085_partyonapplication_application_created_a502bc_idx_and_more"),  # /PS-IGNORE
    ]

    operations = [
        migrations.AddIndex(
            model_name="goodonapplication",
            index=models.Index(fields=["created_at"], name="application_created_37e2a2_idx"),  # /PS-IGNORE
        ),
    ]
