# Generated by Django 4.2.16 on 2025-01-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0086_f680application_armed_forces_usage_and_more"),  # /PS-IGNORE
    ]

    operations = [
        migrations.AlterField(
            model_name="f680application",  # /PS-IGNORE
            name="exceptional_circumstances",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
