# Generated by Django 4.2.19 on 2025-02-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0086_goodonapplication_application_created_37e2a2_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="goodonapplication",
            index=models.Index(fields=["assessment_date"], name="application_assessm_03b5fc_idx"),
        ),
    ]
