# Generated by Django 2.1.7 on 2019-03-18 16:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.TextField(default=None)),
                ('control_code', models.TextField(blank=True, default=None)),
                ('activity', models.TextField(blank=True, default=None)),
                ('destination', models.TextField(blank=True, default=None)),
                ('usage', models.TextField(blank=True, default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'application',
            },
        ),
    ]
