# Generated by Django 2.2 on 2019-05-21 12:47

import applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('more_information_required', 'More information required'), ('under_review', 'Under review'), ('resubmitted', 'Resubmitted'), ('withdrawn', 'Withdrawn'), ('approved', 'Approved'), ('declined', 'Declined')], default=applications.models.ApplicationStatus('Submitted'), max_length=255),
        ),
    ]
