# Generated by Django 2.2 on 2019-04-18 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='control_code',
        ),
        migrations.RemoveField(
            model_name='good',
            name='control_code',
        ),
    ]
