# Generated by Django 2.1.7 on 2019-04-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='draft',
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.TextField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('More information required', 'More information required'), ('Under review', 'Under review'), ('Resubmitted', 'Resubmitted'), ('Withdrawn', 'Withdrawn')], default='Submitted'),
        ),
    ]
