# Generated by Django 2.2 on 2019-06-19 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
