# Generated by Django 2.2 on 2019-04-24 14:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190418_1537'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodOnApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.FloatField(blank=True, default=None, null=True)),
                ('unit', models.TextField(default=None)),
                ('end_use_case', models.TextField(default=None)),
                ('value', models.DecimalField(decimal_places=2, max_digits=256)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='applications.Application')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_on_application', to='goods.Good')),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, default=None)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='applications.Application')),
            ],
        ),
    ]
