# Generated by Django 2.2.2 on 2019-07-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodonapplication',
            name='unit',
            field=models.CharField(choices=[('GRM', 'Gram(s)'), ('KGM', 'Kilogram(s)'), ('NAR', 'Number of articles'), ('MTK', 'Square metre(s)'), ('MTR', 'Metre(s)'), ('LTR', 'Litre(s)'), ('MTQ', 'Cubic metre(s)')], default='GRM', max_length=50),
        ),
    ]
