# Generated by Django 2.1.7 on 2019-04-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.TextField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('More information required', 'More information required'), ('Under review', 'Under review'), ('Resubmitted', 'Resubmitted'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Withdrawn', 'Withdrawn')], default='Draft'),
        ),
    ]
