# Generated by Django 2.2 on 2019-05-25 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0003_add_sites_no_constraint'),
        ('end_user', '0001_initial'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduseronapplication',
            name='end_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_user_on_application', to='end_user.EndUser'),
        ),
        migrations.AddField(
            model_name='destination',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='applications.Application'),
        ),
        migrations.AddField(
            model_name='application',
            name='organisation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation'),
        ),
    ]
