# Generated by Django 2.1.7 on 2019-04-02 16:05

import applications.libraries.ApplicationStatuses
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.TextField(blank=True, choices=[(applications.libraries.ApplicationStatuses.ApplicationStatuses('Draft'), 'Draft'), (applications.libraries.ApplicationStatuses.ApplicationStatuses('Submitted'), 'Submitted'), (applications.libraries.ApplicationStatuses.ApplicationStatuses('More information required'), 'More information required'), (applications.libraries.ApplicationStatuses.ApplicationStatuses('Under review'), 'Under review'), (applications.libraries.ApplicationStatuses.ApplicationStatuses('Resubmitted'), 'Resubmitted'), (applications.libraries.ApplicationStatuses.ApplicationStatuses('Approved'), 'Approved'), (applications.libraries.ApplicationStatuses.ApplicationStatuses('Declined'), 'Declined'), (applications.libraries.ApplicationStatuses.ApplicationStatuses('Withdrawn'), 'Withdrawn')], default='Draft'),
        ),
    ]
