# Generated by Django 2.2.4 on 2019-09-10 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0002_auto_20190628_1252'),
        ('statuses', '0001_initial'),
        ('organisations', '0001_initial'),
        ('goods', '0001_initial'),
        ('end_user', '0004_delete_euaequery'),
        ('applications', '0001_initial'),
        ('denial_reasons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodonapplication',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_on_application', to='goods.Good'),
        ),
        migrations.AddField(
            model_name='externallocationonapplication',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_application_sites', to='applications.Application'),
        ),
        migrations.AddField(
            model_name='externallocationonapplication',
            name='external_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_locations_on_application', to='organisations.ExternalLocation'),
        ),
        migrations.AddField(
            model_name='countryonapplication',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_countries', to='applications.Application'),
        ),
        migrations.AddField(
            model_name='countryonapplication',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries_on_application', to='countries.Country'),
        ),
        migrations.AddField(
            model_name='applicationdenialreason',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_denial_reason', to='applications.Application'),
        ),
        migrations.AddField(
            model_name='applicationdenialreason',
            name='reasons',
            field=models.ManyToManyField(to='denial_reasons.DenialReason'),
        ),
        migrations.AddField(
            model_name='application',
            name='end_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_end_user', to='end_user.EndUser'),
        ),
        migrations.AddField(
            model_name='application',
            name='organisation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation'),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_status', to='statuses.CaseStatus'),
        ),
        migrations.AddField(
            model_name='application',
            name='ultimate_end_users',
            field=models.ManyToManyField(related_name='application_ultimate_end_users', to='end_user.EndUser'),
        ),
    ]
