# Generated by Django 2.1.2 on 2019-02-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='activity',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='application',
            name='control_code',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2019-02-27 16:56:09.741547'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='destination',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='application',
            name='last_modified_at',
            field=models.DateTimeField(auto_now_add=True, default='2019-02-27 16:56:09.741547'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='usage',
            field=models.TextField(default=''),
        ),
    ]
