# Generated by Django 2.2.2 on 2019-06-21 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_delete_destination'),
        ('applications', '0002_auto_20190614_1332'),
    ]

    operations = [
    ]
