# Generated by Django 2.2.3 on 2019-07-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_user', '0002_enduser_organisation'),
        ('applications', '0002_auto_20190717_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ultimate_end_users',
            field=models.ManyToManyField(related_name='application_ultimate_end_users', to='end_user.EndUser'),
        ),
    ]
