# Generated by Django 2.2.4 on 2019-09-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20190918_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='have_you_been_informed',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
