# Generated by Django 2.2 on 2019-04-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_destination_goodonapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodonapplication',
            name='end_use_case',
        ),
    ]
