# Generated by Django 2.2.2 on 2019-06-23 18:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
        ('applications', '0002_delete_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryOnApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries_on_application', to='countries.Country')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_countries', to='applications.Application')),
            ],
        ),
    ]
