# Generated by Django 2.1.7 on 2019-04-03 09:59

import applications.libraries.ApplicationStatuses
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.TextField(blank=True, choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('MORE_INFORMATION_REQUIRED', 'More information required'), ('UNDER_REVIEW', 'Under review'), ('RESUBMITTED', 'Resubmitted'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('WITHDRAWN', 'Withdrawn')], default=applications.libraries.ApplicationStatuses.ApplicationStatuses('Draft')),
        ),
    ]
