# Generated by Django 2.2.4 on 2019-11-18 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("statuses", "0001_initial"),
        ("countries", "0001_initial"),
        (
            "applications",
            "0002_baseapplication_countryonapplication_externallocationonapplication_goodonapplication_hmrcquery_opena",
        ),
        ("denial_reasons", "0001_initial"),
        ("goods", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodonapplication",
            name="good",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="goods_on_application", to="goods.Good"
            ),
        ),
        migrations.AddField(
            model_name="externallocationonapplication",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="external_application_sites",
                to="applications.BaseApplication",
            ),
        ),
        migrations.AddField(
            model_name="externallocationonapplication",
            name="external_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="external_locations_on_application",
                to="organisations.ExternalLocation",
            ),
        ),
        migrations.AddField(
            model_name="countryonapplication",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="countries_on_application",
                to="countries.Country",
            ),
        ),
        migrations.AddField(
            model_name="baseapplication",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application_status",
                to="statuses.CaseStatus",
            ),
        ),
        migrations.AddField(
            model_name="applicationdocument",
            name="application",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="applications.BaseApplication"),
        ),
        migrations.AddField(
            model_name="applicationdenialreason",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application_denial_reason",
                to="applications.BaseApplication",
            ),
        ),
        migrations.AddField(
            model_name="applicationdenialreason",
            name="reasons",
            field=models.ManyToManyField(to="denial_reasons.DenialReason"),
        ),
    ]
