# Generated by Django 2.2.4 on 2019-10-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_applicationdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseapplication',
            name='licence_type',
            field=models.CharField(choices=[('standard_licence', 'Standard licence'), ('open_licence', 'Open licence'), ('hmrc_query', 'HMRC query')], default=None, max_length=50),
        ),
        migrations.RenameField(
            model_name='baseapplication',
            old_name='licence_type',
            new_name='application_type',
        ),
    ]
