# Generated by Django 2.2.9 on 2020-01-24 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("parties", "0001_initial"),
        (
            "applications",
            "0002_baseapplication_countryonapplication_externallocationonapplication_goodonapplication_hmrcquery_opena",
        ),
        ("goods", "0001_initial"),
        ("organisations", "0001_initial"),
        ("denial_reasons", "0001_initial"),
        ("countries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteonapplication",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sites_on_application",
                to="organisations.Site",
            ),
        ),
        migrations.AddField(
            model_name="goodonapplication",
            name="good",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="goods_on_application", to="goods.Good"
            ),
        ),
        migrations.AddField(
            model_name="externallocationonapplication",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="external_application_sites",
                to="applications.BaseApplication",
            ),
        ),
        migrations.AddField(
            model_name="externallocationonapplication",
            name="external_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="external_locations_on_application",
                to="organisations.ExternalLocation",
            ),
        ),
        migrations.AddField(
            model_name="countryonapplication",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="countries_on_application",
                to="countries.Country",
            ),
        ),
        migrations.AddField(
            model_name="applicationdocument",
            name="application",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="applications.BaseApplication"),
        ),
        migrations.AddField(
            model_name="applicationdenialreason",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application_denial_reason",
                to="applications.BaseApplication",
            ),
        ),
        migrations.AddField(
            model_name="applicationdenialreason",
            name="reasons",
            field=models.ManyToManyField(to="denial_reasons.DenialReason"),
        ),
        migrations.AddField(
            model_name="standardapplication",
            name="consignee",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application_consignee",
                to="parties.Party",
            ),
        ),
        migrations.AddField(
            model_name="standardapplication",
            name="end_user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application_end_user",
                to="parties.Party",
            ),
        ),
        migrations.AddField(
            model_name="standardapplication",
            name="third_parties",
            field=models.ManyToManyField(related_name="application_third_parties", to="parties.Party"),
        ),
        migrations.AddField(
            model_name="standardapplication",
            name="ultimate_end_users",
            field=models.ManyToManyField(related_name="application_ultimate_end_users", to="parties.Party"),
        ),
        migrations.AddField(
            model_name="hmrcquery",
            name="consignee",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hmrc_query_consignee",
                to="parties.Party",
            ),
        ),
        migrations.AddField(
            model_name="hmrcquery",
            name="end_user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hmrc_query_end_user",
                to="parties.Party",
            ),
        ),
        migrations.AddField(
            model_name="hmrcquery",
            name="hmrc_organisation",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.PROTECT, to="organisations.Organisation"
            ),
        ),
        migrations.AddField(
            model_name="hmrcquery",
            name="third_parties",
            field=models.ManyToManyField(related_name="hmrc_query_third_parties", to="parties.Party"),
        ),
        migrations.AddField(
            model_name="hmrcquery",
            name="ultimate_end_users",
            field=models.ManyToManyField(related_name="hmrc_query_ultimate_end_users", to="parties.Party"),
        ),
        migrations.AddField(
            model_name="goodonapplication",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="goods", to="applications.StandardApplication"
            ),
        ),
        migrations.AddField(
            model_name="countryonapplication",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application_countries",
                to="applications.OpenApplication",
            ),
        ),
    ]
