# Generated by Django 2.2.3 on 2019-07-30 18:40

from django.db import migrations, models
import django.db.models.deletion
from static.statuses.enums import CaseStatusEnum


def migrate_statuses(apps, schema_editor):
    CaseStatus = apps.get_model('statuses', 'CaseStatus')
    Application = apps.get_model('applications', 'Application')

    for application in Application.objects.all():
        application.status = CaseStatus.objects.filter(id=application.status)
        application.save()


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20190717_0851'),
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.ForeignKey(blank=True, default=CaseStatusEnum.SUBMITTED, null=True,
                                    on_delete=django.db.models.deletion.CASCADE, related_name='application_status', to='statuses.CaseStatus'),
        ),
        migrations.RunPython(migrate_statuses),
    ]
