# Generated by Django 2.1.7 on 2019-04-15 10:41

import applications.models
from django.db import migrations, models
import enumchoicefield.fields


class Migration(migrations.Migration):

    replaces = [('applications', '0003_auto_20190404_1452'), ('applications', '0004_auto_20190410_1019'), ('applications', '0005_auto_20190412_1042'), ('applications', '0006_auto_20190412_1418')]

    dependencies = [
        ('applications', '0002_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.TextField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('More information required', 'More information required'), ('Under review', 'Under review'), ('Resubmitted', 'Resubmitted'), ('Withdrawn', 'Withdrawn')], default='Draft'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=enumchoicefield.fields.EnumChoiceField(default=applications.models.ApplicationStatuses(1), enum_class=applications.models.ApplicationStatuses, max_length=25),
        ),
        migrations.RemoveField(
            model_name='application',
            name='draft',
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=enumchoicefield.fields.EnumChoiceField(default=applications.models.ApplicationStatuses(2), enum_class=applications.models.ApplicationStatuses, max_length=25),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=enumchoicefield.fields.EnumChoiceField(default=applications.models.ApplicationStatuses(1), enum_class=applications.models.ApplicationStatuses, max_length=25),
        ),
    ]
