# Generated by Django 2.2.4 on 2019-10-05 13:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_applicationdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseapplication',
            name='application_copied_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='applications.BaseApplication'),
        ),
        migrations.AlterField(
            model_name='baseapplication',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='baseapplication',
            name='last_modified_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
