# Generated by Django 2.2.4 on 2019-09-20 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('applications', '0002_auto_20190918_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.Document')),
                ('description', models.TextField(blank=True, default=None, max_length=280, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.Application')),
            ],
            bases=('documents.document',),
        ),
        migrations.RemoveField(
            model_name='applicationdocument',
            name='application',
        ),
        migrations.AddField(
            model_name='application',
            name='additional_documents',
            field=models.ManyToManyField(related_name='additional_documents', to='applications.ApplicationDocument'),
        ),
    ]
