# Generated by Django 2.1.7 on 2019-03-17 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20190317_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='application_id',
            new_name='application',
        ),
        migrations.RenameField(
            model_name='good',
            old_name='application_id',
            new_name='application',
        ),
    ]
