# Generated by Django 2.2.2 on 2019-06-24 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_countryonapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countryonapplication',
            old_name='draft',
            new_name='application',
        ),
    ]
