# Generated by Django 2.2.9 on 2020-02-11 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_auto_20200210_1326"),
    ]

    operations = [
        migrations.CreateModel(
            name="F680ClearanceApplication",
            fields=[
                (
                    "baseapplication_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="applications.BaseApplication",
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("applications.baseapplication",),
        ),
        migrations.CreateModel(
            name="GiftingClearanceApplication",
            fields=[
                (
                    "baseapplication_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="applications.BaseApplication",
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("applications.baseapplication",),
        ),
        migrations.AlterField(
            model_name="baseapplication",
            name="application_type",
            field=models.CharField(
                choices=[
                    ("standard_licence", "Standard Licence"),
                    ("open_licence", "Open Licence"),
                    ("hmrc_query", "HMRC Query"),
                    ("exhibition_clearance", "MOD Exhibition Clearance"),
                    ("gifting_clearance", "Gifting Clearance"),
                    ("F680_clearance", "F680 Clearance"),
                ],
                default=None,
                max_length=50,
            ),
        ),
    ]
