# Generated by Django 2.2.9 on 2020-01-28 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20200127_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hmrcquery',
            name='consignee',
        ),
        migrations.RemoveField(
            model_name='hmrcquery',
            name='end_user',
        ),
        migrations.RemoveField(
            model_name='hmrcquery',
            name='third_parties',
        ),
        migrations.RemoveField(
            model_name='hmrcquery',
            name='ultimate_end_users',
        ),
        migrations.RemoveField(
            model_name='standardapplication',
            name='consignee',
        ),
        migrations.RemoveField(
            model_name='standardapplication',
            name='end_user',
        ),
        migrations.RemoveField(
            model_name='standardapplication',
            name='third_parties',
        ),
        migrations.RemoveField(
            model_name='standardapplication',
            name='ultimate_end_users',
        ),
    ]
