# Generated by Django 2.2.4 on 2019-09-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_applicationdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationdocument',
            name='application',
        ),
        migrations.AddField(
            model_name='application',
            name='additional_documents',
            field=models.ManyToManyField(related_name='additional_documents', to='applications.ApplicationDocument'),
        ),
    ]
