# Generated by Django 2.1.7 on 2019-03-17 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20190317_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='application',
            name='control_code',
        ),
        migrations.RemoveField(
            model_name='application',
            name='usage',
        ),
        migrations.AddField(
            model_name='application',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='title',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='good',
            name='control_code',
            field=models.TextField(blank=True, default=None),
        ),
    ]
