# Generated by Django 2.2.4 on 2019-10-30 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0007_organisation_flags"),
        ("applications", "0003_auto_20191030_1106"),
    ]

    operations = [
        migrations.AddField(
            model_name="hmrcquery",
            name="hmrc_organisation",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.PROTECT, to="organisations.Organisation",
            ),
        ),
    ]
