# Generated by Django 2.2.8 on 2020-02-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20200210_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardapplication',
            name='reference_number_on_information_form',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
