# Generated by Django 2.2.4 on 2019-11-18 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "0003_auto_20191118_1511"),
        ("organisations", "0001_initial"),
        ("parties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="standardapplication",
            name="consignee",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application_consignee",
                to="parties.Consignee",
            ),
        ),
        migrations.AddField(
            model_name="standardapplication",
            name="end_user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application_end_user",
                to="parties.EndUser",
            ),
        ),
        migrations.AddField(
            model_name="standardapplication",
            name="third_parties",
            field=models.ManyToManyField(related_name="application_third_parties", to="parties.ThirdParty"),
        ),
        migrations.AddField(
            model_name="standardapplication",
            name="ultimate_end_users",
            field=models.ManyToManyField(related_name="application_ultimate_end_users", to="parties.UltimateEndUser"),
        ),
        migrations.AddField(
            model_name="hmrcquery",
            name="consignee",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hmrc_query_consignee",
                to="parties.Consignee",
            ),
        ),
        migrations.AddField(
            model_name="hmrcquery",
            name="end_user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hmrc_query_end_user",
                to="parties.EndUser",
            ),
        ),
        migrations.AddField(
            model_name="hmrcquery",
            name="hmrc_organisation",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.PROTECT, to="organisations.Organisation"
            ),
        ),
        migrations.AddField(
            model_name="hmrcquery",
            name="third_parties",
            field=models.ManyToManyField(related_name="hmrc_query_third_parties", to="parties.ThirdParty"),
        ),
        migrations.AddField(
            model_name="hmrcquery",
            name="ultimate_end_users",
            field=models.ManyToManyField(related_name="hmrc_query_ultimate_end_users", to="parties.UltimateEndUser"),
        ),
        migrations.AddField(
            model_name="goodonapplication",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="goods", to="applications.StandardApplication"
            ),
        ),
        migrations.AddField(
            model_name="countryonapplication",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application_countries",
                to="applications.OpenApplication",
            ),
        ),
    ]
