# Generated by Django 2.2 on 2019-04-18 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_reversioning_and_audit'),
        ('applications', '0002_auto_20190411_1312'),
    ]

    operations = [
    ]
