# Generated by Django 2.2.2 on 2019-06-26 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_merge_20190621_0952'),
        ('applications', '0004_auto_20190624_1515'),
    ]

    operations = [
    ]
