# Generated by Django 2.2.8 on 2020-01-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_goodonapplication_is_good_incorporated'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseapplication',
            name='licence_duration',
            field=models.IntegerField(default=None, help_text='Set when application finalised', null=True),
        ),
    ]
