# Generated by Django 2.1.7 on 2019-03-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_auto_20190317_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='good',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
