# Generated by Django 2.2.4 on 2019-11-26 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_auto_20191118_1511"),
    ]

    operations = [
        migrations.RemoveField(model_name="baseapplication", name="created_at",),
        migrations.RemoveField(model_name="baseapplication", name="last_modified_at",),
    ]
