# Generated by Django 2.2.10 on 2020-02-14 09:52

from django.db import migrations
import separatedvaluesfield.models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_f680_gifting"),
    ]

    operations = [
        migrations.AddField(
            model_name="standardapplication",
            name="goods_categories",
            field=separatedvaluesfield.models.SeparatedValuesField(
                blank=True,
                choices=[
                    ("anti_piracy", "Anti-piracy"),
                    ("maritime_anti_piracy", "Maritime anti-piracy"),
                    ("firearms", "Firearms"),
                    ("incorporated_goods", "Incorporated goods"),
                ],
                default=None,
                max_length=150,
                null=True,
            ),
        ),
    ]
