# Generated by Django 2.2.10 on 2020-02-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_standardapplication_goods_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standardapplication",
            name="reference_number_on_information_form",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
