# Generated by Django 2.2.4 on 2019-09-24 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('applications', '0004_auto_20190920_1535'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplicationDocuments',
            new_name='ApplicationDocument',
        ),
    ]
