# Generated by Django 2.2.9 on 2020-01-29 14:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0003_remove_party_application'),
        ('applications', '0004_auto_20200128_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyOnApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created_at')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='updated_at')),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applications.BaseApplication')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parties.Party')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
