# Generated by Django 2.1.7 on 2019-04-12 10:42

import applications.models
from django.db import migrations
import enumchoicefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_auto_20190410_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='draft',
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=enumchoicefield.fields.EnumChoiceField(default=applications.models.ApplicationStatuses(2), enum_class=applications.models.ApplicationStatuses, max_length=25),
        ),
    ]
