# Generated by Django 2.2 on 2019-05-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_auto_20190503_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='export_type',
            field=models.CharField(choices=[('permanent', 'Permanent'), ('temporary', 'Temporary')], default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='licence_type',
            field=models.CharField(choices=[('standard_licence', 'Standard Individual Export Licence (SIEL)'), ('open_licence', 'Open Individual Export Licence (OIEL)')], default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='reference_number_on_information_form',
            field=models.TextField(blank=True, null=True),
        ),
    ]
