# Generated by Django 2.2 on 2019-05-16 11:56

import applications.models
from django.db import migrations, models
import enumchoicefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_auto_20190503_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='export_type',
            field=enumchoicefield.fields.EnumChoiceField(blank=True, enum_class=applications.models.ExportType, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='license_type',
            field=enumchoicefield.fields.EnumChoiceField(default=applications.models.LicenseType(3), enum_class=applications.models.LicenseType, max_length=9),
        ),
        migrations.AddField(
            model_name='application',
            name='reference_number_on_information_form',
            field=models.TextField(blank=True, null=True),
        ),
    ]
