# Generated by Django 2.1.7 on 2019-04-12 14:18

import applications.models
from django.db import migrations
import enumchoicefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_auto_20190412_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=enumchoicefield.fields.EnumChoiceField(default=applications.models.ApplicationStatuses(1), enum_class=applications.models.ApplicationStatuses, max_length=25),
        ),
    ]
