# Generated by Django 2.1.7 on 2019-03-17 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_auto_20190317_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='applications.Application'),
        ),
    ]
