# Generated by Django 2.2.8 on 2020-01-15 00:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_baseapplication_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseapplication',
            name='duration',
            field=models.IntegerField(default=None, help_text='Set when application finalised', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)]),
        ),
    ]
