# Generated by Django 2.2.9 on 2020-01-31 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_partyonapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyonapplication',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', related_query_name='party', to='applications.BaseApplication'),
        ),
    ]
