# Generated by Django 2.2 on 2019-05-15 10:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_add_sites_no_constraint'),
        ('applications', '0005_auto_20190503_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitesOnApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_sites', to='applications.Application')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites_on_application', to='organisations.Site')),
            ],
        ),
    ]
