# Generated by Django 2.2.8 on 2020-01-22 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_auto_20200121_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hmrcquery',
            name='consignee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hmrc_query_consignee', to='parties.Party'),
        ),
        migrations.AlterField(
            model_name='standardapplication',
            name='consignee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_consignee', to='parties.Party'),
        ),
    ]
