# Generated by Django 2.2.10 on 2020-02-21 15:47

from django.db import migrations, models
import separatedvaluesfield.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0006_auto_20200217_1634"),
    ]

    operations = [
        migrations.CreateModel(
            name="F680ClearanceType",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "name",
                    separatedvaluesfield.models.SeparatedValuesField(
                        choices=[
                            ("market_survey", "Market Survey"),
                            ("initial_discussions_and_promotions", "Initial discussions and promotions"),
                            ("demonstration_uk_overseas_customers", "Demonstration in the UK to overseas customers"),
                            ("demonstration_overseas", "Demonstration overseas"),
                            ("training", "Training"),
                            ("through_life_support", "Through life support"),
                        ],
                        max_length=35,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="f680clearanceapplication",
            name="f680_clearance_types",
            field=models.ManyToManyField(
                related_name="f680_clearance_type_application", to="applications.F680ClearanceType"
            ),
        ),
    ]
