# Generated by Django 2.2.10 on 2020-02-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("f680_clearance_types", "0001_initial"),
        ("applications", "0006_auto_20200217_1634"),
    ]

    operations = [
        migrations.AddField(
            model_name="f680clearanceapplication",
            name="f680_clearance_types",
            field=models.ManyToManyField(
                related_name="f680_clearance_type_application", to="f680_clearance_types.F680ClearanceType"
            ),
        ),
    ]
