# Generated by Django 2.2.9 on 2020-01-24 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0005_base_party_sub_type"),
        ("applications", "0006_auto_20200121_1411"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseapplication",
            name="application_type",
            field=models.CharField(
                choices=[
                    ("standard_licence", "Standard Licence"),
                    ("open_licence", "Open Licence"),
                    ("hmrc_query", "HMRC Query"),
                    ("exhibition_clearance", "MOD Exhibition Clearance"),
                ],
                default=None,
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="ExhibitionClearanceApplication",
            fields=[
                (
                    "baseapplication_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="applications.BaseApplication",
                    ),
                ),
                (
                    "consignee",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clearance_consignee",
                        to="parties.Consignee",
                    ),
                ),
                (
                    "end_user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clearance_end_user",
                        to="parties.EndUser",
                    ),
                ),
                (
                    "third_parties",
                    models.ManyToManyField(related_name="clearance_third_parties", to="parties.ThirdParty"),
                ),
                (
                    "ultimate_end_users",
                    models.ManyToManyField(related_name="clearance_ultimate_end_users", to="parties.UltimateEndUser"),
                ),
            ],
            options={"abstract": False,},
            bases=("applications.baseapplication",),
        ),
    ]
