# Generated by Django 2.2 on 2019-05-21 09:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('end_user', '0003_auto_20190521_0919'),
        ('applications', '0006_auto_20190517_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndUserOnApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_end_users', to='applications.Application')),
                ('end_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_user_on_application', to='end_user.EndUser')),
            ],
        ),
    ]
