# Generated by Django 2.2.10 on 2020-02-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0007_auto_20200219_1150"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodonapplication",
            name="other_item_type",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="goodonapplication",
            name="item_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("equipment", "Equipment"),
                    ("model", "Model"),
                    ("datasheet", "Datasheet"),
                    ("Brochure", "Brochure"),
                    ("Video", "Video"),
                    ("Other", "Other"),
                ],
                default=None,
                max_length=10,
                null=True,
            ),
        ),
    ]
