# Generated by Django 2.2.8 on 2020-01-22 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_auto_20200122_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hmrcquery',
            name='end_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hmrc_query_end_user', to='parties.Party'),
        ),
        migrations.AlterField(
            model_name='standardapplication',
            name='end_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_end_user', to='parties.Party'),
        ),
    ]
