# Generated by Django 2.2.10 on 2020-02-27 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0008_auto_20200226_1218"),
        ("applications", "0007_f680clearanceapplication_f680_clearance_types"),
    ]

    operations = []
