# Generated by Django 2.2.10 on 2020-03-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("f680_clearance_types", "0001_initial"),
        ("applications", "0008_auto_20200226_1218"),
    ]

    operations = [
        migrations.AddField(
            model_name="f680clearanceapplication",
            name="types",
            field=models.ManyToManyField(
                related_name="f680_clearance_application", to="f680_clearance_types.F680ClearanceType"
            ),
        ),
    ]
