# Generated by Django 2.2.10 on 2020-02-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0008_auto_20200219_1251"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodonapplication",
            name="item_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("equipment", "Equipment"),
                    ("model", "Model"),
                    ("datasheet", "Datasheet"),
                    ("brochure", "Brochure"),
                    ("video", "Video"),
                    ("other", "Other"),
                ],
                default=None,
                max_length=10,
                null=True,
            ),
        ),
    ]
