# Generated by Django 2.2.10 on 2020-02-20 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_auto_20200220_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exhibitionclearanceapplication',
            old_name='exhibition_title',
            new_name='title',
        ),
    ]
