# Generated by Django 2.2.10 on 2020-03-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_f680clearanceapplication_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseapplication',
            name='informed_wmd_ref',
            field=models.TextField(blank=True, default=None, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='baseapplication',
            name='is_eu_military',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('not_applicable', 'Not applicable')], default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='baseapplication',
            name='is_informed_wmd',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='baseapplication',
            name='is_military_end_use_controls',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='baseapplication',
            name='is_suspected_wmd',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='baseapplication',
            name='military_end_use_controls_ref',
            field=models.TextField(blank=True, default=None, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='baseapplication',
            name='suspected_wmd_ref',
            field=models.TextField(blank=True, default=None, max_length=2000, null=True),
        ),
    ]
