# Generated by Django 2.2.10 on 2020-03-05 13:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0009_f680clearanceapplication_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="Licence",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created_at"
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="updated_at"
                    ),
                ),
                ("start_date", models.DateField()),
                ("licence_duration", models.PositiveSmallIntegerField()),
                ("finalised", models.BooleanField(default=False)),
            ],
            options={"abstract": False,},
        ),
        migrations.RemoveField(model_name="baseapplication", name="licence_duration",),
        migrations.AddField(
            model_name="baseapplication",
            name="licence",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="applications.Licence"),
        ),
    ]
