# Generated by Django 2.2.8 on 2020-01-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0009_baseapplication_good_on_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="hmrcquery", name="have_goods_departed", field=models.BooleanField(default=False),
        ),
    ]
