# Generated by Django 2.2.10 on 2020-02-10 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0010_hmrcquery_is_goods_departed"),
    ]

    operations = [
        migrations.RemoveField(model_name="baseapplication", name="application_type",),
    ]
