# Generated by Django 2.2.10 on 2020-03-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0010_auto_20200304_1344"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseapplication",
            name="compliant_limitations_eu_ref",
            field=models.TextField(blank=True, default=None, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="baseapplication",
            name="informed_wmd_ref",
            field=models.TextField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="baseapplication",
            name="is_compliant_limitations_eu",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="baseapplication",
            name="is_eu_military",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="baseapplication",
            name="is_informed_wmd",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="baseapplication",
            name="is_military_end_use_controls",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="baseapplication",
            name="is_suspected_wmd",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="baseapplication",
            name="military_end_use_controls_ref",
            field=models.TextField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="baseapplication",
            name="suspected_wmd_ref",
            field=models.TextField(blank=True, default=None, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="baseapplication",
            name="clearance_level",
            field=models.CharField(
                choices=[
                    ("uk_unclassified", "UK UNCLASSIFIED"),
                    ("uk_official", "UK OFFICIAL"),
                    ("uk_official_sensitive", "UK OFFICIAL - SENSITIVE"),
                    ("uk_secret", "UK SECRET"),
                    ("uk_top_secret", "UK TOP SECRET"),
                    ("nato_unclassified", "NATO UNCLASSIFIED"),
                    ("nato_confidential", "NATO CONFIDENTIAL"),
                    ("nato_restricted", "NATO RESTRICTED"),
                    ("nato_secret", "NATO SECRET"),
                    ("occar_unclassified", "OCCAR UNCLASSIFIED"),
                    ("occar_confidential", "OCCAR CONFIDENTIAL"),
                    ("occar_restricted", "OCCAR RESTRICTED"),
                    ("occar_secret", "OCCAR SECRET"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
