# Generated by Django 2.2.10 on 2020-02-20 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_auto_20200220_1600'),
        ('applications', '0010_auto_20200220_1602'),
    ]

    operations = [
    ]
