# Generated by Django 2.2.10 on 2020-03-09 10:15

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_merge_20200306_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='f680clearanceapplication',
            name='questions',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
