# Generated by Django 2.2.11 on 2020-03-16 09:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0013_auto_20200311_1124"),
    ]

    operations = [
        migrations.RemoveField(model_name="baseapplication", name="licence_duration",),
        migrations.AddField(
            model_name="baseapplication",
            name="compliant_limitations_eu_ref",
            field=models.TextField(blank=True, default=None, max_length=2200, null=True),
        ),
        migrations.AddField(
            model_name="baseapplication",
            name="informed_wmd_ref",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="baseapplication",
            name="is_compliant_limitations_eu",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="baseapplication",
            name="is_eu_military",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="baseapplication",
            name="is_informed_wmd",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="baseapplication",
            name="is_military_end_use_controls",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="baseapplication",
            name="is_suspected_wmd",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="baseapplication",
            name="military_end_use_controls_ref",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="baseapplication",
            name="suspected_wmd_ref",
            field=models.TextField(blank=True, default=None, max_length=2200, null=True),
        ),
        migrations.CreateModel(
            name="Licence",
            fields=[
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created_at"
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="updated_at"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("start_date", models.DateField()),
                ("duration", models.PositiveSmallIntegerField()),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licence",
                        to="applications.BaseApplication",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
