# Generated by Django 2.2.11 on 2020-03-16 13:51

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_baseapplication_wmd_end_use_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='f680clearanceapplication',
            name='questions',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
