# Generated by Django 2.2.11 on 2020-03-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_licence'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseapplication',
            name='is_agreed_to_foi',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
