# Generated by Django 2.2.11 on 2020-03-20 07:49

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0015_licence"),
    ]

    operations = [
        migrations.AddField(
            model_name="f680clearanceapplication", name="questions", field=jsonfield.fields.JSONField(null=True),
        ),
    ]
