# Generated by Django 2.2.11 on 2020-03-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0016_baseapplication_intended_end_use"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseapplication",
            name="compliant_limitations_eu_ref",
            field=models.CharField(blank=True, default=None, max_length=2200, null=True),
        ),
        migrations.AlterField(
            model_name="baseapplication",
            name="intended_end_use",
            field=models.CharField(blank=True, default=None, max_length=2200, null=True),
        ),
        migrations.AlterField(
            model_name="baseapplication",
            name="suspected_wmd_ref",
            field=models.CharField(blank=True, default=None, max_length=2200, null=True),
        ),
    ]
