# Generated by Django 2.2.11 on 2020-03-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_auto_20200320_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseapplication',
            name='is_shipped_waybill_or_lading',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='baseapplication',
            name='non_waybill_or_lading_route_details',
            field=models.TextField(blank=True, default=None, max_length=2000, null=True),
        ),
    ]
