# Generated by Django 2.2.11 on 2020-03-20 15:31

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0017_auto_20200320_1109"),
    ]

    operations = [
        migrations.AddField(
            model_name="f680clearanceapplication", name="questions", field=jsonfield.fields.JSONField(null=True),
        ),
    ]
