# Generated by Django 2.2.11 on 2020-03-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0018_auto_20200324_0952"),
    ]

    operations = [
        migrations.AlterField(model_name="baseapplication", name="name", field=models.TextField(default=None),),
    ]
