# Generated by Django 2.2.11 on 2020-03-25 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0018_auto_20200324_0952"),
        ("applications", "0018_merge_20200320_1647"),
    ]

    operations = []
