# Generated by Django 2.2.11 on 2020-03-26 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0019_merge_20200325_1458'),
        ('applications', '0019_auto_20200325_1145'),
    ]

    operations = [
    ]
