# Generated by Django 2.2.11 on 2020-03-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0019_auto_20200325_1145"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseapplication", name="name", field=models.TextField(default=None, null=True),
        ),
    ]
