# Generated by Django 2.2.11 on 2020-03-31 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0021_baseapplication_agreed_to_foi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Licence',
        ),
    ]
