# Generated by Django 2.2.11 on 2020-04-01 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0022_auto_20200331_1107"),
    ]

    operations = [
        migrations.DeleteModel(name="Licence",),
    ]
