# Generated by Django 2.2.11 on 2020-04-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0024_auto_20200401_1542"),
    ]

    operations = [
        migrations.AddField(
            model_name="openapplication",
            name="tc_activity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("transfer_of_goods", "Transfer of goods"),
                    ("provision_of_transportation", "Transportation services"),
                    ("provision_of_finance", "Finance or financial services"),
                    ("provision_of_insurance", "Insurance or reinsurance"),
                    ("provision_of_advertising", "General advertising or promotion services"),
                ],
                default=None,
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="openapplication",
            name="tc_activity_other",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="openapplication",
            name="tc_product_category",
            field=models.CharField(
                blank=True,
                choices=[("category_a", "Category A"), ("category_b", "Category B"), ("category_c", "Category C")],
                default=None,
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="standardapplication",
            name="tc_activity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("transfer_of_goods", "Transfer of goods"),
                    ("provision_of_transportation", "Transportation services"),
                    ("provision_of_finance", "Finance or financial services"),
                    ("provision_of_insurance", "Insurance or reinsurance"),
                    ("provision_of_advertising", "General advertising or promotion services"),
                ],
                default=None,
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="standardapplication",
            name="tc_activity_other",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="standardapplication",
            name="tc_product_category",
            field=models.CharField(
                blank=True,
                choices=[("category_a", "Category A"), ("category_b", "Category B"), ("category_c", "Category C")],
                default=None,
                max_length=50,
                null=True,
            ),
        ),
    ]
