# Generated by Django 2.2.11 on 2020-04-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0025_auto_20200414_1617"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodonapplication", name="usage", field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
