# Generated by Django 2.2.11 on 2020-04-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0025_auto_20200414_1617"),
    ]

    operations = [
        migrations.AddField(
            model_name="openapplication",
            name="tc_activity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("transfer_of_goods", "Transfer of goods"),
                    ("provision_of_transportation", "Transportation services"),
                    ("provision_of_finance", "Finance or financial services"),
                    ("provision_of_insurance", "Insurance or reinsurance"),
                    ("provision_of_advertising", "General advertising or promotion services"),
                    ("maritime_anti_piracy", "Maritime anti-piracy"),
                    ("other", "Other"),
                ],
                default=None,
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="openapplication",
            name="tc_activity_other",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="openapplication",
            name="tc_product_category",
            field=models.CharField(
                blank=True,
                choices=[("category_a", "Category A"), ("category_b", "Category B"), ("category_c", "Category C")],
                default=None,
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="standardapplication",
            name="tc_activity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("transfer_of_goods", "Transfer of goods"),
                    ("provision_of_transportation", "Transportation services"),
                    ("provision_of_finance", "Finance or financial services"),
                    ("provision_of_insurance", "Insurance or reinsurance"),
                    ("provision_of_advertising", "General advertising or promotion services"),
                    ("maritime_anti_piracy", "Maritime anti-piracy"),
                    ("other", "Other"),
                ],
                default=None,
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="standardapplication",
            name="tc_activity_other",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="standardapplication",
            name="tc_product_category",
            field=models.CharField(
                blank=True,
                choices=[("category_a", "Category A"), ("category_b", "Category B"), ("category_c", "Category C")],
                default=None,
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="standardapplication",
            name="have_you_been_informed",
            field=models.CharField(
                blank=True, choices=[("yes", "Yes"), ("no", "No")], default=None, max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="standardapplication",
            name="reference_number_on_information_form",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
