# Generated by Django 2.2.11 on 2020-04-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0026_auto_20200417_1011"),
    ]

    operations = [
        migrations.AlterField(model_name="goodonapplication", name="usage", field=models.FloatField(default=0),),
    ]
