# Generated by Django 2.2.11 on 2020-04-20 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0027_auto_20200417_1417"),
    ]

    operations = [
        migrations.RenameField(model_name="goodonapplication", old_name="quantity", new_name="applied_for_quantity",),
    ]
