# Generated by Django 2.2.11 on 2020-04-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0027_auto_20200417_1417"),
    ]

    operations = [
        migrations.AddField(
            model_name="openapplication",
            name="goodstype_category",
            field=models.CharField(
                choices=[
                    ("military", "Military or dual use"),
                    ("cryptographic", "Cryptographic"),
                    ("media", "Media"),
                    ("uk_continental_shelf", "UK continental shelf"),
                    ("dealer", "Dealer"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
