# Generated by Django 2.2.11 on 2020-05-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0027_auto_20200417_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardapplication',
            name='contains_firearm_goods',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
