# Generated by Django 2.2.11 on 2020-05-12 08:33

from django.db import migrations, models
import separatedvaluesfield.models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0028_openapplication_goodstype_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="countryonapplication",
            name="contract_types",
            field=separatedvaluesfield.models.SeparatedValuesField(
                blank=True,
                choices=[
                    ("nuclear_related", "Nuclear-related (trigger list items)"),
                    ("navy", "Navy"),
                    ("army", "Army"),
                    ("air_force", "Air force"),
                    ("police", "Police"),
                    ("ministry_of_interior", "Ministry of Interior (or equivalent)"),
                    ("other_security_forces", "Other security forces"),
                    ("companies_nuclear_related", "Companies requesting Nuclear Trigger List items"),
                    ("maritime_anti_piracy", "Maritime anti piracy"),
                    ("aircraft_manufacturers", "Aircraft manufacturers, maintainers or operators"),
                    ("registered_firearm_dealers", "Registered firearm dealers"),
                    ("oil_and_gas_industry", "Oil and gas industry"),
                    ("pharmaceutical_or_medical", "Pharmaceutical or medical"),
                    ("media", "Media"),
                    ("private_military", "Private military or security companies (including security transportation)"),
                    ("education", "Education (e.g. schools, colleges and universities)"),
                    ("for_the_exporters_own_use", "For the exporters own use"),
                    ("other_contract_type", "Other contract type"),
                ],
                default=None,
                max_length=250,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="countryonapplication",
            name="other_contract_type_text",
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
