# Generated by Django 2.2.11 on 2020-05-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0028_openapplication_goodstype_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="standardapplication",
            name="contains_firearm_goods",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
