# Generated by Django 2.2.11 on 2020-05-01 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0029_convert_goods_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardapplication',
            name='goods_categories',
        ),
    ]
