# Generated by Django 2.2.11 on 2020-05-04 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0030_convert_goods_categories"),
    ]

    operations = [
        migrations.RemoveField(model_name="standardapplication", name="goods_categories",),
    ]
