# Generated by Django 2.2.13 on 2020-06-12 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0031_auto_20200525_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodonapplication',
            name='licenced_quantity',
        ),
        migrations.RemoveField(
            model_name='goodonapplication',
            name='licenced_value',
        ),
        migrations.RemoveField(
            model_name='goodonapplication',
            name='usage',
        ),
    ]
