# Generated by Django 2.2.13 on 2020-06-12 13:38

from django.db import migrations, models


def reduce_decimal_places(apps, schema_editor):
    GoodOnApplication = apps.get_model("applications", "GoodOnApplication")
    for goodOnApp in GoodOnApplication.objects.all():
        if len(str(goodOnApp.value)) > 15:
            goodOnApp.value = 0
        if len(str(goodOnApp.licenced_value)) > 15:
            goodOnApp.licenced_value = 0
        goodOnApp.save()


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0031_auto_20200525_1120"),
    ]

    operations = [
        migrations.RunPython(reduce_decimal_places),
    ]
