# Generated by Django 2.2.13 on 2020-06-22 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0033_auto_20200612_1342"),
    ]

    operations = [
        migrations.RemoveField(model_name="goodonapplication", name="licenced_quantity",),
        migrations.RemoveField(model_name="goodonapplication", name="licenced_value",),
        migrations.RemoveField(model_name="goodonapplication", name="usage",),
    ]
