# Generated by Django 2.2.13 on 2020-07-06 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0033_auto_20200612_1342"),
    ]

    operations = [
        migrations.RemoveField(model_name="standardapplication", name="contains_firearm_goods",),
    ]
