# Generated by Django 2.1.7 on 2019-04-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.TextField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('More information required', 'More information required'), ('Under review', 'Under review'), ('Resubmitted', 'Resubmitted'), ('Withdrawn', 'Withdrawn')], default='Draft'),
        ),
    ]
