# Generated by Django 2.2.17 on 2021-01-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("countries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="report_name",
            field=models.TextField(default="", help_text="Name to use in reports, to harmonize with SPIRE"),
        ),
    ]
