# Generated by Django 3.2.21 on 2023-10-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("countries", "0004_remove_lu_countersign_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="trading_country_code",
            field=models.CharField(max_length=2, null=True),
        ),
    ]
