# Generated by Django 3.2.21 on 2023-10-20 13:52

from django.db import migrations


def update_trading_country_code(apps, schema_editor):
    Country = apps.get_model("countries", "Country")

    mapping = (
        ("AX", "FI"),
        ("BAT", "AQ"),
        ("ES-CE", "XC"),
        ("ES-ML", "XL"),
        ("MC", "FR"),
        ("PR", "US"),
        ("RS", "XS"),
    )

    for country_code, trading_country_code in mapping:
        country = Country.objects.get(id=country_code)
        country.trading_country_code = trading_country_code
        country.save()


class Migration(migrations.Migration):

    dependencies = [
        ("countries", "0005_country_trading_country_code"),
    ]

    operations = [
        migrations.RunPython(
            update_trading_country_code,
            migrations.RunPython.noop,
        ),
    ]
