# Generated by Django 2.2.4 on 2019-09-05 09:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('drafts', '0001_initial'),
        ('organisations', '0001_initial'),
        ('countries', '0002_auto_20190628_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, default=None)),
                ('address', models.TextField(blank=True, default=None)),
                ('website', models.URLField(blank=True, default=None)),
                ('party_type', models.CharField(choices=[('government', 'Government'), ('commercial', 'Commercial Organisation'), ('individual', 'Individual'), ('other', 'Other')], default='other', max_length=20)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='application_party', to='applications.Application')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.Country')),
                ('draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='draft_party', to='drafts.Draft')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organisation_party', to='organisations.Organisation')),
            ],
        ),
        migrations.CreateModel(
            name='ThirdParty',
            fields=[
                ('party_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='parties.Party')),
                ('third_party_type', models.CharField(choices=[('intermediate_consignee', 'Intermediate Consignee'), ('agent', 'Agent'), ('submitter', 'Authorised Submitter'), ('consultant', 'Consultant'), ('contact', 'Contact'), ('exporter', 'Exporter'), ('other', 'Other')], default='other', max_length=20)),
            ],
            bases=('parties.party',),
        ),
    ]
