# Generated by Django 2.2.4 on 2019-09-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='type',
            field=models.CharField(choices=[('consignee', 'Consignee'), ('end_user', 'End User'), ('ultimate_end_user', 'Ultimate End User'), ('third_party', 'Third Party')], max_length=20),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='sub_type',
            field=models.CharField(choices=[('intermediate_consignee', 'Intermediate Consignee'), ('agent', 'Agent'), ('submitter', 'Authorised Submitter'), ('consultant', 'Consultant'), ('contact', 'Contact'), ('exporter', 'Exporter'), ('other', 'Other')], default='other', max_length=22),
        ),
    ]
