# Generated by Django 2.2.4 on 2019-12-02 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD:parties/document/migrations/0001_initial.py
        ('parties', '0001_initial'),
        ('documents', '0001_initial'),
=======
        ("parties", "0001_initial"),
>>>>>>> 3ee0f3aed18c2051e207ab050c85559fed824262:parties/migrations/0002_partydocument.py
    ]

    operations = [
        migrations.CreateModel(
            name='PartyDocument',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.Document')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.Party')),
            ],
            bases=('documents.document',),
        ),
    ]
