# Generated by Django 2.2.9 on 2020-01-28 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_auto_20200128_2215'),
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parties', to='applications.BaseApplication'),
        ),
    ]
