# Generated by Django 2.2.9 on 2020-01-29 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0002_party_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='application',
        ),
    ]
