# Generated by Django 2.2.4 on 2019-09-18 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("parties", "0002_partydocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="partydocument",
            name="party",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="parties.Party"),
        ),
    ]
