# Generated by Django 2.2.10 on 2020-03-11 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0005_auto_20200303_1516"),
    ]

    operations = [
        migrations.AlterModelOptions(name="party", options={"ordering": ["name"]},),
    ]
