# Generated by Django 2.2.8 on 2020-01-22 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_auto_20200122_1306'),
        ('cases', '0009_auto_20200122_1306'),
        ('parties', '0005_base_party_sub_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consignee',
        ),
    ]
