# Generated by Django 2.2.8 on 2020-01-23 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0005_base_party_sub_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="copy_of",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="parties.Party"),
        ),
    ]
