# Generated by Django 2.2.8 on 2020-01-22 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_auto_20200122_1448'),
        ('end_user_advisories', '0002_auto_20200122_1448'),
        ('applications', '0008_auto_20200122_1448'),
        ('parties', '0006_delete_consignee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EndUser',
        ),
    ]
