# Generated by Django 2.2.13 on 2020-07-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0009_auto_20200626_0958"),
    ]

    operations = [
        migrations.AddField(
            model_name="party", name="role_other", field=models.CharField(default=None, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name="party", name="sub_type_other", field=models.CharField(default=None, max_length=75, null=True),
        ),
    ]
