# Generated by Django 2.2.13 on 2020-06-09 15:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licences', '0002_licence_decisions'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenLicenceReturns',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.TextField()),
                ('year', models.PositiveSmallIntegerField()),
                ('licences', models.ManyToManyField(related_name='open_licence_returns', to='licences.Licence')),
            ],
        ),
    ]
