# Generated by Django 2.2.13 on 2020-06-12 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compliancesitecase",
            name="site",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING, related_name="compliance", to="organisations.Site"
            ),
        ),
    ]
