# Generated by Django 2.2.13 on 2020-06-18 13:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0038_auto_20200615_1400"),
        ("compliance", "0002_compliancesitecase"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceVisitCase",
            fields=[
                (
                    "case_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cases.Case",
                    ),
                ),
                (
                    "visit_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("first_contact", "First contact"),
                            ("first_visit", "First visit"),
                            ("routine_visit", "Routine visit"),
                            ("revisit", "Revisit"),
                        ],
                        default=None,
                        max_length=15,
                        null=True,
                    ),
                ),
                ("visit_date", models.DateField(blank=True, default=None, null=True)),
                (
                    "overall_risk_value",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("very_low", "very low risk"),
                            ("lower", "lower risk"),
                            ("medium", "medium risk"),
                            ("higher", "higher risk"),
                            ("highest", "highest risk"),
                        ],
                        default=None,
                        max_length=10,
                        null=True,
                    ),
                ),
                ("licence_risk_value", models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ("overview", models.TextField(blank=True, default=None, null=True)),
                ("inspection", models.TextField(blank=True, default=None, null=True)),
                ("compliance_overview", models.TextField(blank=True, default=None, null=True)),
                (
                    "compliance_risk_value",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("very_low", "very low risk"),
                            ("lower", "lower risk"),
                            ("medium", "medium risk"),
                            ("higher", "higher risk"),
                            ("highest", "highest risk"),
                        ],
                        default=None,
                        max_length=10,
                        null=True,
                    ),
                ),
                ("individuals_overview", models.TextField(blank=True, default=None, null=True)),
                (
                    "individuals_risk_value",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("very_low", "very low risk"),
                            ("lower", "lower risk"),
                            ("medium", "medium risk"),
                            ("higher", "higher risk"),
                            ("highest", "highest risk"),
                        ],
                        default=None,
                        max_length=10,
                        null=True,
                    ),
                ),
                ("products_overview", models.TextField(blank=True, default=None, null=True)),
                (
                    "products_risk_value",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("very_low", "very low risk"),
                            ("lower", "lower risk"),
                            ("medium", "medium risk"),
                            ("higher", "higher risk"),
                            ("highest", "highest risk"),
                        ],
                        default=None,
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "site_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="visit_case",
                        to="compliance.ComplianceSiteCase",
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("cases.case",),
        ),
        migrations.CreateModel(
            name="CompliancePerson",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created_at"
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="updated_at"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("job_title", models.CharField(max_length=100)),
                (
                    "visit_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="people_present",
                        to="compliance.ComplianceVisitCase",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
