# Generated by Django 2.2.13 on 2020-06-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0004_auto_20200625_0823"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compliancevisitcase", name="visit_date", field=models.DateField(default=None, null=True),
        ),
    ]
