# Generated by Django 2.2.11 on 2020-04-01 14:54

from django.db import migrations
import separatedvaluesfield.models


class Migration(migrations.Migration):

    dependencies = [
        ("routing_rules", "0002_auto_20200401_1309"),
    ]

    operations = [
        migrations.AddField(
            model_name="routingrule",
            name="additional_rules",
            field=separatedvaluesfield.models.SeparatedValuesField(
                blank=True,
                choices=[("users", "Users"), ("case_types", "Case Types"), ("flags", "flags"), ("country", "Country")],
                default=None,
                max_length=100,
                null=True,
            ),
        ),
    ]
