# Generated by Django 2.2.11 on 2020-04-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routing_rules", "0003_routingrule_additional_rules"),
    ]

    operations = [
        migrations.AddField(model_name="routingrule", name="Active", field=models.BooleanField(default=True),),
    ]
