# Generated by Django 2.2.11 on 2020-04-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("routing_rules", "0004_routingrule_active"),
    ]

    operations = [
        migrations.RenameField(model_name="routingrule", old_name="Active", new_name="active",),
    ]
