# Generated by Django 2.2.11 on 2020-04-03 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("routing_rules", "0005_auto_20200402_1105"),
    ]

    operations = [
        migrations.AlterModelOptions(name="routingrule", options={"ordering": ["team__name", "tier", "-created_at"]},),
    ]
