# Generated by Django 3.1.8 on 2021-04-26 05:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import sortedm2m.fields
import uuid


class Migration(migrations.Migration):

    replaces = [
        ("letter_templates", "0001_initial"),
        ("letter_templates", "0002_lettertemplate_decisions"),
        ("letter_templates", "0003_auto_20200316_1041"),
        ("letter_templates", "0004_lettertemplate_visible_to_exporter"),
        ("letter_templates", "0005_lettertemplate_include_digital_signature"),
    ]

    initial = True

    dependencies = [
        ("decisions", "0001_initial"),
        ("letter_layouts", "0001_initial"),
        ("cases", "0004_auto_20200211_1459"),
        ("picklists", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LetterTemplate",
            fields=[
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created_at"
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="updated_at"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=35, unique=True)),
                ("case_types", models.ManyToManyField(related_name="letter_templates", to="cases.CaseType")),
                (
                    "layout",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="letter_layouts.letterlayout"),
                ),
                (
                    "letter_paragraphs",
                    sortedm2m.fields.SortedManyToManyField(help_text=None, to="picklists.PicklistItem"),
                ),
                ("decisions", models.ManyToManyField(related_name="letter_templates", to="decisions.Decision")),
                ("visible_to_exporter", models.BooleanField(default=True)),
                ("include_digital_signature", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
