# Generated by Django 3.1.8 on 2021-04-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter_templates', '0001_squashed_0005_lettertemplate_include_digital_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettertemplate',
            name='include_digital_signature',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='lettertemplate',
            name='visible_to_exporter',
            field=models.BooleanField(),
        ),
    ]
