# Generated by Django 3.2.11 on 2023-05-22 15:57

from django.db import migrations

from api.picklists.enums import PickListStatus, PicklistType


def populate_inform_letter_template(apps, schema_editor):


    LU_TEAM_ID = "00000000-0000-0000-0000-000000000001"  # /PS-IGNORE
    LETTER_TEMPLATE_ID = "73aec0e7-8156-4ed8-8c57-b2877413cd07"  # /PS-IGNORE
    
    INFORM_LETTERS = [
        {"name": "Weapons of mass destruction (WMD)", "text":"Hello WMD"},
        {"name": "Military and military", "text": "Hello MAM"},
        {"name": "Military and weapons of mass destruction (WMD)", "text" :"Hello MWMD"},
    ]
    PicklistItem = apps.get_model("picklists", "PicklistItem")
     
    picklist_item_ids = []
    LetterTemplates = apps.get_model("letter_templates", "LetterTemplate")
    
    Team = apps.get_model("teams", "Team")
    lu_team = Team.objects.get(pk=LU_TEAM_ID)


    for inform_letter in INFORM_LETTERS:
            pick_list_item = PicklistItem(
                team=lu_team,
                name=inform_letter["name"],
                text=inform_letter["text"],
                type=PicklistType.LETTER_PARAGRAPH,
                status=PickListStatus.ACTIVE,
            )
            pick_list_item.save()
            picklist_item_ids.append(pick_list_item.id)
    
    import pdb
    pdb.set_trace()       
    
    inform_letter_template = LetterTemplates.objects.get(pk=LETTER_TEMPLATE_ID)
    inform_letter_template.letter_paragraphs.set(picklist_item_ids)
    inform_letter_template.save()        


class Migration(migrations.Migration):

    dependencies = [
        ("letter_templates", "0002_auto_20210426_1014"),
    ]

    operations = [
        migrations.RunPython(populate_inform_letter_template, migrations.RunPython.noop),
    ]
