# Generated by Django 2.2.11 on 2020-03-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letter_templates", "0003_auto_20200316_1041"),
    ]

    operations = [
        migrations.AddField(
            model_name="lettertemplate",
            name="visible_to_exporter",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
