# Generated by Django 2.2.13 on 2020-06-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letter_templates", "0004_lettertemplate_visible_to_exporter"),
    ]

    operations = [
        migrations.AddField(
            model_name="lettertemplate",
            name="include_digital_signature",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
