# Generated by Django 3.2.11 on 2023-08-21 15:57

from django.db import migrations



def inform_letter_update_military_picklist(apps, schema_editor):

    PicklistItem = apps.get_model("picklists", "PicklistItem")
    military_pick_list_item = PicklistItem.objects.get(name="Military and military")
    military_pick_list_item.name = "Military"
    military_pick_list_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ("letter_templates", "0005_inform_letter_template_change_advice_type"),
    ]

    operations = [
        migrations.RunPython(inform_letter_update_military_picklist, migrations.RunPython.noop),
    ]
