# Generated by Django 2.2.4 on 2019-10-07 09:10

from django.db import migrations, models


def initialize(apps, schema_editor):
    LetterLayout = apps.get_model('letter_layouts', 'LetterLayout')
    if not LetterLayout.objects.all():
        team = LetterLayout(id='licence',
                            name='Licence')
        team.save()
        team = LetterLayout(id='siel',
                            name='SIEL')
        team.save()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LetterLayout',
            fields=[
                ('id', models.CharField(editable=False, max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(initialize)
    ]
