# Generated by Django 2.2.10 on 2020-02-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flags", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flag", name="name", field=models.CharField(default="Untitled Flag", max_length=25, unique=True),
        ),
    ]
