# Generated by Django 2.2.11 on 2020-03-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flags", "0003_flaggingrule"),
    ]

    operations = [
        migrations.AlterModelOptions(name="flaggingrule", options={"ordering": ["team__name", "-created_at"]},),
        migrations.AddIndex(
            model_name="flaggingrule", index=models.Index(fields=["created_at"], name="flags_flagg_created_0d8cd4_idx"),
        ),
    ]
