# Generated by Django 4.2.11 on 2024-04-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flags", "0005_auto_20220824_2337"),
    ]

    operations = [
        migrations.AddField(
            model_name="flag",
            name="remove_on_finalised",
            field=models.BooleanField(default=False),
        ),
    ]
