# Generated by Django 4.2.11 on 2024-03-25 17:29

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("flags", "0005_auto_20220824_2337"),
    ]

    operations = [
        migrations.CreateModel(
            name="RemoveFlag",
            fields=[
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created_at"
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="updated_at"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "alias",
                    models.TextField(
                        default=None, help_text="fixed static field for reference", null=True, unique=True
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Case", "Case"),
                            ("Organisation", "Organisation"),
                            ("Good", "Good"),
                            ("Destination", "Destination"),
                            ("PartyOnApplication", "PartyOnApplication"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Deactivated", "Deactivated")], default="Active", max_length=20
                    ),
                ),
            ],
            options={
                "db_table": "remove_flag",
            },
        ),
    ]
