# Generated by Django 3.2.11 on 2024-06-17 08:22

from django.db import migrations


def populate_lu_cic_flag(apps, schema_editor):
    LICENSING_TEAM_UNIT_ID= '58e77e47-42c8-499f-a58d-94f94541f8c6'
    FLAG_NAME = 'LU Change in Circumstances'
    Flag = apps.get_model("flags", "Flag")
    
    if not Flag.objects.filter(name=FLAG_NAME):
        Flag.objects.create(
            name = FLAG_NAME,
            level = 'Case',
            team_id = LICENSING_TEAM_UNIT_ID,
            blocks_finalising=True,
            alias = 'LU_CHANGE_IN_CIRCUMSTANCES',
        )


class Migration(migrations.Migration):

    dependencies = [
        ("flags", "0006_flag_remove_on_finalised"),
    ]

    operations = []
    operations = [
        migrations.RunPython(populate_lu_cic_flag, migrations.RunPython.noop),
    ]
