# Generated by Django 2.2.11 on 2020-04-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flags", "0006_auto_20200407_1437"),
    ]

    operations = [
        migrations.AddField(model_name="flag", name="blocks_approval", field=models.BooleanField(default=False),),
    ]
