# Generated by Django 4.2.19 on 2025-03-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0009_update_beis_to_desnz"),
        ("flags", "0006_flag_remove_on_finalised"),
    ]

    operations = [
        migrations.AddField(
            model_name="flag",
            name="applicable_by_team",
            field=models.ManyToManyField(related_name="applicable_flags", to="teams.team"),
        ),
    ]
