# Generated by Django 2.2.16 on 2020-12-23 23:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0007_flag_blocks_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='flaggingrule',
            name='matching_groups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), default=list, size=None),
        ),
        migrations.AddField(
            model_name='flaggingrule',
            name='matching_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='flaggingrule',
            name='matching_value',
            field=models.TextField(default=''),
        ),
    ]
