# Generated by Django 2.2.16 on 2020-12-23 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0008_auto_20201223_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flaggingrule',
            name='matching_value',
        ),
    ]
