# Generated by Django 2.2.16 on 2020-12-29 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flags", "0008_auto_20201223_2340"),
    ]

    operations = [
        migrations.RemoveField(model_name="flaggingrule", name="matching_value",),
        migrations.AlterField(
            model_name="flaggingrule",
            name="flag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="flagging_rules", to="flags.Flag"
            ),
        ),
    ]
