# Generated by Django 2.2.16 on 2021-01-04 15:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flags", "0009_auto_20201229_1454"),
    ]

    operations = [
        migrations.AddField(
            model_name="flaggingrule",
            name="excluded_values",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(default=""), default=list, size=None
            ),
        ),
    ]
