# Generated by Django 3.1.7 on 2021-03-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0011_auto_20210128_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='removable_by',
            field=models.CharField(choices=[('Anyone', 'Anyone'), ('Authorised countersigner', 'Authorised countersigner'), ('Head of Licensing Unit countersigner', 'Head of Licensing Unit countersigner')], default='Anyone', max_length=50),
        ),
        migrations.AlterField(
            model_name='flag',
            name='name',
            field=models.CharField(default='Untitled Flag', max_length=100, unique=True),
        ),
    ]
