# Generated by Django 2.2.10 on 2020-02-11 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("generated_documents", "0001_initial"),
        ("letter_templates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedcasedocument",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="letter_templates.LetterTemplate"
            ),
        ),
    ]
