# Generated by Django 2.2.10 on 2020-03-11 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("generated_documents", "0003_auto_20200218_1203"),
    ]

    operations = [
        migrations.AlterModelOptions(name="generatedcasedocument", options={"ordering": ["name"]},),
    ]
