# Generated by Django 2.2.10 on 2020-03-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generated_documents", "0003_auto_20200218_1203"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedcasedocument",
            name="advice_type",
            field=models.CharField(
                choices=[
                    ("approve", "Approve"),
                    ("proviso", "Proviso"),
                    ("refuse", "Refuse"),
                    ("no_licence_required", "No Licence Required"),
                    ("not_applicable", "Not Applicable"),
                    ("conflicting", "Conflicting"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
