# Generated by Django 2.2.4 on 2019-09-05 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('queries', '0001_initial'),
        ('end_user', '0004_delete_euaequery'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndUserAdvisoryQuery',
            fields=[
                ('query_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='queries.Query')),
                ('note', models.TextField(blank=True, default=None, null=True)),
                ('reasoning', models.TextField(blank=True, default=None, null=True)),
                ('end_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='euae_query', to='end_user.EndUser')),
            ],
            bases=('queries.query',),
        ),
    ]
