# Generated by Django 2.2.8 on 2020-02-07 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("end_user_advisories", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="enduseradvisoryquery", name="copy_of",),
    ]
