# Generated by Django 2.2.4 on 2019-09-17 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_advisories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduseradvisoryquery',
            name='copied_from',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='end_user_advisories.EndUserAdvisoryQuery'),
        ),
    ]
