# Generated by Django 2.2.8 on 2020-01-22 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_advisories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enduseradvisoryquery',
            name='end_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='eua_query', to='parties.Party'),
        ),
    ]
