# Generated by Django 2.2.9 on 2020-02-04 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0001_initial'),
        ('end_user_advisories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduseradvisoryquery',
            name='end_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='eua_query', to='parties.Party'),
        ),
    ]
