# Generated by Django 2.2.4 on 2019-09-04 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_advisories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enduseradvisoryquery',
            name='status',
        ),
    ]
