# Generated by Django 2.2.4 on 2019-09-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_advisories', '0002_additional_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enduseradvisoryquery',
            name='contact_email',
            field=models.EmailField(blank=True, default=None, max_length=254),
        ),
    ]
