# Generated by Django 2.2.11 on 2020-04-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods_query", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsquery",
            name="clc_control_list_entry",
            field=models.TextField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
