# Generated by Django 2.2.8 on 2020-01-14 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_timestampable"),
        ("goods", "0008_auto_20200114_1329"),
        ("cases", "0005_timestampable"),
        ("queries", "0001_initial"),
        ("goods_query", "0002_controllistclassificationquery_good"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoodsQuery",
            fields=[
                (
                    "query_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="queries.Query",
                    ),
                ),
                ("clc_raised_reasons", models.TextField(blank=True, default=None, null=True)),
                ("pv_grading_raised_reasons", models.TextField(blank=True, default=None, null=True)),
                (
                    "good",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, related_name="good", to="goods.Good"
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("queries.query",),
        ),
        migrations.DeleteModel(name="ControlListClassificationQuery",),
    ]
