# Generated by Django 2.2.12 on 2020-05-28 11:21

from django.db import migrations, models
import django.utils.timezone
import gov_notify.enums
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GovNotifyTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created_at')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='updated_at')),
                ('template_type', models.CharField(choices=[(gov_notify.enums.TemplateType('ecju'), 'ecju')], db_index=True, max_length=255)),
                ('template_id', models.UUIDField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
