# Generated by Django 2.2.16 on 2020-09-24 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("goodstype", "0004_auto_20200423_1456"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodstype",
            name="application",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="applications.BaseApplication"),
        ),
        migrations.AlterField(
            model_name="goodstype",
            name="comment",
            field=models.TextField(blank=True, default=None, help_text="control review comment", null=True),
        ),
        migrations.AlterField(
            model_name="goodstype",
            name="control_list_entries",
            field=models.ManyToManyField(to="control_list_entries.ControlListEntry"),
        ),
    ]
