# Generated by Django 2.2.16 on 2020-09-24 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0036_auto_20200924_1127'),
        ('goodstype', '0004_auto_20200423_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodstype',
            name='control_review',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.GoodControlReview'),
        ),
    ]
