# Generated by Django 3.2.16 on 2022-11-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodstype', '0010_goodstype_is_precedent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodstypedocument',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
