# Generated by Django 4.2.8 on 2023-12-20 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("control_list_entries", "0005_adds_5D001e"),
        ("applications", "0077_back_populate_product_report_summary_prefix_and_suffix"),
        ("goods", "0026_auto_20230201_1536"),
        ("goodstype", "0010_goodstype_is_precedent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodstype",
            name="application",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="applications.baseapplication"),
        ),
        migrations.AlterField(
            model_name="goodstype",
            name="control_list_entries",
            field=models.ManyToManyField(to="control_list_entries.controllistentry"),
        ),
        migrations.AlterField(
            model_name="goodstype",
            name="firearm_details",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="goods.firearmgooddetails",
            ),
        ),
    ]
