# Generated by Django 4.2.16 on 2024-12-16 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0074_remove_advice_goods_type_delete_goodcountrydecision"),
        ("goodstype", "0011_alter_goodstype_application_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goodstypedocument",
            name="document_ptr",
        ),
        migrations.RemoveField(
            model_name="goodstypedocument",
            name="goods_type",
        ),
        migrations.DeleteModel(
            name="GoodsType",
        ),
        migrations.DeleteModel(
            name="GoodsTypeDocument",
        ),
    ]
