# Generated by Django 2.2.4 on 2019-12-09 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("queries", "0001_initial"),
        ("cases", "0001_initial"),
        ("generated_documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="generated_case_document",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="generated_documents.GeneratedCaseDocument"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="query",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="queries.Query"),
        ),
    ]
