# Generated by Django 2.2.2 on 2019-07-01 11:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0001_initial'),
        ('gov_users', '0002_govuserrevisionmeta'),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cases', models.ManyToManyField(to='cases.Case')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queues.Queue')),
                ('users', models.ManyToManyField(to='gov_users.GovUser')),
            ],
        ),
    ]
