# Generated by Django 2.2 on 2019-05-29 09:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('denial_reasons', '0001_initial'),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDenialReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reasoning', models.TextField(blank=True, default=None, max_length=2200, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_denial_reason', to='cases.Case')),
                ('reasons', models.ManyToManyField(to='denial_reasons.DenialReason')),
            ],
        ),
    ]
