# Generated by Django 2.2.2 on 2019-07-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov_users', '0002_govuserrevisionmeta'),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseassignment',
            name='user',
        ),
        migrations.AddField(
            model_name='caseassignment',
            name='users',
            field=models.ManyToManyField(related_name='case_assignments', to='gov_users.GovUser'),
        ),
    ]
