# Generated by Django 2.2.8 on 2019-12-13 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
        ("goodstype", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodcountrydecision",
            name="good",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="goodstype.GoodsType"),
        ),
        migrations.AddField(
            model_name="ecjuquery",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="case_ecju_query", to="cases.Case"
            ),
        ),
    ]
