# Generated by Django 2.2.2 on 2019-07-01 11:21
import uuid

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('case_types', '0001_initial'),
        ('clc_queries', '0001_initial'),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_type',
            field=models.ForeignKey(default=uuid.UUID('b12cb700-7b19-40ab-b777-e82ce71e380f'), on_delete=django.db.models.deletion.DO_NOTHING, related_name='case', to='case_types.CaseType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='clc_query',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case', to='clc_queries.ClcQuery'),
        ),
        migrations.AlterField(
            model_name='case',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case', to='applications.Application'),
        ),
        migrations.AlterField(
            model_name='case',
            name='queues',
            field=models.ManyToManyField(related_name='cases', to='queues.Queue'),
        ),
    ]
