# Generated by Django 2.2.4 on 2019-09-05 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0001_initial'),
        ('users', '0006_auto_20190819_1523'),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parties.Party'),
        ),
        migrations.AddField(
            model_name='advice',
            name='ultimate_end_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ultimate_end_user', to='parties.Party'),
        ),
        migrations.AddField(
            model_name='advice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.GovUser'),
        ),
    ]
