# Generated by Django 2.2.4 on 2019-09-05 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_auto_20190819_1523'),
        ('denial_reasons', '0001_initial'),
        ('flags', '0001_initial'),
        ('queries', '0002_auto_20190904_1642'),
        ('queues', '0001_initial'),
        ('goods', '0007_merge_20190828_1402'),
        ('goodstype', '0002_goodstype_flags'),
        ('countries', '0002_auto_20190628_1252'),
        ('applications', '0004_auto_20190730_1840'),
        ('end_user', '0004_delete_euaequery'),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseassignment',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queues.Queue'),
        ),
        migrations.AddField(
            model_name='caseassignment',
            name='users',
            field=models.ManyToManyField(related_name='case_assignments', to='users.GovUser'),
        ),
        migrations.AddField(
            model_name='case',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case', to='applications.Application'),
        ),
        migrations.AddField(
            model_name='case',
            name='flags',
            field=models.ManyToManyField(related_name='cases', to='flags.Flag'),
        ),
        migrations.AddField(
            model_name='case',
            name='query',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case', to='queries.Query'),
        ),
        migrations.AddField(
            model_name='case',
            name='queues',
            field=models.ManyToManyField(related_name='cases', to='queues.Queue'),
        ),
        migrations.AddField(
            model_name='advice',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case'),
        ),
        migrations.AddField(
            model_name='advice',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.Country'),
        ),
        migrations.AddField(
            model_name='advice',
            name='denial_reasons',
            field=models.ManyToManyField(to='denial_reasons.DenialReason'),
        ),
        migrations.AddField(
            model_name='advice',
            name='end_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='end_user.EndUser'),
        ),
        migrations.AddField(
            model_name='advice',
            name='good',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.Good'),
        ),
        migrations.AddField(
            model_name='advice',
            name='goods_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goodstype.GoodsType'),
        ),
        migrations.AddField(
            model_name='advice',
            name='ultimate_end_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ultimate_end_user', to='end_user.EndUser'),
        ),
        migrations.AddField(
            model_name='advice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.GovUser'),
        ),
    ]
