# Generated by Django 2.2.3 on 2019-07-08 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clc_queries', '0003_clcquery_status'),
        ('case_types', '0001_initial'),
        ('gov_users', '0002_govuserrevisionmeta'),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseassignment',
            name='user',
        ),
        migrations.AddField(
            model_name='case',
            name='case_type',
            field=models.ForeignKey(default='0ec51727-2acf-4459-b568-93a906d84008', on_delete=django.db.models.deletion.DO_NOTHING, related_name='case', to='case_types.CaseType'),
        ),
        migrations.AddField(
            model_name='case',
            name='clc_query',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case', to='clc_queries.ClcQuery'),
        ),
        migrations.AddField(
            model_name='caseassignment',
            name='users',
            field=models.ManyToManyField(related_name='case_assignments', to='gov_users.GovUser'),
        ),
        migrations.AlterField(
            model_name='case',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case', to='applications.Application'),
        ),
    ]
