# Generated by Django 2.2.3 on 2019-07-17 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('queues', '0001_initial'),
        ('applications', '0002_auto_20190717_0851'),
        ('clc_queries', '0002_clcquery_good'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('case_types', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ExporterUser'),
        ),
        migrations.AddField(
            model_name='casenote',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_note', to='cases.Case'),
        ),
        migrations.AddField(
            model_name='casenote',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='case_note', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caseassignment',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case'),
        ),
        migrations.AddField(
            model_name='caseassignment',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queues.Queue'),
        ),
        migrations.AddField(
            model_name='caseassignment',
            name='users',
            field=models.ManyToManyField(related_name='case_assignments', to='users.GovUser'),
        ),
        migrations.AddField(
            model_name='case',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case', to='applications.Application'),
        ),
        migrations.AddField(
            model_name='case',
            name='case_type',
            field=models.ForeignKey(default='0ec51727-2acf-4459-b568-93a906d84008', on_delete=django.db.models.deletion.DO_NOTHING, related_name='case', to='case_types.CaseType'),
        ),
        migrations.AddField(
            model_name='case',
            name='clc_query',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case', to='clc_queries.ClcQuery'),
        ),
        migrations.AddField(
            model_name='case',
            name='queues',
            field=models.ManyToManyField(related_name='cases', to='queues.Queue'),
        ),
    ]
