# Generated by Django 2.2.4 on 2019-08-09 10:57

import uuid

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190724_1334'),
        ('denial_reasons', '0001_initial'),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('approve', 'Approve'), ('proviso', 'Proviso'), ('refuse', 'Refuse'), ('no_licence_required', 'No Licence Required'), ('not_applicable', 'Not Applicable')], max_length=30)),
                ('goods', django.contrib.postgres.fields.jsonb.JSONField()),
                ('destinations', django.contrib.postgres.fields.jsonb.JSONField()),
                ('proviso', models.TextField(blank=True, default=None, null=True)),
                ('advice', models.TextField(blank=True, default=None, null=True)),
                ('note', models.TextField(blank=True, default=None, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case')),
                ('denial_reasons', models.ManyToManyField(to='denial_reasons.DenialReason')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.GovUser')),
            ],
        ),
    ]
