# Generated by Django 2.2.4 on 2019-12-02 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='query',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='queries.Query'),
        ),
    ]
