# Generated by Django 2.2 on 2019-05-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casenote',
            name='text',
            field=models.TextField(blank=True, default=None, max_length=2200, null=True),
        ),
    ]
