# Generated by Django 2.2.4 on 2019-09-09 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0001_initial'),
        ('cases', '0001_initial'),
        ('goodstype', '0002_goodstype_flags'),
        ('users', '0006_auto_20190819_1523'),
        ('goods', '0007_merge_20190828_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='end_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parties.EndUser'),
        ),
        migrations.AddField(
            model_name='advice',
            name='good',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.Good'),
        ),
        migrations.AddField(
            model_name='advice',
            name='goods_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goodstype.GoodsType'),
        ),
        migrations.AddField(
            model_name='advice',
            name='ultimate_end_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ultimate_end_user', to='parties.EndUser'),
        ),
        migrations.AddField(
            model_name='advice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.GovUser'),
        ),
    ]
