# Generated by Django 2.2.4 on 2019-09-05 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_auto_20190819_1523'),
        ('denial_reasons', '0001_initial'),
        ('goods', '0007_merge_20190828_1402'),
        ('queues', '0001_initial'),
        ('cases', '0001_initial'),
        ('goodstype', '0002_goodstype_flags'),
        ('queries', '0001_initial'),
        ('countries', '0002_auto_20190628_1252'),
        ('end_user', '0004_delete_euaequery'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='query',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case', to='queries.Query'),
        ),
        migrations.AddField(
            model_name='case',
            name='queues',
            field=models.ManyToManyField(related_name='cases', to='queues.Queue'),
        ),
        migrations.AddField(
            model_name='advice',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case'),
        ),
        migrations.AddField(
            model_name='advice',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.Country'),
        ),
        migrations.AddField(
            model_name='advice',
            name='denial_reasons',
            field=models.ManyToManyField(to='denial_reasons.DenialReason'),
        ),
        migrations.AddField(
            model_name='advice',
            name='end_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='end_user.EndUser'),
        ),
        migrations.AddField(
            model_name='advice',
            name='good',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.Good'),
        ),
        migrations.AddField(
            model_name='advice',
            name='goods_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goodstype.GoodsType'),
        ),
        migrations.AddField(
            model_name='advice',
            name='ultimate_end_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ultimate_end_user', to='end_user.EndUser'),
        ),
        migrations.AddField(
            model_name='advice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.GovUser'),
        ),
    ]
