# Generated by Django 2.2.4 on 2019-11-18 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("queries", "0001_initial"),
        ("cases", "0001_initial"),
        ("goodstype", "0001_initial"),
        ("countries", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="query",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="queries.Query"),
        ),
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="goodcountrydecision",
            name="case",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cases.Case"),
        ),
        migrations.AddField(
            model_name="goodcountrydecision",
            name="country",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="countries.Country"),
        ),
        migrations.AddField(
            model_name="goodcountrydecision",
            name="good",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="goodstype.GoodsType"),
        ),
        migrations.AddField(
            model_name="ecjuquery",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="case_ecju_query", to="cases.Case"
            ),
        ),
        migrations.AddField(
            model_name="ecjuquery",
            name="raised_by_user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="govuser_ecju_query",
                to="users.GovUser",
            ),
        ),
        migrations.AddField(
            model_name="ecjuquery",
            name="responded_by_user",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exportuser_ecju_query",
                to="users.ExporterUser",
            ),
        ),
        migrations.AddField(
            model_name="casenote",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="case_note", to="cases.Case"
            ),
        ),
        migrations.AddField(
            model_name="casenote",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_note",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="casedocument",
            name="case",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cases.Case"),
        ),
        migrations.AddField(
            model_name="casedocument",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.GovUser"),
        ),
        migrations.AddField(
            model_name="caseassignment",
            name="case",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cases.Case"),
        ),
    ]
