# Generated by Django 2.2.4 on 2019-08-14 14:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('denial_reasons', '0001_initial'),
        ('end_user', '0002_enduser_organisation'),
        ('goods', '0002_good_organisation'),
        ('goodstype', '0001_initial'),
        ('users', '0003_auto_20190724_1334'),
        ('countries', '0002_auto_20190628_1252'),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('approve', 'Approve'), ('proviso', 'Proviso'), ('refuse', 'Refuse'), ('no_licence_required', 'No Licence Required'), ('not_applicable', 'Not Applicable')], max_length=30)),
                ('text', models.TextField(blank=True, default=None, null=True)),
                ('note', models.TextField(blank=True, default=None, null=True)),
                ('proviso', models.TextField(blank=True, default=None, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.Country')),
                ('denial_reasons', models.ManyToManyField(to='denial_reasons.DenialReason')),
                ('end_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='end_user.EndUser')),
                ('good', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.Good')),
                ('goods_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goodstype.GoodsType')),
                ('ultimate_end_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ultimate_end_user', to='end_user.EndUser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.GovUser')),
            ],
        ),
    ]
