# Generated by Django 2.2.4 on 2019-09-11 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_list_classifications', '0002_controllistclassificationquery_good'),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='clc_query',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='control_list_classifications.ControlListClassificationQuery'),
        ),
    ]
