# Generated by Django 2.2.2 on 2019-06-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0002_remove_queue_cases'),
        ('cases', '0002_casenote_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='cases',
            field=models.ManyToManyField(to='queues.Queue'),
        ),
    ]
