# Generated by Django 2.2.4 on 2019-08-12 09:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190724_1334'),
        ('cases', '0002_case_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcjuQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=5000)),
                ('response', models.CharField(max_length=5000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_ecju_query', to='cases.Case')),
                ('raised_by_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='govuser_ecju_query', to='users.GovUser')),
                ('responded_by_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exportuser_ecju_query', to='users.ExporterUser')),
            ],
        ),
    ]
