# Generated by Django 2.2.3 on 2019-07-17 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20190717_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casenote',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='case_note', to=settings.AUTH_USER_MODEL),
        ),
    ]
