# Generated by Django 2.2.4 on 2019-08-21 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_advice_ecjuquery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='note',
        ),
        migrations.AddField(
            model_name='notification',
            name='case_note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.CaseNote'),
        ),
        migrations.AddField(
            model_name='notification',
            name='ecju_query',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.EcjuQuery'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
