# Generated by Django 2.2.3 on 2019-07-05 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gov_users', '0002_govuserrevisionmeta'),
        ('documents', '0001_initial'),
        ('cases', '0002_auto_20190708_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.Document')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gov_users.GovUser')),
            ],
            bases=('documents.document',),
        ),
    ]
