# Generated by Django 2.2.4 on 2019-09-09 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
        ('cases', '0002_auto_20190909_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='consignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consignee', to='parties.Consignee'),
        ),
    ]
