# Generated by Django 2.2.2 on 2019-07-01 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20190701_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.ForeignKey(default='0ec51727-2acf-4459-b568-93a906d84008', on_delete=django.db.models.deletion.DO_NOTHING, related_name='case', to='case_types.CaseType'),
        ),
    ]
