# Generated by Django 2.2.4 on 2019-10-31 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0004_merge_20190911_1610'),
        ('cases', '0002_goodcountrydecision'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQueue',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('queues.queue',),
        ),
    ]
