# Generated by Django 2.2.3 on 2019-07-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20190708_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='casenote',
            name='is_visible_for_exporter',
            field=models.BooleanField(default=False),
        ),
    ]
