# Generated by Django 2.2.4 on 2019-09-04 16:42

from django.db import migrations
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20190904_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': [django.db.models.functions.comparison.Coalesce('application__submitted_at', 'query__submitted_at')]},
        ),
    ]
