# Generated by Django 2.2.4 on 2019-11-18 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("parties", "0001_initial"),
        ("cases", "0002_auto_20191118_1511"),
        ("goodstype", "0001_initial"),
        ("goods", "0001_initial"),
        ("countries", "0001_initial"),
        ("users", "0001_initial"),
        ("flags", "0001_initial"),
        ("denial_reasons", "0001_initial"),
        ("queues", "0001_initial"),
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="caseassignment",
            name="queue",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="queues.Queue"),
        ),
        migrations.AddField(
            model_name="caseassignment",
            name="users",
            field=models.ManyToManyField(related_name="case_assignments", to="users.GovUser"),
        ),
        migrations.AddField(
            model_name="case", name="flags", field=models.ManyToManyField(related_name="cases", to="flags.Flag"),
        ),
        migrations.AddField(
            model_name="case", name="queues", field=models.ManyToManyField(related_name="cases", to="queues.Queue"),
        ),
        migrations.AddField(
            model_name="baseactivity",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="advice",
            name="case",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cases.Case"),
        ),
        migrations.AddField(
            model_name="advice",
            name="consignee",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="consignee", to="parties.Consignee"
            ),
        ),
        migrations.AddField(
            model_name="advice",
            name="country",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="countries.Country"),
        ),
        migrations.AddField(
            model_name="advice", name="denial_reasons", field=models.ManyToManyField(to="denial_reasons.DenialReason"),
        ),
        migrations.AddField(
            model_name="advice",
            name="end_user",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="parties.EndUser"),
        ),
        migrations.AddField(
            model_name="advice",
            name="good",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="goods.Good"),
        ),
        migrations.AddField(
            model_name="advice",
            name="goods_type",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="goodstype.GoodsType"),
        ),
        migrations.AddField(
            model_name="advice",
            name="third_party",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="third_party",
                to="parties.ThirdParty",
            ),
        ),
        migrations.AddField(
            model_name="advice",
            name="ultimate_end_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ultimate_end_user",
                to="parties.UltimateEndUser",
            ),
        ),
        migrations.AddField(
            model_name="advice",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="users.GovUser"),
        ),
        migrations.AddField(
            model_name="teamadvice",
            name="team",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="teams.Team"),
        ),
        migrations.AddField(
            model_name="notification",
            name="case_activity",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="cases.CaseActivity"),
        ),
        migrations.AddField(
            model_name="caseactivity",
            name="case",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cases.Case"),
        ),
    ]
