# Generated by Django 2.2.2 on 2019-06-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov_users', '0002_govuserrevisionmeta'),
        ('cases', '0002_auto_20190618_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='users',
            field=models.ManyToManyField(related_name='cases', to='gov_users.GovUser'),
        ),
    ]
