# Generated by Django 2.2.9 on 2020-01-27 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0001_initial'),
        ('countries', '0001_initial'),
        ('flags', '0001_initial'),
        ('organisations', '0001_initial'),
        ('goods', '0002_gooddocument_organisation'),
        ('denial_reasons', '0001_initial'),
        ('queues', '0001_initial'),
        ('teams', '0001_initial'),
        ('statuses', '0001_initial'),
        ('users', '0001_initial'),
        ('goodstype', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0002_auto_20200127_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecjuquery',
            name='raised_by_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='govuser_ecju_query', to='users.GovUser'),
        ),
        migrations.AddField(
            model_name='ecjuquery',
            name='responded_by_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exportuser_ecju_query', to='users.ExporterUser'),
        ),
        migrations.AddField(
            model_name='casenote',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_note', to='cases.Case'),
        ),
        migrations.AddField(
            model_name='casenote',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='case_note', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case'),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.GovUser'),
        ),
        migrations.AddField(
            model_name='caseassignment',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_assignments', to='cases.Case'),
        ),
        migrations.AddField(
            model_name='caseassignment',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queues.Queue'),
        ),
        migrations.AddField(
            model_name='caseassignment',
            name='users',
            field=models.ManyToManyField(related_name='case_assignments', to='users.GovUser'),
        ),
        migrations.AddField(
            model_name='case',
            name='case_officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.GovUser'),
        ),
        migrations.AddField(
            model_name='case',
            name='flags',
            field=models.ManyToManyField(related_name='cases', to='flags.Flag'),
        ),
        migrations.AddField(
            model_name='case',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation'),
        ),
        migrations.AddField(
            model_name='case',
            name='queues',
            field=models.ManyToManyField(related_name='cases', to='queues.Queue'),
        ),
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='query_status', to='statuses.CaseStatus'),
        ),
        migrations.AddField(
            model_name='advice',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case'),
        ),
        migrations.AddField(
            model_name='advice',
            name='consignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consignee', to='parties.Party'),
        ),
        migrations.AddField(
            model_name='advice',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.Country'),
        ),
        migrations.AddField(
            model_name='advice',
            name='denial_reasons',
            field=models.ManyToManyField(to='denial_reasons.DenialReason'),
        ),
        migrations.AddField(
            model_name='advice',
            name='end_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parties.Party'),
        ),
        migrations.AddField(
            model_name='advice',
            name='good',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.Good'),
        ),
        migrations.AddField(
            model_name='advice',
            name='goods_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goodstype.GoodsType'),
        ),
        migrations.AddField(
            model_name='advice',
            name='third_party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_party', to='parties.Party'),
        ),
        migrations.AddField(
            model_name='advice',
            name='ultimate_end_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ultimate_end_user', to='parties.Party'),
        ),
        migrations.AddField(
            model_name='advice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.GovUser'),
        ),
        migrations.AddField(
            model_name='teamadvice',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team'),
        ),
    ]
