# Generated by Django 2.2.4 on 2019-08-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_advice_ecjuquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='created_at',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='advice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
