# Generated by Django 2.2.2 on 2019-07-16 13:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0001_initial'),
        ('cases', '0002_auto_20190708_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseFlags',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_flags', to='cases.Case')),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_flags', to='flags.Flag')),
            ],
        ),
    ]
