# Generated by Django 2.2.2 on 2019-07-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0001_initial'),
        ('cases', '0002_auto_20190708_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='flags',
            field=models.ManyToManyField(related_name='cases', to='flags.Flag'),
        ),
    ]
