# Generated by Django 2.2.4 on 2019-10-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_goodcountrydecision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='type',
            field=models.CharField(choices=[('application', 'Application'), ('clc_query', 'CLC Query'), ('end_user_advisory_query', 'End User Advisory Query'), ('hmrc_query', 'HMRC Query')], default='application', max_length=35),
        ),
    ]
