# Generated by Django 2.2.2 on 2019-07-11 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0001_initial'),
        ('cases', '0002_auto_20190702_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseFlags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_on_flag', to='cases.Case')),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flag_on_case', to='flags.Flag')),
            ],
        ),
    ]
