# Generated by Django 2.2.8 on 2020-01-07 16:41

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20191209_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='created',
        ),
        migrations.RemoveField(
            model_name='case',
            name='modified',
        ),
        migrations.AddField(
            model_name='advice',
            name='updated_at',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='updated_at'),
        ),
        migrations.AddField(
            model_name='case',
            name='created_at',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created_at'),
        ),
        migrations.AddField(
            model_name='case',
            name='updated_at',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='updated_at'),
        ),
        migrations.AddField(
            model_name='caseassignment',
            name='created_at',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created_at'),
        ),
        migrations.AddField(
            model_name='caseassignment',
            name='updated_at',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='updated_at'),
        ),
        migrations.AddField(
            model_name='casenote',
            name='updated_at',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='updated_at'),
        ),
        migrations.AddField(
            model_name='ecjuquery',
            name='updated_at',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='updated_at'),
        ),
        migrations.AddField(
            model_name='goodcountrydecision',
            name='created_at',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created_at'),
        ),
        migrations.AddField(
            model_name='goodcountrydecision',
            name='updated_at',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='advice',
            name='created_at',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='casenote',
            name='created_at',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='ecjuquery',
            name='created_at',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created_at'),
        ),
    ]
