# Generated by Django 2.2.4 on 2019-09-30 10:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('goodstype', '0003_goodstype_countries'),
        ('countries', '0002_auto_20190628_1252'),
        ('cases', '0003_auto_20190919_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodCountryDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('advice_type', models.CharField(choices=[('approve', 'Approve'), ('proviso', 'Proviso'), ('refuse', 'Refuse'), ('no_licence_required', 'No Licence Required'), ('not_applicable', 'Not Applicable'), ('conflicting', 'Conflicting')], max_length=30)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.Country')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodstype.GoodsType')),
            ],
        ),
    ]
