# Generated by Django 2.2.4 on 2019-12-05 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_auto_20191203_0910"),
    ]

    operations = [
        migrations.RemoveField(model_name="generatedcasedocument", name="casedocument_ptr",),
        migrations.RemoveField(model_name="generatedcasedocument", name="template",),
    ]
