# Generated by Django 2.2.3 on 2019-07-05 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20190702_1525'),
        ('cases', '0003_auto_20190701_1344'),
    ]

    operations = [
    ]
