# Generated by Django 2.2.4 on 2019-08-26 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_advice_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casedocument',
            name='description',
        ),
    ]
