# Generated by Django 2.2.10 on 2020-02-11 14:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_auto_20200210_1326"),
    ]

    operations = [
        migrations.RemoveField(model_name="case", name="type",),
        migrations.RemoveField(model_name="casetype", name="id",),
        migrations.RemoveField(model_name="casetype", name="name",),
        migrations.AddField(
            model_name="casetype",
            name="reference",
            field=models.CharField(
                choices=[
                    ("oiel", "OIEL"),
                    ("ogel", "OGEL"),
                    ("oicl", "OICL"),
                    ("siel", "SIEL"),
                    ("sicl", "SICL"),
                    ("sitl", "SITL"),
                    ("f680", "F680"),
                    ("exhc", "EXHC"),
                    ("gift", "GIFT"),
                    ("cre", "CRE"),
                    ("gqy", "GQY"),
                    ("eua", "EUA"),
                ],
                default="siel",
                max_length=5,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="casetype",
            name="sub_type",
            field=models.CharField(
                choices=[
                    ("standard", "Standard"),
                    ("open", "Open"),
                    ("hmrc", "HMRC"),
                    ("exhibition_clearance", "Exhibition clearance"),
                    ("end_user_advisory", "End user advisory"),
                ],
                default="standard",
                max_length=35,
            ),
        ),
        migrations.AddField(
            model_name="casetype",
            name="type",
            field=models.CharField(
                choices=[("application", "Application"), ("query", "Query")], default="application", max_length=35
            ),
        ),
        migrations.AddField(
            model_name="casetype",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="case",
            name="case_type",
            field=models.ForeignKey(
                default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="cases.CaseType"
            ),
        ),
    ]
