# Generated by Django 2.2.4 on 2019-11-19 08:42
import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cases", "0003_auto_20191118_1511"), ("statuses", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="type",
            field=models.CharField(
                choices=[
                    ("application", "Application"),
                    ("clc_query", "CLC Query"),
                    ("end_user_advisory_query", "End User Advisory Query"),
                    ("hmrc_query", "HMRC Query"),
                ],
                max_length=35,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="query_status",
                to="statuses.CaseStatus",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="submitted_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
