# Generated by Django 2.2.4 on 2019-08-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_advice_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
