# Generated by Django 2.2.3 on 2019-07-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_casedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedocument',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=280, null=True),
        ),
    ]
