# Generated by Django 2.2.3 on 2019-07-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_casedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
