# Generated by Django 2.2.4 on 2019-09-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_baseactivity_caseactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseactivity',
            name='additional_text',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='baseactivity',
            name='text',
            field=models.TextField(default=None),
        ),
    ]
