# Generated by Django 2.2.3 on 2019-07-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20190717_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='casenote',
            name='is_visible_to_exporter',
            field=models.BooleanField(default=False),
        ),
    ]
