# Generated by Django 2.2.3 on 2019-07-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_casenote_is_visible_for_exporter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casenote',
            name='is_visible_for_exporter',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
