# Generated by Django 2.2.4 on 2019-08-26 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_advice_created_at'),
        ('cases', '0003_auto_20190821_1432'),
    ]

    operations = [
    ]
