# Generated by Django 2.2.3 on 2019-07-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_casedocument_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedocument',
            name='s3_key',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
