# Generated by Django 2.2.4 on 2019-09-10 12:25

from django.db import migrations, models
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': [django.db.models.functions.comparison.Coalesce('application__submitted_at', 'clc_query__submitted_at')]},
        ),
        migrations.AlterField(
            model_name='ecjuquery',
            name='response',
            field=models.CharField(max_length=2200, null=True),
        ),
    ]
