# Generated by Django 2.2.3 on 2019-07-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_auto_20190712_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casenote',
            name='is_visible_for_exporter',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
