# Generated by Django 2.2.4 on 2019-09-06 12:23

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.comparison


def init(apps, schema_editor):

    Permission = apps.get_model('users', 'Permission')
    if not Permission.objects.filter(id='MANAGE_TEAM_ADVICE'):
        permission = Permission(id='MANAGE_TEAM_ADVICE',
                                name='Manage team advice')
        permission.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20190918_0838'),
        ('teams', '0001_initial')
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': [django.db.models.functions.comparison.Coalesce('application__submitted_at', 'clc_query__submitted_at')]},
        ),
        migrations.AlterField(
            model_name='ecjuquery',
            name='response',
            field=models.CharField(max_length=2200, null=True),
        ),
        migrations.CreateModel(
            name='TeamAdvice',
            fields=[
                ('advice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cases.Advice')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team')),
            ],
            bases=('cases.advice',),
        ),
        migrations.RunPython(init),
    ]
