# Generated by Django 2.2.4 on 2019-08-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_merge_20190826_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecjuquery',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
