# Generated by Django 2.2.4 on 2019-12-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0004_auto_20191030_1220"),
    ]

    operations = [
        migrations.AddField(
            model_name="casedocument",
            name="type",
            field=models.CharField(
                choices=[("UPLOADED", "Uploaded"), ("GENERATED", "Generated")], default="UPLOADED", max_length=100
            ),
        ),
    ]
