# Generated by Django 2.2.4 on 2019-09-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecjuquery',
            name='response',
            field=models.CharField(max_length=2200, null=True),
        ),
    ]
