# Generated by Django 2.2.4 on 2019-11-23 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("letter_templates", "0001_initial"),
        ("cases", "0004_auto_20191030_1220"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseType",
            fields=[
                ("id", models.CharField(editable=False, max_length=30, primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("application", "Application"),
                            ("clc_query", "CLC Query"),
                            ("end_user_advisory_query", "End User Advisory Query"),
                            ("hmrc_query", "HMRC Query"),
                        ],
                        max_length=35,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="casedocument",
            name="type",
            field=models.CharField(
                choices=[("UPLOADED", "Uploaded"), ("GENERATED", "Generated")], default="UPLOADED", max_length=100
            ),
        ),
        migrations.CreateModel(
            name="GeneratedDocument",
            fields=[
                (
                    "casedocument_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cases.CaseDocument",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="letter_templates.LetterTemplate"
                    ),
                ),
            ],
            bases=("cases.casedocument",),
        ),
    ]
