# Generated by Django 2.2.4 on 2019-11-18 15:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('letter_templates', '0002_auto_20191114_1113'),
        ('cases', '0004_auto_20191030_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Document')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letter_templates.LetterTemplate')),
            ],
        ),
    ]
