# Generated by Django 2.2.4 on 2019-12-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0004_auto_20191030_1220"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseType",
            fields=[
                ("id", models.CharField(editable=False, max_length=30, primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("application", "Application"),
                            ("clc_query", "CLC Query"),
                            ("end_user_advisory_query", "End User Advisory Query"),
                            ("hmrc_query", "HMRC Query"),
                        ],
                        max_length=35,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="casedocument",
            name="type",
            field=models.CharField(
                choices=[("UPLOADED", "Uploaded"), ("GENERATED", "Generated")], default="UPLOADED", max_length=100
            ),
        ),
    ]
