# Generated by Django 2.2.4 on 2019-09-13 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
        ('cases', '0004_auto_20190912_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodActivity',
            fields=[
                ('baseactivity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cases.BaseActivity')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Good')),
            ],
            bases=('cases.baseactivity',),
        ),
    ]
