# Generated by Django 2.2.3 on 2019-07-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0001_initial'),
        ('cases', '0004_casedocument_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='flags',
            field=models.ManyToManyField(related_name='cases', to='flags.Flag'),
        ),
    ]
