# Generated by Django 2.2.4 on 2019-11-20 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letter_templates', '0002_auto_20191114_1113'),
        ('cases', '0004_auto_20191030_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedocument',
            name='type',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('GENERATED', 'Generated')], default='UPLOADED', max_length=100),
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('casedocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cases.CaseDocument')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='letter_templates.LetterTemplate')),
            ],
            bases=('cases.casedocument',),
        ),
    ]
