# Generated by Django 2.2.4 on 2019-09-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_auto_20190906_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice',
            name='type',
            field=models.CharField(choices=[('approve', 'Approve'), ('proviso', 'Proviso'), ('refuse', 'Refuse'), ('no_licence_required', 'No Licence Required'), ('not_applicable', 'Not Applicable'), ('conflicting', 'Conflicting')], max_length=30),
        ),
    ]
