# Generated by Django 2.2.4 on 2019-12-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0005_auto_20191127_1435"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedcasedocument", name="text", field=models.TextField(blank=True, default=True),
        ),
    ]
