# Generated by Django 2.2.4 on 2019-09-05 10:20

from django.db import migrations
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_auto_20190903_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': [django.db.models.functions.comparison.Coalesce('application__submitted_at', 'clc_query__submitted_at')]},
        ),
    ]
