# Generated by Django 2.2.4 on 2019-09-14 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_auto_20190914_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='ecju_query',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.EcjuQuery'),
        ),
    ]
