# Generated by Django 2.2.8 on 2020-01-14 13:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0005_timestampable"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseReferenceCode",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("reference_number", models.IntegerField()),
                ("year", models.IntegerField(editable=False)),
            ],
        ),
    ]
