# Generated by Django 2.2.4 on 2019-12-04 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_auto_20191203_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseactivity',
            name='baseactivity_ptr',
        ),
        migrations.RemoveField(
            model_name='caseactivity',
            name='case',
        ),
        migrations.DeleteModel(
            name='BaseActivity',
        ),
        migrations.DeleteModel(
            name='CaseActivity',
        ),
    ]
