# Generated by Django 2.2.4 on 2019-11-19 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_generateddocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateddocument',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='letter_templates.LetterTemplate'),
        ),
    ]
