# Generated by Django 2.2.4 on 2019-09-10 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_auto_20190910_1225'),
        ('cases', '0006_case_ordering'),
    ]

    operations = [
    ]
