# Generated by Django 2.2.4 on 2019-12-05 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0006_casetype"),
        ("generated_documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="generated_case_document",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="generated_documents.GeneratedCaseDocument"
            ),
        ),
    ]
