# Generated by Django 2.2.10 on 2020-03-02 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0006_auto_20200225_1128"),
    ]

    operations = [
        migrations.RemoveField(model_name="casedocument", name="description",),
        migrations.RemoveField(model_name="casedocument", name="type",),
    ]
