# Generated by Django 2.2.8 on 2020-01-14 10:16

from django.db import migrations, models

from cases.libraries.reference_code import generate_reference_code


class Migration(migrations.Migration):
    def initialize(apps, schema_editor):
        # All cases need to have a reference code
        Case = apps.get_model("cases", "Case")
        for case in Case.objects.all():
            if not case.reference_code:
                case.reference_code = generate_reference_code(case)
                case.save()

    dependencies = [
        ("cases", "0006_casereferencecode"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="reference_code",
            field=models.CharField(default=None, editable=False, max_length=30, unique=True, null=True, blank=True),
        ),
        migrations.RunPython(initialize),
    ]
