# Generated by Django 2.2.4 on 2019-11-20 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_auto_20191119_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generateddocument',
            name='case',
        ),
        migrations.RemoveField(
            model_name='generateddocument',
            name='document',
        ),
        migrations.RemoveField(
            model_name='generateddocument',
            name='id',
        ),
        migrations.RemoveField(
            model_name='generateddocument',
            name='name',
        ),
        migrations.AddField(
            model_name='casedocument',
            name='type',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('GENERATED', 'Generated')], default='UPLOADED', max_length=100),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='casedocument_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cases.CaseDocument'),
            preserve_default=False,
        ),
    ]
