# Generated by Django 2.2.4 on 2019-09-18 12:17

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.comparison


def init(apps, schema_editor):

    Permission = apps.get_model('users', 'Permission')
    if not Permission.objects.filter(id='MANAGE_FINAL_ADVICE'):
        permission = Permission(id='MANAGE_FINAL_ADVICE',
                                name='Manage final advice')
        permission.save()
        Permission.objects.get(id='MAKE_FINAL_DECISIONS').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_auto_20190909_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalAdvice',
            fields=[
                ('advice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cases.Advice')),
            ],
            bases=('cases.advice',),
        ),
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': [django.db.models.functions.comparison.Coalesce('application__submitted_at', 'query__submitted_at')]},
        ),
        migrations.RunPython(init),
    ]
