# Generated by Django 2.2.10 on 2020-02-28 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0006_auto_20200225_1128"),
    ]

    operations = [
        migrations.RemoveField(model_name="casedocument", name="description",),
    ]
