# Generated by Django 2.2.8 on 2020-01-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_case_reference_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='reference_code',
            field=models.CharField(default=None, editable=False, max_length=30, unique=True),
        ),
    ]
