# Generated by Django 2.2.10 on 2020-03-04 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generated_documents', '0003_auto_20200218_1203'),
        ('cases', '0006_auto_20200225_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaladvice',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='generated_documents.GeneratedCaseDocument'),
        ),
    ]
