# Generated by Django 2.2.10 on 2020-03-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0007_auto_20200303_1516"),
    ]

    operations = [
        migrations.AddField(
            model_name="casedocument",
            name="visible_to_exporter",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
