# Generated by Django 2.2.10 on 2020-02-28 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0007_remove_casedocument_description"),
    ]

    operations = [
        migrations.RemoveField(model_name="casedocument", name="type",),
    ]
