# Generated by Django 2.2.10 on 2020-02-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0007_advice_pv_grading"),
    ]

    operations = [
        migrations.AddField(
            model_name="advice", name="conflicting_pv_grading", field=models.CharField(max_length=60, null=True),
        ),
    ]
