# Generated by Django 2.2.4 on 2019-09-11 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_merge_20190910_1455'),
        ('cases', '0007_finaladvice'),
    ]

    operations = [
    ]
