# Generated by Django 2.2.11 on 2020-03-20 12:10

from django.db import migrations, models
import django.db.models.deletion


def convert_users(apps, schema_editor):
    CaseAssignment = apps.get_model("cases", "CaseAssignment")
    db_alias = schema_editor.connection.alias
    case_assignments = CaseAssignment.objects.using(db_alias).all()
    for assignment in case_assignments:
        for user in assignment.users.all():
            CaseAssignment.objects.create(case=assignment.case, queue=assignment.queue, user=user)
        assignment.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20200311_1124"),
        ("cases", "0008_casedocument_visible_to_exporter"),
    ]

    operations = [
        migrations.AddField(
            model_name="caseassignment",
            name="user",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="users.GovUser"),
        ),
        migrations.AlterField(
            model_name="caseassignment",
            name="queue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="case_assignments", to="queues.Queue"
            ),
        ),
        migrations.RunPython(convert_users),
    ]
