# Generated by Django 2.2.8 on 2020-01-23 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0008_auto_20200116_1514"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caseassignment",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="case_assignments", to="cases.Case"
            ),
        ),
    ]
