# Generated by Django 2.2.10 on 2020-03-02 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0008_advice_conflicting_pv_grading"),
    ]

    operations = [
        migrations.RenameField(model_name="advice", old_name="conflicting_pv_grading", new_name="collated_pv_grading",),
    ]
