# Generated by Django 2.2.9 on 2020-01-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0008_auto_20200116_1514"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="type",
            field=models.CharField(
                choices=[
                    ("application", "Application"),
                    ("goods_query", "Product Query"),
                    ("end_user_advisory_query", "End User Advisory Query"),
                    ("hmrc_query", "HMRC Query"),
                ],
                max_length=35,
            ),
        ),
        migrations.AlterField(
            model_name="casetype",
            name="name",
            field=models.CharField(
                choices=[
                    ("application", "Application"),
                    ("goods_query", "Product Query"),
                    ("end_user_advisory_query", "End User Advisory Query"),
                    ("hmrc_query", "HMRC Query"),
                ],
                max_length=35,
            ),
        ),
    ]
