# Generated by Django 2.2.11 on 2020-03-20 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_casedocument_visible_to_exporter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caseassignment',
            old_name='users',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='caseassignment',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_assignments', to='queues.Queue'),
        ),
    ]
