# Generated by Django 2.2.11 on 2020-03-20 11:40

from django.db import migrations, models
import django.db.models.deletion

from cases.models import CaseAssignment


def forwards_func(apps, schema_editor):
    CaseAssignment.objects.all.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20200311_1124"),
        ("cases", "0008_casedocument_visible_to_exporter"),
    ]

    operations = [
        migrations.RemoveField(model_name="caseassignment", name="users",),
        migrations.AddField(
            model_name="caseassignment",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_assignments",
                to="users.GovUser",
            ),
        ),
        migrations.AlterField(
            model_name="caseassignment",
            name="queue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="case_assignments", to="queues.Queue"
            ),
        ),
        migrations.RunPython(forwards_func),
    ]
