# Generated by Django 2.2.10 on 2020-03-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0009_auto_20200302_1412"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advice",
            name="collated_pv_grading",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
