# Generated by Django 2.2.11 on 2020-03-20 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0010_auto_20200320_1255"),
    ]

    operations = [
        migrations.RemoveField(model_name="caseassignment", name="users",),
    ]
