# Generated by Django 2.2.8 on 2020-02-07 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0011_auto_20200203_1426"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="copy_of",
            field=models.ForeignKey(
                default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to="cases.Case"
            ),
        ),
    ]
