# Generated by Django 2.2.9 on 2020-02-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_auto_20200203_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='type',
            field=models.CharField(choices=[('application', 'Application'), ('goods_query', 'Goods Query'), ('end_user_advisory_query', 'End User Advisory Query'), ('hmrc_query', 'HMRC Query'), ('exhibition_clearance', 'MOD Exhibition Clearance'), ('gifting_clearance', 'Gifting Clearance'), ('F680_clearance', 'F680 Clearance')], max_length=35),
        ),
        migrations.AlterField(
            model_name='casetype',
            name='name',
            field=models.CharField(choices=[('application', 'Application'), ('goods_query', 'Goods Query'), ('end_user_advisory_query', 'End User Advisory Query'), ('hmrc_query', 'HMRC Query'), ('exhibition_clearance', 'MOD Exhibition Clearance'), ('gifting_clearance', 'Gifting Clearance'), ('F680_clearance', 'F680 Clearance')], max_length=35),
        ),
    ]
