# Generated by Django 2.2.11 on 2020-03-20 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0011_auto_20200320_1329"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caseassignment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="case_assignments", to="users.GovUser"
            ),
        ),
    ]
