# Generated by Django 2.2.11 on 2020-04-20 14:44

from django.db import migrations
from django.db.models import Count


def forward_step(apps, schema_editor):
    CaseAssignment = apps.get_model("cases.CaseAssignment")

    dups = (
        CaseAssignment.objects.values("case_id", "user_id", "queue_id")
        .annotate(count=Count("id"))
        .values("case_id", "user_id", "queue_id")
        .order_by()
        .filter(count__gt=1)
    )

    for value in dups:
        objects = CaseAssignment.objects.filter(
            case_id=value["case_id"], user_id=value["user_id"], queue_id=value["queue_id"]
        ).order_by("created_at")[1:]

        for object in objects:
            object.delete()


def backwards_step(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("queues", "0001_initial"),
        ("users", "0005_auto_20200322_1547"),
        ("cases", "0013_auto_20200325_1544"),
    ]

    operations = [
        migrations.RunPython(forward_step, backwards_step),
        migrations.AlterUniqueTogether(name="caseassignment", unique_together={("case", "user", "queue")},),
    ]
