# Generated by Django 2.2.11 on 2020-03-27 13:11

import cases.models
from django.db import migrations
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_auto_20200325_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='id',
            field=cases.models.LiteUUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
