# Generated by Django 2.2.11 on 2020-05-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0014_auto_20200420_1444"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casereferencecode", name="year", field=models.IntegerField(editable=False, unique=True),
        ),
    ]
