# Generated by Django 2.2.11 on 2020-05-02 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0015_auto_20200502_1817"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advice",
            name="country",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="advice", to="countries.Country"
            ),
        ),
    ]
