# Generated by Django 2.2.11 on 2020-05-07 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20200307_1805'),
        ('cases', '0018_auto_20200505_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='level',
            field=models.CharField(choices=[('user', 'User'), ('team', 'Team'), ('final', 'Final')], default='user', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advice',
            name='new_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.Team'),
        ),
    ]
