# Generated by Django 2.2.11 on 2020-05-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0021_remove_team_final_advice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casereferencecode", name="year", field=models.IntegerField(editable=False, unique=True),
        ),
    ]
