# Generated by Django 2.2.11 on 2020-05-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0022_auto_20200513_1023"),
    ]

    operations = [
        migrations.AddField(model_name="advice", name="footnote", field=models.TextField(blank=True, null=True),),
    ]
