# Generated by Django 2.2.11 on 2020-05-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0023_advice_footnote"),
    ]

    operations = [
        migrations.AddField(
            model_name="advice",
            name="footnote_required",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="advice", name="footnote", field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
