# Generated by Django 2.2.12 on 2020-05-18 16:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0023_auto_20200515_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
