# Generated by Django 2.2.12 on 2020-05-20 10:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0024_enforcementcheckid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
