# Generated by Django 2.2.12 on 2020-05-27 12:01

from django.db import migrations, models


def remove_existing_entity_ids(apps, schema_editor):
    EnforcementCheckID = apps.get_model("cases", "EnforcementCheckID")
    EnforcementCheckID.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0027_auto_20200522_0945"),
    ]

    operations = [
        migrations.RunPython(remove_existing_entity_ids),
    ]
