# Generated by Django 2.2.12 on 2020-05-29 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0027_auto_20200522_0945"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casedocument",
            name="user",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="users.GovUser"),
        ),
    ]
