# Generated by Django 2.2.12 on 2020-06-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0028_auto_20200529_0925"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casedocument",
            name="type",
            field=models.CharField(
                choices=[("UPLOADED", "Uploaded"), ("GENERATED", "Generated"), ("AUTO_GENERATED", "Auto Generated")],
                default="UPLOADED",
                max_length=100,
            ),
        ),
    ]
