# Generated by Django 2.2.13 on 2020-06-05 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_auto_20200307_1805"),
        ("cases", "0030_auto_20200601_1433"),
    ]

    operations = [
        migrations.AddField(
            model_name="ecjuquery",
            name="team",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="teams.Team"),
        ),
    ]
