# Generated by Django 2.2.13 on 2020-06-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0038_auto_20200615_1400"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casetype",
            name="sub_type",
            field=models.CharField(
                choices=[
                    ("standard", "Standard Licence"),
                    ("open", "Open Licence"),
                    ("hmrc", "HMRC Query"),
                    ("end_user_advisory", "End User Advisory Query"),
                    ("goods", "Goods Query"),
                    ("exhibition_clearance", "MOD Exhibition Clearance"),
                    ("gifting_clearance", "MOD Gifting Clearance"),
                    ("f680_clearance", "MOD F680 Clearance"),
                    ("compliance_site", "Compliance Site Case"),
                    ("compliance_visit", "Compliance Visit Case"),
                ],
                max_length=35,
            ),
        ),
    ]
