# Generated by Django 2.2.13 on 2020-06-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0039_auto_20200618_1318"),
    ]

    operations = [
        migrations.AddField(
            model_name="case", name="next_review_date", field=models.DateField(default=None, null=True),
        ),
    ]
