# Generated by Django 2.2.13 on 2020-06-25 15:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_auto_20200307_1805"),
        ("cases", "0040_case_next_review_date"),
    ]

    operations = [
        migrations.RemoveField(model_name="case", name="next_review_date",),
        migrations.CreateModel(
            name="CaseReviewDate",
            fields=[
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created_at"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("next_review_date", models.DateField(default=None, null=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="case_review_date", to="cases.Case"
                    ),
                ),
                ("team", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="teams.Team")),
            ],
            options={"unique_together": {("case", "team")},},
        ),
    ]
