# Generated by Django 2.2.13 on 2020-07-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0041_casereviewdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodcountrydecision',
            name='approve',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
