# Generated by Django 2.2.13 on 2020-07-10 15:44

from django.db import migrations, models

from cases.enums import AdviceType


def convert_good_country_decision(apps, schema_editor):
    GoodCountryDecision = apps.get_model("cases", "GoodCountryDecision")
    for goodCountryDecision in GoodCountryDecision.objects.all():
        if goodCountryDecision.decision == AdviceType.APPROVE or goodCountryDecision.decision == AdviceType.PROVISO:
            goodCountryDecision.approve = True
        else:
            goodCountryDecision.approve = False
        goodCountryDecision.save()


def reverse_good_country_decision(apps, schema_editor):
    GoodCountryDecision = apps.get_model("cases", "GoodCountryDecision")
    for goodCountryDecision in GoodCountryDecision.objects.all():
        if goodCountryDecision.approve:
            goodCountryDecision.decision = AdviceType.APPROVE
        else:
            goodCountryDecision.decision = AdviceType.REFUSE
        goodCountryDecision.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0042_goodcountrydecision_approve'),
    ]

    operations = [
        migrations.RunPython(
            convert_good_country_decision,
            reverse_code=reverse_good_country_decision
        ),
    ]
