# Generated by Django 2.2.13 on 2020-07-13 14:01

from django.db import migrations

from cases.enums import AdviceType


def convert_good_country_decision(apps, schema_editor):
    """
    Maps the decision AdviceTypes to a boolean as GoodCountryDecision
    can only be approved (True) or refused (false).
    Other AdviceTypes do not apply
    """
    GoodCountryDecision = apps.get_model("cases", "GoodCountryDecision")
    for goodCountryDecision in GoodCountryDecision.objects.all():
        if goodCountryDecision.decision == AdviceType.APPROVE or goodCountryDecision.decision == AdviceType.PROVISO:
            goodCountryDecision.approve = True
        else:
            goodCountryDecision.approve = False
        goodCountryDecision.save()


def reverse_good_country_decision(apps, schema_editor):
    GoodCountryDecision = apps.get_model("cases", "GoodCountryDecision")
    for goodCountryDecision in GoodCountryDecision.objects.all():
        if goodCountryDecision.approve:
            goodCountryDecision.decision = AdviceType.APPROVE
        else:
            goodCountryDecision.decision = AdviceType.REFUSE
        goodCountryDecision.save()


class Migration(migrations.Migration):
    dependencies = [
        ("goodstype", "0004_auto_20200423_1456"),
        ("countries", "0001_initial"),
        ("cases", "0043_auto_20200713_1400"),
    ]

    operations = [
        migrations.RunPython(convert_good_country_decision, reverse_code=reverse_good_country_decision),
    ]
