# Generated by Django 2.2.13 on 2020-07-10 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
        ('goodstype', '0004_auto_20200423_1456'),
        ('cases', '0043_auto_20200710_1544'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoodCountryDecision',
            new_name='GoodsTypeCountryDecision',
        ),
        migrations.RenameField(
            model_name='goodstypecountrydecision',
            old_name='good',
            new_name='goods_type',
        ),
    ]
