# Generated by Django 2.2.13 on 2020-07-10 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodstype', '0004_auto_20200423_1456'),
        ('countries', '0001_initial'),
        ('cases', '0044_auto_20200710_1555'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='goodstypecountrydecision',
            unique_together={('case', 'goods_type', 'country')},
        ),
        migrations.RemoveField(
            model_name='goodstypecountrydecision',
            name='decision',
        ),
    ]
