# Generated by Django 2.2.13 on 2020-07-22 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0045_auto_20200713_1402"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advice",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
