# Generated by Django 2.2.2 on 2019-07-01 11:21

import uuid

from django.db import migrations, models


def initialize(apps, schema_editor):
    # Load the case_types table with a couple of rows of pre-configured case types
    case_type = apps.get_app_config('case_types').get_model('CaseType')
    if not case_type.objects.all():
        case_type.objects.create(id='0ec51727-2acf-4459-b568-93a906d84008', name='Licence application')
        case_type.objects.create(id='b12cb700-7b19-40ab-b777-e82ce71e380f', name='CLC query')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(default=None)),
            ],
        ),
        migrations.RunPython(initialize)
    ]
