# Generated by Django 2.2 on 2019-05-08 14:45

from django.db import migrations, models


def destroy(apps, schema_editor):
    Country = apps.get_model('countries', 'Country')
    if Country.objects.all():
        Country.objects.all().delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.CharField(primary_key=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
    ]
