# Generated by Django 2.2.9 on 2020-01-31 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('is_eu', models.BooleanField()),
                ('flags', models.ManyToManyField(related_name='countries', to='flags.Flag')),
            ],
        ),
    ]
