# Generated by Django 2.2.8 on 2020-01-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_country_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='is_eu',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
