# Generated by Django 4.2.17 on 2025-01-22 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0075_update_licence_decision_denial_reasons"),
    ]

    operations = [
        migrations.CreateModel(
            name="F680Application",
            fields=[
                (
                    "case_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cases.case",
                    ),
                ),
                ("data", models.JSONField()),
            ],
            options={
                "abstract": False,
            },
            bases=("cases.case",),
        ),
    ]
