# Generated by Django 4.2.18 on 2025-01-27 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "0084_standardapplication_subject_to_itar_controls"),
    ]

    operations = [
        migrations.CreateModel(
            name="F680Application",  # /PS-IGNORE
            fields=[
                (
                    "baseapplication_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="applications.baseapplication",
                    ),
                ),
                ("application", models.JSONField()),
            ],
            options={
                "abstract": False,
            },
            bases=("applications.baseapplication",),
        ),
    ]
