# Generated by Django 4.2.19 on 2025-03-10 13:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0014_alter_organisation_status"),
        ("countries", "0006_update_trading_country_code"),
        ("f680", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("description", models.TextField()),
                (
                    "security_grading",
                    models.CharField(
                        choices=[
                            ("unclassified", "Unclassified"),
                            ("official", "Official"),
                            ("official-sensitive", "Official - sensitive"),
                            ("restricted", "Restricted"),
                            ("confidential", "Confidential"),
                            ("secret", "Secret"),
                            ("top-secret", "Top-secret"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("security_grading_other", models.TextField(default=None, null=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organisation_product",
                        to="organisations.organisation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("address", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("end-user", "End-user"),
                            ("ultimate-end-user", "Ultimate end-user"),
                            ("third-party", "Third party"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("agent-broker", "End-user"),
                            ("intermediate-consignee", "Intermediate consignee"),
                            ("authorised-submitter", "Authorised submitter"),
                            ("consultant", "Consultant"),
                            ("contact", "Contact"),
                            ("exporter", "Exporter"),
                            ("other", "Other"),
                        ],
                        default=None,
                        max_length=50,
                        null=True,
                    ),
                ),
                ("role_other", models.TextField(default=None, null=True)),
                ("country", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="countries.country")),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organisation_recipient",
                        to="organisations.organisation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SecurityRelease",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "security_grading",
                    models.CharField(
                        choices=[
                            ("official", "Official"),
                            ("official-sensitive", "Official - sensitive"),
                            ("secret", "Secret"),
                            ("top-secret", "Top-secret"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("security_grading_other", models.TextField(default=None, null=True)),
                ("intended_use", models.TextField()),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="f680.f680application"  # /PS-IGNORE
                    ),
                ),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="f680.product")),
                ("recipient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="f680.recipient")),
            ],
        ),
    ]
