# Generated by Django 4.2.17 on 2025-01-22 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0084_standardapplication_subject_to_itar_controls"),
        ("f680", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="f680application",
            name="case_ptr",
        ),
        migrations.AddField(
            model_name="f680application",
            name="baseapplication_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default="00dee880-8d7c-4161-aa52-7f601a202b90",
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="applications.baseapplication",
            ),
            preserve_default=False,
        ),
    ]
