# Generated by Django 4.2.19 on 2025-03-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("f680", "0002_product_recipient_securityreleaserequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="security_grading",
            field=models.CharField(
                choices=[
                    ("unclassified", "Unclassified"),
                    ("official", "Official"),
                    ("official-sensitive", "Official - sensitive"),
                    ("restricted", "Restricted"),
                    ("confidential", "Confidential"),
                    ("secret", "Secret"),
                    ("top-secret", "Top-secret"),
                    ("other", "Other"),
                ],
                default=None,
                max_length=50,
                null=True,
            ),
        ),
    ]
