# Generated by Django 4.2.19 on 2025-03-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("f680", "0003_alter_product_security_grading"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipient",
            name="role",
            field=models.CharField(
                choices=[
                    ("agent-or-broker", "Agent or broker"),
                    ("intermediate-consignee", "Intermediate consignee"),
                    ("authorised-submitter", "Authorised submitter"),
                    ("consultant", "Consultant"),
                    ("contact", "Contact"),
                    ("exporter", "Exporter"),
                    ("other", "Other"),
                ],
                default=None,
                max_length=50,
                null=True,
            ),
        ),
    ]
