# Generated by Django 4.2.19 on 2025-03-13 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("f680", "0004_alter_recipient_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securityreleaserequest",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="security_release_requests",
                to="f680.f680application",
            ),
        ),
        migrations.AlterField(
            model_name="securityreleaserequest",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="security_release_requests", to="f680.product"
            ),
        ),
        migrations.AlterField(
            model_name="securityreleaserequest",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="security_release_requests",
                to="f680.recipient",
            ),
        ),
    ]
