# Generated by Django 4.2.19 on 2025-03-13 16:07

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("f680", "0005_alter_securityreleaserequest_application_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now, editable=False, verbose_name="created_at"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now, editable=False, verbose_name="updated_at"
            ),
        ),
        migrations.AddField(
            model_name="recipient",
            name="created_at",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now, editable=False, verbose_name="created_at"
            ),
        ),
        migrations.AddField(
            model_name="recipient",
            name="updated_at",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now, editable=False, verbose_name="updated_at"
            ),
        ),
        migrations.AddField(
            model_name="securityreleaserequest",
            name="created_at",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now, editable=False, verbose_name="created_at"
            ),
        ),
        migrations.AddField(
            model_name="securityreleaserequest",
            name="updated_at",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now, editable=False, verbose_name="updated_at"
            ),
        ),
    ]
