# Generated by Django 4.2.16 on 2025-03-17 10:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0079_licencedecision_cases_licen_created_850df1_idx"),
        ("users", "0007_delete_govnotification"),
        ("teams", "0009_update_beis_to_desnz"),
        ("f680", "0006_product_created_at_product_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created_at"
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="updated_at"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[("approve", "Approve"), ("refuse", "Refuse"), ("not_applicable", "Not applicable")],
                        max_length=30,
                    ),
                ),
                ("conditions", models.TextField(blank=True, default="", null=True)),
                ("refusal_reasons", models.TextField(blank=True, default="", null=True)),
                (
                    "security_grading",
                    models.CharField(
                        choices=[
                            ("official", "Official"),
                            ("official-sensitive", "Official - sensitive"),
                            ("secret", "Secret"),
                            ("top-secret", "Top-secret"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("security_grading_other", models.TextField(blank=True, default="", null=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="recommendations", to="cases.case"
                    ),
                ),
                (
                    "security_release_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="f680.securityreleaserequest",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recommendations",
                        to="teams.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="recommendations", to="users.govuser"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
