# Generated by Django 4.2.19 on 2025-03-25 09:52

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0009_update_beis_to_desnz"),
        ("users", "0007_delete_govnotification"),
        ("cases", "0082_update_security_clearance_case_type_hierarchy"),
        ("f680", "0007_f680_recommendation"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityReleaseOutcome",
            fields=[
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created_at"
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="updated_at"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("outcome", models.CharField(choices=[("approve", "Approve"), ("refuse", "Refuse")], max_length=30)),
                ("conditions", models.TextField(blank=True, default="", null=True)),
                ("refusal_reasons", models.TextField(blank=True, default="", null=True)),
                (
                    "security_grading",
                    models.CharField(
                        choices=[
                            ("official", "Official"),
                            ("official-sensitive", "Official - sensitive"),
                            ("secret", "Secret"),
                            ("top-secret", "Top-secret"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "approval_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("initial_discussion_or_promoting", "Initial discussion or promoting"),
                                ("demonstration_in_uk", "Demonstration in UK"),
                                ("demonstration_overseas", "Demonstration overseas"),
                                ("training", "Training"),
                                ("through_life_support", "Through life support"),
                                ("supply", "Supply"),
                            ],
                            max_length=50,
                        ),
                        size=None,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_release_outcomes",
                        to="cases.case",
                    ),
                ),
                ("security_release_requests", models.ManyToManyField(to="f680.securityreleaserequest")),
                (
                    "team",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="security_release_outcomes",
                        to="teams.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="security_release_outcomes",
                        to="users.govuser",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
