# Generated by Django 4.2.19 on 2025-03-25 14:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("f680", "0008_securityreleaseoutcome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securityreleaseoutcome",
            name="approval_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("initial_discussion_or_promoting", "Initial discussion or promoting"),
                        ("demonstration_in_uk", "Demonstration in UK"),
                        ("demonstration_overseas", "Demonstration overseas"),
                        ("training", "Training"),
                        ("through_life_support", "Through life support"),
                        ("supply", "Supply"),
                    ],
                    max_length=50,
                ),
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="securityreleaseoutcome",
            name="security_grading",
            field=models.CharField(
                blank=True,
                choices=[
                    ("official", "Official"),
                    ("official-sensitive", "Official - sensitive"),
                    ("secret", "Secret"),
                    ("top-secret", "Top-secret"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
