# Generated by Django 4.2.16 on 2025-04-03 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("f680", "0009_alter_securityreleaseoutcome_approval_types_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recommendation",
            name="security_grading",
        ),
        migrations.RemoveField(
            model_name="recommendation",
            name="security_grading_other",
        ),
    ]
