# Generated by Django 4.2.16 on 2025-04-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("f680", "0010_remove_recommendation_security_grading_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="securityreleaseoutcome",
            name="validity_end_date",
            field=models.DateField(blank=True, help_text="Date the outcome is no longer valid", null=True),
        ),
        migrations.AddField(
            model_name="securityreleaseoutcome",
            name="validity_start_date",
            field=models.DateField(blank=True, help_text="Date the outcome validity starts", null=True),
        ),
    ]
