# Generated by Django 4.2.16 on 2025-04-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("f680", "0011_securityreleaseoutcome_validity_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendation",
            name="security_grading",
            field=models.CharField(
                blank=True,
                choices=[
                    ("official", "Official"),
                    ("official-sensitive", "Official - sensitive"),
                    ("secret", "Secret"),
                    ("top-secret", "Top-secret"),
                    ("other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="security_grading_other",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
