# Generated by Django 4.2.20 on 2025-05-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("f680", "0012_recommendation_security_grading_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="security_grading_prefix",
            field=models.CharField(
                choices=[("UK", "UK"), ("NATO", "NATO"), ("OCCAR", "OCCAR"), ("other", "Other")],
                default=None,
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="security_grading_prefix_other",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="securityreleaserequest",
            name="security_grading_prefix",
            field=models.CharField(
                choices=[("UK", "UK"), ("NATO", "NATO"), ("OCCAR", "OCCAR"), ("other", "Other")],
                default=None,
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="securityreleaserequest",
            name="security_grading_prefix_other",
            field=models.TextField(default=None, null=True),
        ),
    ]
