# Generated by Django 4.2.20 on 2025-05-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("f680", "0013_add_missing_f680_case_submitted_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="security_grading_prefix",
            field=models.CharField(
                choices=[("uk", "UK"), ("nato", "NATO"), ("occar", "OCCAR"), ("other", "Other")],
                default=None,
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="security_grading_prefix_other",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="securityreleaserequest",
            name="security_grading_prefix",
            field=models.CharField(
                choices=[("uk", "UK"), ("nato", "NATO"), ("occar", "OCCAR"), ("other", "Other")],
                default=None,
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="securityreleaserequest",
            name="security_grading_prefix_other",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="security_grading",
            field=models.CharField(
                choices=[
                    ("unclassified", "UNCLASSIFIED"),
                    ("official", "OFFICIAL"),
                    ("official-sensitive", "OFFICIAL-SENSITIVE"),
                    ("restricted", "RESTRICTED"),
                    ("confidential", "CONFIDENTIAL"),
                    ("secret", "CONFIDENTIAL"),
                    ("top-secret", "TOP SECRET"),
                    ("other", "Other"),
                ],
                default=None,
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="security_grading",
            field=models.CharField(
                blank=True,
                choices=[
                    ("official", "OFFICIAL"),
                    ("official-sensitive", "OFFICIAL-SENSITIVE"),
                    ("secret", "SECRET"),
                    ("top-secret", "TOP SECRET"),
                    ("other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="securityreleaseoutcome",
            name="security_grading",
            field=models.CharField(
                blank=True,
                choices=[
                    ("official", "OFFICIAL"),
                    ("official-sensitive", "OFFICIAL-SENSITIVE"),
                    ("secret", "SECRET"),
                    ("top-secret", "TOP SECRET"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="securityreleaserequest",
            name="security_grading",
            field=models.CharField(
                choices=[
                    ("official", "OFFICIAL"),
                    ("official-sensitive", "OFFICIAL-SENSITIVE"),
                    ("secret", "SECRET"),
                    ("top-secret", "TOP SECRET"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
