# Generated by Django 4.2.20 on 2025-05-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("f680", "0014_product_security_grading_prefix_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendation",
            name="security_grading_prefix",
            field=models.CharField(
                choices=[("uk", "UK"), ("nato", "NATO"), ("occar", "OCCAR"), ("other", "Other")],
                default=None,
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="security_grading_prefix_other",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
