# Generated by Django 3.1.8 on 2021-04-26 05:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    replaces = [('teams', '0001_initial'), ('teams', '0002_auto_20200307_1805'), ('teams', '0003_auto_20210325_0812')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(default=None, unique=True)),
                ('part_of_ecju', models.BooleanField(default=None, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
