# Generated by Django 2.2.11 on 2020-03-07 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="team", options={"ordering": ["name"]},),
    ]
