# Generated by Django 3.1.12 on 2021-09-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("teams", "0002_auto_20210924_1241")]

    operations = [
        migrations.AddField(
            model_name="team",
            name="is_ogd",
            field=models.BooleanField(default=False, help_text="Whether the team is an Other Government Department"),
        ),
        migrations.AlterField(
            model_name="team",
            name="part_of_ecju",
            field=models.BooleanField(
                default=None, help_text="Whether the team is part of Export Control Joint Unit", null=True
            ),
        ),
    ]
