# Generated by Django 3.1.7 on 2021-03-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20200307_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='part_of_ecju',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.TextField(default=None, unique=True),
        ),
    ]
