# Generated by Django 3.2.11 on 2022-02-09 09:47

from django.db import migrations


def populate_dev_team_alias(apps, schema_editor):
    flags = {
        'FCO': 'FCO',
        'Licensing Unit': 'LICENSING_UNIT',
        'MOD-ECJU': 'MOD_ECJU',
        'MOD-DI': 'MOD_DI',
        'MOD-DSR': 'MOD_DSR',
        'MOD-DSTL': 'MOD_DSTL',
        'MOD-WECA': 'MOD_WECA',
    }
    Team = apps.get_model('teams', 'Team')
    for f in flags.keys():
        team = Team.objects.filter(name__iexact=f).exclude(alias__isnull=False)
        if team.exists():
            team.update(alias=flags[f])


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_populate_team_alias_flags'),
    ]

    operations = [
        migrations.RunPython(populate_dev_team_alias, migrations.RunPython.noop),
    ]
