# Generated by Django 3.2.12 on 2022-05-31 12:44

from django.db import migrations


def populate_dev_team_alias(apps, schema_editor):
    tau_name = "Technical Assessment Unit"
    tau_alias = "TAU"
    Team = apps.get_model("teams", "Team")
    if not Team.objects.filter(alias=tau_alias).exists():
        team = Team.objects.filter(name__iexact=tau_name, alias=None)
        if team.exists():
            team.update(alias=tau_alias)


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_populate_dev_team_alias_flags'),
    ]

    operations = [
        migrations.RunPython(populate_dev_team_alias, migrations.RunPython.noop),
    ]
