# Generated by Django 2.2.11 on 2020-04-21 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("end_user_advisories", "0003_remove_enduseradvisoryquery_copy_of"),
    ]

    operations = [
        migrations.AlterModelOptions(name="enduseradvisoryquery", options={"ordering": ["created_at"]},),
    ]
