# Generated by Django 2.2.10 on 2020-02-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="F680ClearanceType",
            fields=[("id", models.CharField(max_length=45, primary_key=True, serialize=False)),],
        ),
    ]
