# Generated by Django 3.2.13 on 2022-06-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_squashed_0018_baseuser_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="exporteruser",
            name="external_id",
            field=models.CharField(blank=True, max_length=200, default=""),
        ),
    ]
