# Generated by Django 2.2.10 on 2020-03-11 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20200211_1101"),
    ]

    operations = [
        migrations.AlterModelOptions(name="role", options={"ordering": ["name"]},),
    ]
