# Generated by Django 3.2.18 on 2023-03-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_default_govuser_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
