# Generated by Django 4.2.8 on 2023-12-20 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_value_for_pending_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userorganisationrelationship",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.exporteruser"),
        ),
    ]
