# Generated by Django 4.2.14 on 2024-09-06 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_userorganisationrelationship_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GovNotification",
        ),
    ]
