# Generated by Django 2.2.13 on 2020-07-21 13:18

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_auto_20200603_1252"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="baseuser", managers=[("objects", django.contrib.auth.models.UserManager()),],
        ),
        migrations.AlterModelManagers(
            name="exporteruser", managers=[("objects", django.contrib.auth.models.UserManager()),],
        ),
        migrations.AlterModelManagers(
            name="govuser", managers=[("objects", django.contrib.auth.models.UserManager()),],
        ),
    ]
