# Generated by Django 2.2.16 on 2020-09-07 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_auto_20200907_1229"),
    ]

    operations = [
        migrations.AlterModelOptions(name="exporteruser", options={},),
        migrations.AlterModelOptions(name="govuser", options={},),
        migrations.AlterModelManagers(name="exporteruser", managers=[],),
        migrations.AlterModelManagers(name="govuser", managers=[],),
    ]
