# Generated by Django 2.2.18 on 2021-02-12 16:20

from django.db import migrations
from django.db.migrations import RunPython
from django.db.models import Q

from api.core.constants import GovPermissions
from api.users.enums import UserType


def update_permission_values(apps, schema_editor):
    """
    Update Permission objects in DB if their display value has changed
    """
    Permission = apps.get_model("users", "Permission")
    for gp in GovPermissions:
        try:
            # if any permission exist in the db with a name that doesn't match
            # the current value of the enum then update them
            # otherwise continue
            perm = Permission.objects.get(~Q(name=gp.value), id=gp.name, type=UserType.INTERNAL)
            perm.name = gp.value
            perm.save()
        except Permission.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_auto_20200907_1234"),
    ]

    operations = [
        RunPython(update_permission_values, reverse_code=RunPython.noop),
    ]
