# Generated by Django 3.1.7 on 2021-03-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210223_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='id',
            field=models.CharField(editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(default='permission - FIX', max_length=100),
        ),
    ]
