# Generated by Django 3.1.7 on 2021-04-12 16:43

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210309_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None),
        ),
    ]
