# Generated by Django 3.1.7 on 2021-04-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210309_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='phone_number',
            field=models.TextField(blank=True, default=''),
        ),
    ]
