# Generated by Django 2.2.3 on 2019-07-17 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clc_queries', '0001_initial'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clcquery',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='goods.Good'),
        ),
    ]
