# Generated by Django 2.2.3 on 2019-07-18 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clc_queries', '0002_clcquery_good'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clcquery',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='clc_query', to='goods.Good'),
        ),
    ]
