# Generated by Django 2.2.3 on 2019-07-30 18:40

from django.db import migrations, models
import django.db.models.deletion


def migrate_statuses(apps, schema_editor):
    CaseStatus = apps.get_model('statuses', 'CaseStatus')
    ClcQuery = apps.get_model('clc_queries', 'ClcQuery')

    for clc_query in ClcQuery.objects.all():
        clc_query.status = CaseStatus.objects.filter(status=clc_query.status)
        clc_query.save(update_fields=['status'])


class Migration(migrations.Migration):

    dependencies = [
        ('clc_queries', '0003_auto_20190718_1030'),
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clcquery',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='clc_query_status', to='statuses.CaseStatus'),
        ),
        migrations.RunPython(migrate_statuses),
    ]
