# Generated by Django 2.2.3 on 2019-07-17 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clc_queries', '0003_clcquery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clcquery',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='clc_query', to='goods.Good'),
        ),
    ]
