# Generated by Django 2.2.3 on 2019-07-30 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clc_queries', '0004_clcquery_submitted_at'),
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clcquery',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='clc_query_status', to='statuses.CaseStatus'),
        )
    ]
