# Generated by Django 3.1.8 on 2021-04-23 11:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('addresses', '0001_initial'), ('addresses', '0002_auto_20200326_1420')]

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_line_1', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('address_line_2', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('region', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('postcode', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('city', models.CharField(default=None, max_length=50, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.country')),
                ('address', models.CharField(blank=True, default=None, help_text='Used for addresses not in the UK', max_length=256, null=True)),
            ],
        ),
        migrations.AlterModelTable(
            name='address',
            table='address',
        ),
    ]
