# Generated by Django 4.2.14 on 2024-10-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0001_squashed_0002_auto_20200326_1420"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="address_line_3",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
