# Generated by Django 3.1.7 on 2021-04-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20200326_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='address',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
    ]
