# Generated by Django 2.2.3 on 2019-08-01 10:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PicklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('text', models.TextField(max_length=5000)),
                ('type', models.CharField(choices=[('proviso', 'Proviso'), ('ecju_query', 'ECJU Query'), ('letter_paragraph', 'Letter Paragraph'), ('annual_report_summary', 'Annual Report Summary'), ('standard_advice', 'Standard Advice'), ('footnotes', 'Footnotes')], max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Deactivated', 'Deactivated')], default='Active', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_team', to='teams.Team')),
            ],
        ),
    ]
