# Generated by Django 2.2.3 on 2019-08-01 12:48

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PicklistItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("text", models.TextField(max_length=5000)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("proviso", "Proviso"),
                            ("ecju_query", "ECJU Query"),
                            ("letter_paragraph", "Letter Paragraph"),
                            ("report_summary", "Report Summary"),
                            ("standard_advice", "Standard Advice"),
                            ("footnotes", "Footnotes"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("deactivated", "Deactivated")],
                        default="active",
                        max_length=50,
                    ),
                ),
                ("last_modified_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organisation_team",
                        to="teams.Team",
                    ),
                ),
            ],
        ),
    ]
