# Generated by Django 2.2.3 on 2019-07-31 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picklists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picklistitem',
            name='status',
            field=models.CharField(choices=[('Activate', 'Activate'), ('Deactivate', 'Deactivate')], default='Activate', max_length=50),
        ),
    ]
