# Generated by Django 2.2.11 on 2020-03-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("picklists", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picklistitem",
            name="type",
            field=models.CharField(
                choices=[
                    ("proviso", "Proviso"),
                    ("ecju_query", "Standard ECJU Query"),
                    ("letter_paragraph", "Letter Paragraph"),
                    ("report_summary", "Report Summary"),
                    ("standard_advice", "Standard Advice"),
                    ("footnotes", "Footnotes"),
                    ("pre_visit_questionnaire", "Pre-Visit Questionnaire questions (ECJU Query)"),
                    ("compliance_actions", "Compliance Actions (ECJU Query"),
                ],
                max_length=50,
            ),
        ),
    ]
