# Generated by Django 4.2.20 on 2025-05-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("picklists", "0002_auto_20220110_1430"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picklistitem",
            name="type",
            field=models.CharField(
                choices=[
                    ("proviso", "Proviso"),
                    ("ecju_query", "Standard ECJU Query"),
                    ("letter_paragraph", "Letter Paragraph"),
                    ("report_summary", "Report Summary"),
                    ("standard_advice", "Standard Advice"),
                    ("refusal_reason", "Refusal reason"),
                    ("footnotes", "Footnotes"),
                    ("pre_visit_questionnaire", "Pre-Visit Questionnaire questions (ECJU Query)"),
                    ("compliance_actions", "Compliance Actions (ECJU Query)"),
                    ("f680_proviso", "F680 Proviso"),
                ],
                max_length=50,
            ),
        ),
    ]
