# Generated by Django 4.2.16 on 2025-01-23 17:52

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0007_delete_govnotification"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExporterAnswerSet",
            fields=[
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created_at"
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="updated_at"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("flow", models.CharField(max_length=2000)),
                ("section", models.CharField(max_length=2000)),
                ("answers", models.JSONField()),
                (
                    "answer_fields",
                    django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None),
                ),
                ("frontend_commit_sha", models.CharField(max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("submitted", "Submitted")], default="draft", max_length=50
                    ),
                ),
                ("target_object_id", models.UUIDField()),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="exporter_answer_sets",
                        to="users.exporteruser",
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
