# Generated by Django 4.2.16 on 2025-01-24 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exporter_answers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exporteranswerset",
            name="superseded_by",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="exporter_answers.exporteranswerset"
            ),
        ),
    ]
