# Generated by Django 4.2.16 on 2025-01-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exporter_answers", "0002_exporteranswerset_superseded_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exporteranswerset",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("submitted", "Submitted"), ("superseded", "Superseded")],
                default="draft",
                max_length=50,
            ),
        ),
    ]
