# Generated by Django 4.2.18 on 2025-01-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exporter_answers", "0003_alter_exporteranswerset_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="exporteranswerset",
            name="questions",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
