# Generated by Django 4.2.18 on 2025-01-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exporter_answers", "0004_exporteranswerset_questions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exporteranswerset",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("superseded", "Superseded")], default="active", max_length=50
            ),
        ),
    ]
