# Generated by Django 2.1.7 on 2019-03-13 10:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('control_codes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, default=None, null=True)),
                ('friendly_name', models.TextField(blank=True, default=None, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'control_list',
            },
        ),
        migrations.CreateModel(
            name='GlobalDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'global_definition',
            },
        ),
        migrations.CreateModel(
            name='LocalDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'local_definition',
            },
        ),
        migrations.AddField(
            model_name='controlcode',
            name='decontrolled',
            field=models.BooleanField(default=False),
        ),
    ]
