# Generated by Django 3.2.15 on 2022-09-22 08:00
import csv
import os

from django.db import migrations, transaction

from api.staticdata.regimes.enums import RegimesEnum, RegimeSubsectionsEnum


def create_entries(RegimeEntry, subsection, entries_csv_filename):
    data_path = os.path.dirname(os.path.abspath(__file__))
    file_path = os.path.join(data_path, "data", entries_csv_filename)
    with open(file_path) as csvfile:
        reader = csv.reader(csvfile)
        for name, *_ in reader:
            RegimeEntry.objects.create(
                subsection=subsection,
                name=name,
            )


def create_mtcr_regimes(apps, schema_editor):
    Regime = apps.get_model("regimes", "Regime")
    RegimeSubsection = apps.get_model("regimes", "RegimeSubsection")
    RegimeEntry = apps.get_model("regimes", "RegimeEntry")

    with transaction.atomic():
        mtcr_regime = Regime.objects.create(
            id=RegimesEnum.MTCR,
            name="MTCR",
        )

        mtcr_category_1_subsection = RegimeSubsection.objects.create(
            id=RegimeSubsectionsEnum.MTCR_CATEGORY_1,
            name="MTCR Category 1",
            regime=mtcr_regime,
        )
        create_entries(
            RegimeEntry,
            mtcr_category_1_subsection,
            "MTCR_Cat_1_regimes.csv",
        )

        mtcr_category_2_subsection = RegimeSubsection.objects.create(
            id=RegimeSubsectionsEnum.MTCR_CATEGORY_2,
            name="MTCR Category 2",
            regime=mtcr_regime,
        )
        create_entries(
            RegimeEntry,
            mtcr_category_2_subsection,
            "MTCR_Cat_2_regimes.csv",
        )


class Migration(migrations.Migration):

    dependencies = [
        ("regimes", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            create_mtcr_regimes,
            migrations.RunPython.noop,
        ),
    ]
