# Generated by Django 3.2.15 on 2022-09-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regimes", "0003_add_wassenaar_regimes"),
    ]

    operations = [
        migrations.AddField(
            model_name="regimeentry",
            name="shortened_name",
            field=models.CharField(max_length=5, null=True),
        ),
    ]
