# Generated by Django 3.2.15 on 2022-09-27 14:20

from django.db import migrations, transaction


def update_wassenaar_entries(apps, schema_editor):
    RegimeEntry = apps.get_model("regimes", "RegimeEntry")

    with transaction.atomic():
        for name, shortened_name in [
            ("Wassenaar Arrangement", "W"),
            ("Wassenaar Arrangement Sensitive", "WS"),
            ("Wassenaar Arrangement Very Sensitive", "WVS"),
        ]:
            regime_entry = RegimeEntry.objects.get(name=name)
            regime_entry.shortened_name = shortened_name
            regime_entry.save()


class Migration(migrations.Migration):

    dependencies = [
        ("regimes", "0004_regimeentry_shortened_name"),
    ]

    operations = [
        migrations.RunPython(
            update_wassenaar_entries,
            migrations.RunPython.noop,
        ),
    ]
