# Generated by Django 3.2.15 on 2022-12-02 11:48

from django.db import migrations, transaction


from api.staticdata.regimes.enums import RegimesEnum, RegimeSubsectionsEnum


def create_cwc_regimes(apps, schema_editor):
    Regime = apps.get_model("regimes", "Regime")
    RegimeSubsection = apps.get_model("regimes", "RegimeSubsection")
    RegimeEntry = apps.get_model("regimes", "RegimeEntry")

    with transaction.atomic():
        cwc_regime = Regime.objects.create(
            id=RegimesEnum.CWC,
            name="CWC",
        )

        # We have a data model for the regimes that always has three levels in the hierarchy.
        # In the case of CWC there isn't really a subsection but to be consistent with the hierarchy of models
        # we create dummy entries inbetween.
        for pk, name in [
            (
                RegimeSubsectionsEnum.CWC_SCHEDULE_1,
                "CWC Schedule 1",
            ),
            (
                RegimeSubsectionsEnum.CWC_SCHEDULE_2,
                "CWC Schedule 2",
            ),
            (
                RegimeSubsectionsEnum.CWC_SCHEDULE_3,
                "CWC Schedule 3",
            ),
        ]:
            subsection = RegimeSubsection.objects.create(
                id=pk,
                name=name,
                regime=cwc_regime,
            )
            RegimeEntry.objects.create(
                name=name,
                subsection=subsection,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("regimes", "0005_update_wassenaar_entries_shortened_names"),
    ]

    operations = [
        migrations.RunPython(
            create_cwc_regimes,
            migrations.RunPython.noop,
        ),
    ]
