# Generated by Django 3.2.15 on 2022-12-02 14:09

from django.db import migrations, transaction


from api.staticdata.regimes.enums import RegimesEnum, RegimeSubsectionsEnum


def create_ag_regimes(apps, schema_editor):
    Regime = apps.get_model("regimes", "Regime")
    RegimeSubsection = apps.get_model("regimes", "RegimeSubsection")
    RegimeEntry = apps.get_model("regimes", "RegimeEntry")

    with transaction.atomic():
        ag_regime = Regime.objects.create(
            id=RegimesEnum.AG,
            name="AG",
        )

        # We have a data model for the regimes that always has three levels in the hierarchy.
        # In the case of AG there isn't really a subsection but to be consistent with the hierarchy of models
        # we create dummy entries inbetween.
        for pk, name in [
            (
                RegimeSubsectionsEnum.AG_CHEMICAL_LIST,
                "AG Chemical List",
            ),
            (
                RegimeSubsectionsEnum.AG_BIOLOGICAL_LIST,
                "AG Biological List",
            ),
        ]:
            subsection = RegimeSubsection.objects.create(
                id=pk,
                name=name,
                regime=ag_regime,
            )
            RegimeEntry.objects.create(
                name=name,
                subsection=subsection,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("regimes", "0006_add_cwc_regimes"),
    ]

    operations = [
        migrations.RunPython(
            create_ag_regimes,
            migrations.RunPython.noop,
        ),
    ]
