# Generated by Django 3.2.16 on 2022-12-12 16:16

from django.db import migrations, transaction


def update_cwc_shortened_names(apps, schema_editor):
    RegimeEntry = apps.get_model("regimes", "RegimeEntry")

    with transaction.atomic():
        for name, shortened_name in (
            ("CWC Schedule 1", "CWC 1"),
            ("CWC Schedule 2", "CWC 2"),
            ("CWC Schedule 3", "CWC 3"),
        ):
            regime_entry = RegimeEntry.objects.get(name=name)
            regime_entry.shortened_name = shortened_name
            regime_entry.save()


class Migration(migrations.Migration):

    dependencies = [
        ("regimes", "0008_add_nsg_regimes"),
    ]

    operations = [
        migrations.RunPython(
            update_cwc_shortened_names,
            migrations.RunPython.noop,
        ),
    ]
