# Generated by Django 3.2.16 on 2022-12-14 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("regimes", "0009_update_cwc_shortened_names"),
        ("regimes", "0009_update_nsg_regimes"),
    ]

    operations = []
