# Generated by Django 2.2 on 2019-05-30 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('end_user', '0001_initial'),
        ('organisations', '0003_add_sites_no_constraint'),
        ('drafts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='end_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_end_user', to='end_user.EndUser'),
        ),
        migrations.AddField(
            model_name='draft',
            name='organisation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation'),
        ),
    ]
