# Generated by Django 2.2.2 on 2019-06-18 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='cases',
        ),
    ]
