# Generated by Django 2.1.7 on 2019-04-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='name',
            field=models.TextField(default='Untitled Queue'),
        ),
    ]
