# Generated by Django 2.2 on 2019-06-12 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='team',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.Team'),
        ),
    ]
