# Generated by Django 2.2.4 on 2019-09-10 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("queues", "0002_auto_20190905_1020"),
        ("queues", "0002_auto_20190910_1225"),
    ]

    operations = []
