# Generated by Django 2.2.4 on 2019-09-11 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0002_auto_20190906_1223'),
        ('queues', '0003_merge_20190910_1455'),
    ]

    operations = [
    ]
