# Generated by Django 2.2.4 on 2019-11-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0004_merge_20190911_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='name',
            field=models.TextField(default='Untitled Queue', unique=True),
        ),
    ]
