# Generated by Django 2.2.11 on 2020-05-02 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("denial_reasons", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="denialreason", options={"ordering": ["id"]},),
    ]
