# Generated by Django 3.1.8 on 2022-01-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("denial_reasons", "0001_squashed_0004_denialreason_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="denialreason",
            name="display_value",
            field=models.TextField(default=""),
        ),
    ]
