# Generated by Django 3.1.7 on 2021-03-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denial_reasons', '0002_auto_20200502_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denialreason',
            name='id',
            field=models.TextField(editable=False, primary_key=True, serialize=False),
        ),
    ]
