# Generated by Django 3.1.7 on 2021-04-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denial_reasons', '0003_auto_20210322_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='denialreason',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
