# Generated by Django 4.2.14 on 2024-07-30 15:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("denial_reasons", "0004_denial_reasons_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="denialreason",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
