# Generated by Django 4.2.14 on 2024-08-09 15:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("denial_reasons", "0006_populate_uuid_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="denialreason",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
