# Generated by Django 3.2.18 on 2023-05-10 14:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0005_value_for_pending_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("url", models.CharField(max_length=2000)),
                ("name", models.CharField(max_length=30)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.govuser")),
            ],
        ),
    ]
