# Generated by Django 2.2.11 on 2020-04-29 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("queues", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="queue",
            name="countersigning_queue",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="queues.Queue"),
        ),
        migrations.AlterModelTable(name="queue", table="queue",),
    ]
