# Generated by Django 3.2.12 on 2022-02-24 12:29

from django.db import migrations


def add_combine_and_review_queue(apps, schema_editor):
    Team = apps.get_model("teams", "Team")
    Queue = apps.get_model("queues", "Queue")

    try:
        mod_ecju_team = Team.objects.get(name="MOD-ECJU")
    except Team.DoesNotExist:
        return

    Queue.objects.update_or_create(
        name="Review and combine",
        team=mod_ecju_team,
        defaults={
            "alias": "MOD_ECJU_REVIEW_AND_COMBINE",
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("queues", "0004_populate_dev_queue_alias_flags"),
    ]

    operations = [
        migrations.RunPython(add_combine_and_review_queue, migrations.RunPython.noop),
    ]
