# Generated by Django 3.2.11 on 2022-01-27 09:48

from django.db import migrations


def populate_queue_alias(apps, schema_editor):
    LU_PRE_CIRC_PK = "4dfc0d0b-c0c0-4f59-897b-b7d596bed930"  # /PS-IGNORE
    alias = "LU_PRE_CIRC_REVIEW"
    Queue = apps.get_model("queues", "Queue")
    pre_circ_queue = Queue.objects.filter(pk=LU_PRE_CIRC_PK)
    if pre_circ_queue.exists():
        pre_circ_queue.update(alias=alias)


class Migration(migrations.Migration):

    dependencies = [
        ("queues", "0005_add_combine_and_review_queue"),
    ]

    operations = [
        migrations.RunPython(populate_queue_alias, migrations.RunPython.noop),
    ]
