# Generated by Django 3.2.11 on 2022-02-21 17:48

from django.db import migrations


def populate_lu_queue_alias(apps, schema_editor):
    LU_LICENSING_MANAGER_QUEUE = "9f5a2a93-03ed-4416-a8f8-8b728e5ea9d0"  # /PS-IGNORE
    LU_SR_LICENSING_MANAGER_QUEUE = "7b643901-565a-4ec8-8a7a-de34bc541a0e"  # /PS-IGNORE

    Queue = apps.get_model("queues", "Queue")

    licensing_mgr_queue = Queue.objects.filter(pk=LU_LICENSING_MANAGER_QUEUE)
    if licensing_mgr_queue.exists():
        licensing_mgr_queue.update(alias="LU_LICENSING_MANAGER_QUEUE")

    sr_licensing_mgr_queue = Queue.objects.filter(pk=LU_SR_LICENSING_MANAGER_QUEUE)
    if sr_licensing_mgr_queue.exists():
        sr_licensing_mgr_queue.update(alias="LU_SR_LICENSING_MANAGER_QUEUE")


class Migration(migrations.Migration):

    dependencies = [
        ("queues", "0006_populate_pre_circ_queue_alias"),
    ]

    operations = [
        migrations.RunPython(populate_lu_queue_alias, migrations.RunPython.noop),
    ]
