# Generated by Django 2.2.4 on 2019-08-07 13:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0002_case_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcjuQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=5000)),
                ('response', models.CharField(max_length=5000, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_ecju_query', to='cases.Case')),
            ],
        ),
    ]
