# Generated by Django 2.2.17 on 2021-01-06 15:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0014_auto_20200907_1234"),
    ]

    operations = [
        migrations.CreateModel(
            name="Denial",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created_at"
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="updated_at"
                    ),
                ),
                ("denied_name", models.TextField(help_text="The name of the person being denied")),
                ("authority", models.TextField(help_text="The organisation that denied the person")),
                ("data", django.contrib.postgres.fields.jsonb.JSONField()),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="denials_created", to="users.GovUser"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
