# Generated by Django 2.2.17 on 2021-01-11 16:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("external_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="denial",
            name="is_revoked",
            field=models.BooleanField(default=False, help_text="If true do not include in search results"),
        ),
        migrations.RemoveField(model_name="denial", name="id",),
        migrations.AddField(
            model_name="denial",
            name="id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
