# Generated by Django 2.2.17 on 2021-01-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("external_data", "0002_auto_20210111_1659"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="denial",
            name="authority",
        ),
        migrations.RemoveField(
            model_name="denial",
            name="denied_name",
        ),
        migrations.AddField(
            model_name="denial",
            name="address",
            field=models.TextField(default="", help_text="The address of the individual/organization being denied"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="denial",
            name="name",
            field=models.TextField(default="", help_text="The name of the individual/organization being denied"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="denial",
            name="reference",
            field=models.TextField(
                default="", help_text="The reference code assigned by the authority that created the denial"
            ),
            preserve_default=False,
        ),
    ]
