# Generated by Django 2.2.17 on 2021-01-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("external_data", "0005_auto_20210115_1310"),
    ]

    operations = [
        migrations.AddField(
            model_name="denial",
            name="consignee_name",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="denial",
            name="final_destination",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="denial",
            name="item_description",
            field=models.TextField(default="", verbose_name="The description of the item being denied"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="denial",
            name="item_list_codes",
            field=models.TextField(default="", verbose_name="The codes of the items being denied"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="denial",
            name="notifying_government",
            field=models.TextField(default="", help_text="The authority that raised the denial"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="denial",
            name="reference",
            field=models.TextField(help_text="The reference assigned by the notifying government", unique=True),
        ),
    ]
