# Generated by Django 2.2.17 on 2021-01-27 14:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0045_remove_denialmatchonapplication_denial"),
        ("external_data", "0007_denial_end_use"),
    ]

    operations = [
        migrations.CreateModel(
            name="SanctionMatch",
            fields=[
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created_at"
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="updated_at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("elasticsearch_reference", models.TextField()),
                (
                    "party_on_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sanction_matches",
                        to="applications.PartyOnApplication",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
