# Generated by Django 2.2.17 on 2021-01-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("external_data", "0008_sanctionmatch"),
    ]

    operations = [
        migrations.AddField(
            model_name="sanctionmatch",
            name="is_revoked",
            field=models.BooleanField(default=False, help_text="If true do not include in search results"),
        ),
        migrations.AddField(
            model_name="sanctionmatch",
            name="is_revoked_comment",
            field=models.TextField(default=""),
        ),
    ]
