# Generated by Django 2.2.17 on 2021-01-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("external_data", "0009_auto_20210129_1134"),
    ]

    operations = [
        migrations.AddField(
            model_name="sanctionmatch", name="list_name", field=models.TextField(default=""), preserve_default=False,
        ),
        migrations.AddField(
            model_name="sanctionmatch", name="name", field=models.TextField(default=""), preserve_default=False,
        ),
    ]
