# Generated by Django 2.2.17 on 2021-01-29 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("external_data", "0010_auto_20210129_1308"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sanctionmatch",
            old_name="list_name",
            new_name="flag_uuid",
        ),
    ]
