# Generated by Django 3.2.15 on 2022-10-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("external_data", "0012_auto_20210222_1115"),
    ]

    operations = [
        migrations.AlterField(
            model_name="denial",
            name="reference",
            field=models.TextField(help_text="The reference assigned by the notifying government"),
        ),
    ]
