# Generated by Django 3.2.15 on 2022-10-07 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("external_data", "0013_alter_denial_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="denial",
            name="address",
            field=models.TextField(
                blank=True, default="", help_text="The address of the individual/organization being denied", null=True
            ),
        ),
        migrations.AlterField(
            model_name="denial",
            name="consignee_name",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="denial",
            name="end_use",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="denial",
            name="final_destination",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="denial",
            name="item_description",
            field=models.TextField(
                blank=True, default="", verbose_name="The description of the item being denied", null=True
            ),
        ),
        migrations.AlterField(
            model_name="denial",
            name="item_list_codes",
            field=models.TextField(
                blank=True, default="", verbose_name="The codes of the items being denied", null=True
            ),
        ),
        migrations.AlterField(
            model_name="denial",
            name="name",
            field=models.TextField(
                blank=True, default="", help_text="The name of the individual/organization being denied", null=True
            ),
        ),
        migrations.AlterField(
            model_name="denial",
            name="notifying_government",
            field=models.TextField(blank=True, default="", help_text="The authority that raised the denial", null=True),
        ),
    ]
