# Generated by Django 3.1.8 on 2022-10-10 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('external_data', '0014_auto_20221007_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='denial',
            old_name='final_destination',
            new_name='country',
        ),
    ]
