# Generated by Django 3.2.15 on 2022-10-10 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_exporteruser_external_id"),
        ("external_data", "0015_auto_20221010_1228"),
    ]

    operations = [
        migrations.AlterField(
            model_name="denial",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="denials_created",
                to="users.govuser",
            ),
        ),
    ]
