# Generated by Django 3.2.15 on 2022-10-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("external_data", "0016_alter_denial_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="denial",
            name="regime_reg_ref",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
