# Generated by Django 3.2.23 on 2023-11-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_data', '0017_denial_regime_reg_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='denial',
            name='reason_for_refusal',
            field=models.TextField(blank=True, default='', help_text='The reason for denial'),
        ),
    ]
