# Generated by Django 3.2.23 on 2023-11-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_data', '0017_denial_regime_reg_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='denial',
            name='reason_for_refusal',
            field=models.TextField(blank=True, default='', null=True, help_text='Reason why the denial was refused'),
        ),
        migrations.AddField(
            model_name='denial',
            name='spire_entity_id',
            field=models.IntegerField(help_text='Entity_id from spire for matching data', null=True),
        ),
    ]
