# Generated by Django 4.2.10 on 2024-03-21 16:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_userorganisationrelationship_user"),
        ("external_data", "0018_auto_20231109_1425"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewDenial",
            fields=[
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created_at"
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="updated_at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "reference",
                    models.TextField(help_text="The reference assigned by the notifying government"),
                ),
                ("regime_reg_ref", models.TextField(unique=True, blank=False)),
                (
                    "notifying_government",
                    models.TextField(
                        help_text="The authority that raised the denial", null=True
                    ),
                ),
                (
                    "item_list_codes",
                    models.TextField(
                        null=True, verbose_name="The codes of the items being denied"
                    ),
                ),
                (
                    "item_description",
                    models.TextField(
                       null=True, verbose_name="The description of the item being denied"
                    ),
                ),
                ("end_use", models.TextField(null=True)),
                (
                    "is_revoked",
                    models.BooleanField(default=False, help_text="If true do not include in search results"),
                ),
                ("is_revoked_comment", models.TextField(default="")),
                (
                    "reason_for_refusal",
                    models.TextField(help_text="Reason why the denial was refused", null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="newdenials_created",
                        to="users.govuser",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DenialEntity",
            fields=[
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created_at"
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="updated_at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("type", models.TextField()),
                (
                    "name",
                    models.TextField(
                        help_text="The name of the individual/organization being denied",
                        null=True,
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        help_text="The address of the individual/organization being denied",
                        null=True,
                    ),
                ),
                ("country", models.TextField(null=True)),
                (
                    "denial_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="denial_entity",
                        to="external_data.newdenial",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
