# Generated by Django 4.2.10 on 2024-03-27 14:26
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0079_remove_openapplication_baseapplication_ptr_and_more"),
        ("users", "0006_alter_userorganisationrelationship_user"),
        ("external_data", "0018_auto_20231109_1425"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Denial",
            new_name="DenialEntity",
        ),
        migrations.AlterField(
            model_name="denialentity",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="denialenitity_created",
                to="users.govuser",
            ),
        ),
    ]
