# Generated by Django 4.2.10 on 2024-03-28 15:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_userorganisationrelationship_user"),
        ("external_data", "0019_rename_denial_denialentity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Denial",
            fields=[
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created_at"
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="updated_at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("reference", models.TextField(help_text="The reference assigned by the notifying government")),
                (
                    "regime_reg_ref",
                    models.TextField(help_text="The unique reference assigned by the issuing regime", unique=True),
                ),
                (
                    "notifying_government",
                    models.TextField(
                        blank=True, default="", help_text="The authority that raised the denial", null=True
                    ),
                ),
                (
                    "item_list_codes",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="The codes of the items being denied"
                    ),
                ),
                (
                    "item_description",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="The description of the item being denied"
                    ),
                ),
                ("end_use", models.TextField(blank=True, default="", null=True)),
                (
                    "is_revoked",
                    models.BooleanField(default=False, help_text="If true do not include in search results"),
                ),
                ("is_revoked_comment", models.TextField(blank=True, default="", null=True)),
                (
                    "reason_for_refusal",
                    models.TextField(blank=True, default="", help_text="Reason why the denial was refused", null=True),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="denial_created_by_user",
                        to="users.govuser",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
