# Generated by Django 4.2.10 on 2024-04-02 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("external_data", "0020_denial"),
    ]

    operations = [
        migrations.AddField(
            model_name="denialentity",
            name="denial",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="denial_entity",
                to="external_data.denial",
            ),
        ),
    ]
