# Generated by Django 4.2.11 on 2024-04-18 08:45

from django.db import migrations, models
from api.external_data.helpers import get_denial_entity_type


def set_denial_entity_type(apps):

    DenialEntity = apps.get_model("external_data", "DenialEntity")

    for denial_entity in DenialEntity.objects.all():
        denial_entity.entity_type = get_denial_entity_type(denial_entity.entity_type)
        denial_entity.save()


class Migration(migrations.Migration):

    dependencies = [
        ("external_data", "0021_denialentity_denial_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="denialentity",
            name="entity_type",
            field=models.TextField(
                blank=True,
                choices=[("consignee", "Consignee"), ("end_user", "End-user"), ("third_party", "Third party")],
                default="",
                help_text="Type of entity being denied",
                null=True,
            ),
        ),
        migrations.RunPython(set_denial_entity_type, migrations.RunPython.noop),
    ]
