# Generated by Django 4.2.11 on 2024-04-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("external_data", "0021_denialentity_denial_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="denialentity",
            name="entity_type",
            field=models.TextField(
                blank=True,
                choices=[("End-user", "End User"), ("Consignee", "Consignee"), ("Third-party", "Third Party")],
                default="",
                help_text="Type of entity being denied",
                null=True,
            ),
        ),
    ]
