# Generated by Django 4.2.11 on 2024-04-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("external_data", "0022_denialentity_entity_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="denialentity",
            name="entity_type",
            field=models.TextField(
                blank=True,
                choices=[("end_user", "End-user"), ("consignee", "Consignee"), ("third_party", "Third-party")],
                default="",
                help_text="Type of entity being denied",
                null=True,
            ),
        ),
    ]
