# Generated by Django 4.2.11 on 2024-04-18 12:00

from django.db import migrations
from api.external_data.helpers import get_denial_entity_type


def set_denial_entity_type(apps):

    DenialEntity = apps.get_model("external_data", "DenialEntity")

    for denial_entity in DenialEntity.objects.all():
        denial_entity.entity_type = get_denial_entity_type(denial_entity.entity_type)
        denial_entity.save()


class Migration(migrations.Migration):

    dependencies = [
        ("external_data", "0022_denialentity_entity_type"),
    ]

    operations = [migrations.RunPython(set_denial_entity_type, migrations.RunPython.noop)]
