# Generated by Django 4.2.13 on 2024-05-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("external_data", "0025_entity_type_empty_strings"),
    ]

    operations = [
        migrations.AddField(
            model_name="denialentity",
            name="denial_cle",
            field=models.TextField(blank=True, default="", null=True, verbose_name="Control list entry for denial"),
        ),
    ]
