# Generated by Django 4.2.13 on 2024-05-21 12:05

from django.db import migrations


def set_denial_cle(apps, schema_editor):

    DenialEntity = apps.get_model("external_data", "DenialEntity")

    for denial_entity in DenialEntity.objects.filter(denial_cle=""):
        denial_entity.denial_cle = denial_entity.denial.item_list_codes
        denial_entity.save()


class Migration(migrations.Migration):

    dependencies = [
        ("external_data", "0026_denialentity_denial_cle"),
    ]

    operations = [migrations.RunPython(set_denial_cle, migrations.RunPython.noop)]
