# Generated by Django 4.2.13 on 2024-05-29 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("external_data", "0026_rename_item_list_codes_to_denial_cle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="denialentity",
            name="consignee_name",
        ),
        migrations.RemoveField(
            model_name="denialentity",
            name="data",
        ),
        migrations.RemoveField(
            model_name="denialentity",
            name="denial_cle",
        ),
        migrations.RemoveField(
            model_name="denialentity",
            name="end_use",
        ),
        migrations.RemoveField(
            model_name="denialentity",
            name="is_revoked",
        ),
        migrations.RemoveField(
            model_name="denialentity",
            name="is_revoked_comment",
        ),
        migrations.RemoveField(
            model_name="denialentity",
            name="item_description",
        ),
        migrations.RemoveField(
            model_name="denialentity",
            name="notifying_government",
        ),
        migrations.RemoveField(
            model_name="denialentity",
            name="reason_for_refusal",
        ),
        migrations.RemoveField(
            model_name="denialentity",
            name="reference",
        ),
        migrations.RemoveField(
            model_name="denialentity",
            name="regime_reg_ref",
        ),
        migrations.RemoveField(
            model_name="denialentity",
            name="spire_entity_id",
        ),
        migrations.AlterField(
            model_name="denialentity",
            name="denial",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="denial_entity", to="external_data.denial"
            ),
        ),
    ]
