# Generated by Django 2.2.10 on 2020-02-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="clearance_level",
            field=models.CharField(
                choices=[
                    ("uk_unclassified", "UK unclassified"),
                    ("uk_official", "UK official"),
                    ("uk_official_sensitive", "UK official - sensitive"),
                    ("uk_secret", "UK secret"),
                    ("uk_top_secret", "UK top secret"),
                    ("nato_unclassified", "NATO unclassified"),
                    ("nato_confidential", "NATO confidential"),
                    ("nato_restricted", "NATO restricted"),
                    ("nato_secret", "NATO secret"),
                    ("occar_unclassified", "OCCAR unclassified"),
                    ("occar_confidential", "OCCAR confidential"),
                    ("occar_restricted", "OCCAR restricted"),
                    ("occar_secret", "OCCAR secret"),
                ],
                help_text="Only relevant to F680 applications",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="party",
            name="descriptors",
            field=models.CharField(help_text="Clearance descriptors, caveats and codewords", max_length=256, null=True),
        ),
    ]
