# Generated by Django 3.1.12 on 2021-11-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("parties", "0001_squashed_0011_party_signatory_name_euu")]

    operations = [
        migrations.AlterField(model_name="party", name="name", field=models.TextField(blank=True, default=""))
    ]
