# Generated by Django 3.1.12 on 2021-10-26 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_squashed_0011_party_signatory_name_euu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='copy_of',
        ),
    ]
