# Generated by Django 3.1.13 on 2021-11-26 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_add_document_fields"),
        ("parties", "0002_remove_name_length_limit"),
    ]

    operations = [
        migrations.CreateModel(
            name="EndUserTranslationDocument",
            fields=[
                (
                    "document_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="documents.document",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translation_documents",
                        to="parties.party",
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("documents.document",),
        ),
    ]
