# Generated by Django 3.1.8 on 2022-01-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0003_auto_20211221_1215"),
    ]

    operations = [
        migrations.AlterField(
            model_name="party",
            name="type",
            field=models.CharField(
                choices=[
                    ("consignee", "Consignee"),
                    ("end_user", "End-user"),
                    ("ultimate_end_user", "Ultimate end-user"),
                    ("third_party", "Third party"),
                    ("additional_contact", "Additional contact"),
                ],
                max_length=20,
            ),
        ),
    ]
