# Generated by Django 3.1.8 on 2022-03-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0004_auto_20220104_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='document_in_english',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='document_on_letterhead',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='end_user_document_available',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='end_user_document_missing_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
