# Generated by Django 2.2.11 on 2020-03-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0006_auto_20200311_1124"),
    ]

    operations = [
        migrations.AddField(model_name="party", name="details", field=models.TextField(blank=True, null=True),),
        migrations.AddField(
            model_name="party", name="email", field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="party", name="phone_number", field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="party",
            name="type",
            field=models.CharField(
                choices=[
                    ("consignee", "Consignee"),
                    ("end_user", "End user"),
                    ("ultimate_end_user", "Ultimate end user"),
                    ("third_party", "Third party"),
                    ("additional_contact", "Additional contact"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="party", name="website", field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
