# Generated by Django 3.1.8 on 2022-03-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0006_auto_20220307_1634"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="product_differences_note",
            field=models.TextField(blank=True, default=""),
        ),
    ]
