# Generated by Django 3.1.8 on 2022-03-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0007_party_product_differences_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="ec3_missing_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="partydocument",
            name="type",
            field=models.TextField(
                choices=[
                    ("supporting_document", "Supporting document"),
                    ("end_user_undertaking_document", "End-user undertaking or stockist undertaking document"),
                    ("end_user_english_translation_document", "English translation of end-user undertaking document"),
                    ("end_user_company_letterhead_document", "End-user document on company letterhead"),
                    ("end_user_ec3_document", "End-user EC3 document"),
                ],
                default="supporting_document",
            ),
        ),
    ]
