# Generated by Django 2.2.13 on 2020-06-26 09:53

from django.db import migrations, models


def reduce_field_length(apps, schema_editor):
    Party = apps.get_model("parties", "Party")

    for party in Party.objects.all():
        if party.name:
            party.name = party.name[:100]
        if party.address:
            party.address = party.address[:256]
        if party.details:
            party.details = party.details[:256]
        party.save()


def reverse_reduce_field_length(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0007_auto_20200317_1730"),
    ]

    operations = [migrations.RunPython(reduce_field_length, reverse_code=reverse_reduce_field_length)]
