# Generated by Django 3.2.16 on 2022-11-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0008_auto_20220317_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.TextField(blank=True, default='', max_length=80),
        ),
    ]
