# Generated by Django 4.2.11 on 2024-04-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0008_auto_20220317_0915"),
    ]

    operations = [
        migrations.AlterField(
            model_name="party",
            name="type",
            field=models.CharField(
                choices=[
                    ("consignee", "Consignee"),
                    ("end_user", "End-user"),
                    ("ultimate_end_user", "Ultimate end-user"),
                    ("third_party", "Third party"),
                    ("additional_contact", "Additional contact"),
                    ("open_destination", "Open destination"),
                ],
                max_length=20,
            ),
        ),
    ]
