# Generated by Django 2.2.2 on 2019-07-04 12:58

from django.db import migrations, models
import documents.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('file', documents.fields.S3FileField(max_length=1000, upload_to='')),
                ('size', models.IntegerField(blank=True, null=True)),
                ('virus_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('safe', models.NullBooleanField()),
                ('checksum', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
