# Generated by Django 2.2.10 on 2020-02-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="description",
            field=models.TextField(blank=True, default=None, max_length=280, null=True),
        ),
    ]
