# Generated by Django 2.2.12 on 2020-05-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document", name="virus_scan_attempts", field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
