# Generated by Django 2.2.10 on 2020-03-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    # Manually added dependencies on removing description from other document models
    dependencies = [
        ("documents", "0001_initial"),
        ("goods", "0007_remove_gooddocument_description"),
        ("goodstype", "0002_remove_goodstypedocument_description"),
        ("cases", "0007_auto_20200302_1118"),
        ("applications", "0009_remove_applicationdocument_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="description",
            field=models.TextField(blank=True, default=None, max_length=280, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="type",
            field=models.CharField(
                choices=[("UPLOADED", "Uploaded"), ("GENERATED", "Generated")], default="UPLOADED", max_length=100
            ),
        ),
    ]
