# Generated by Django 2.2.10 on 2020-02-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_document_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="type",
            field=models.CharField(
                choices=[("UPLOADED", "Uploaded"), ("GENERATED", "Generated")], default="UPLOADED", max_length=100
            ),
        ),
    ]
