# Generated by Django 2.2.4 on 2019-08-26 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
    ]
