# Generated by Django 2.1.7 on 2019-02-27 16:06

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exporter_id', models.TextField(default='')),
                ('control_code', models.CharField(default='', max_length=30)),
                ('activity', models.TextField(default='')),
                ('destination', models.TextField(default='')),
                ('usage', models.TextField(default='')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('last_modified_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
