# Generated by Django 2.2.13 on 2020-06-18 11:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import licences.enums
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0032_auto_20200612_0845'),
        ('licences', '0002_licence_decisions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licence',
            name='is_complete',
        ),
        migrations.AddField(
            model_name='licence',
            name='status',
            field=models.CharField(choices=[('ISSUED', 'issued'), ('REINSTATED', 'reinstated'), ('REVOKED', 'revoked'), ('DRAFT', 'draft')], default=licences.enums.LicenceStatus('draft'), max_length=32),
        ),
        migrations.CreateModel(
            name='GoodOnLicence',
            fields=[
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created_at')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='updated_at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usage', models.FloatField(default=0)),
                ('quantity', models.FloatField(blank=True, default=None, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=256, null=True)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.GoodOnApplication')),
                ('licence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='licences.Licence')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
