# Generated by Django 2.2.13 on 2020-06-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licences", "0002_licence_decisions"),
    ]

    operations = [
        migrations.AddField(model_name="licence", name="sent_at", field=models.DateTimeField(blank=True, null=True),),
    ]
