# Generated by Django 2.2.13 on 2020-06-10 12:24

from django.db import migrations, models
import uuid


def set_licence_reference(apps, schema_editor):
    Licence = apps.get_model("licence", "Licence")
    for licence in Licence.objects.all():
        if not licence.reference_code:
            licence.reference_code = licence.application.reference_code
            licence.save()


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0003_licence_reference_code'),
    ]

    operations = [
        migrations.RunPython(set_licence_reference),
    ]
