# Generated by Django 2.2.13 on 2020-06-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0004_auto_20200618_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='status',
            field=models.CharField(default='draft', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='licence',
            constraint=models.CheckConstraint(check=models.Q(status__in=['issued', 'reinstated', 'revoked', 'draft']), name='status_choices'),
        ),
    ]
