# Generated by Django 2.2.13 on 2020-06-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licences", "0004_auto_20200616_0836"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licence",
            name="reference_code",
            field=models.CharField(editable=False, max_length=30, unique=True),
        ),
    ]
