# Generated by Django 2.2.13 on 2020-07-02 13:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0034_auto_20200622_0835"),
        ("licences", "0006_licence_sent_at"),
    ]

    operations = [
        migrations.AlterModelOptions(name="licence", options={"ordering": ("-created_at",)},),
        migrations.RemoveField(model_name="licence", name="is_complete",),
        migrations.AddField(
            model_name="licence",
            name="status",
            field=models.CharField(
                choices=[
                    ("issued", "Issued"),
                    ("reinstated", "Reinstated"),
                    ("revoked", "Revoked"),
                    ("surrendered", "Surrendered"),
                    ("draft", "Draft"),
                    ("cancelled", "Cancelled"),
                    ("refused", "Refused"),
                ],
                default="draft",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="licence", name="duration", field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(model_name="licence", name="start_date", field=models.DateField(null=True),),
        migrations.CreateModel(
            name="GoodOnLicence",
            fields=[
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created_at"
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="updated_at"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("usage", models.FloatField(default=0)),
                ("quantity", models.FloatField(blank=True, default=None, null=True)),
                ("value", models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=15, null=True)),
                (
                    "good",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licence",
                        to="applications.GoodOnApplication",
                    ),
                ),
                (
                    "licence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goods",
                        related_query_name="goods",
                        to="licences.Licence",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
