# Generated by Django 2.2.13 on 2020-06-23 17:01

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0033_auto_20200612_1342"),
        ("licences", "0006_licence_sent_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsageTransaction",
            fields=[
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created_at"
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="updated_at"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "goods",
                    models.ManyToManyField(related_name="usage_transactions", to="applications.GoodOnApplication"),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
