# Generated by Django 2.2.13 on 2020-06-23 18:31

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("licences", "0006_licence_sent_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="HMRCIntegrationUpdateTransaction",
            fields=[
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created_at"
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="updated_at"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={"abstract": False,},
        ),
        migrations.AddField(
            model_name="licence",
            name="hmrc_integration_update_transactions",
            field=models.ManyToManyField(related_name="licences", to="licences.HMRCIntegrationUpdateTransaction"),
        ),
    ]
