# Generated by Django 2.2.13 on 2020-06-22 17:29

from django.db import migrations, models
import django.db.models.deletion
import licences.enums


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0007_auto_20200622_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodonlicence',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licence', to='applications.GoodOnApplication'),
        ),
        migrations.AlterField(
            model_name='licence',
            name='status',
            field=models.CharField(choices=[('issued', licences.enums.LicenceStatus('issued')), ('reinstated', licences.enums.LicenceStatus('reinstated')), ('revoked', licences.enums.LicenceStatus('revoked')), ('surrendered', licences.enums.LicenceStatus('surrendered')), ('draft', licences.enums.LicenceStatus('draft'))], default=licences.enums.LicenceStatus('draft'), max_length=32),
        ),
    ]
