# Generated by Django 2.2.13 on 2020-06-23 07:31

from django.db import migrations, models
import licences.enums


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0008_auto_20200622_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='status',
            field=models.CharField(choices=[('issued', licences.enums.LicenceStatus('issued')), ('reinstated', licences.enums.LicenceStatus('reinstated')), ('revoked', licences.enums.LicenceStatus('revoked')), ('surrendered', licences.enums.LicenceStatus('surrendered')), ('draft', licences.enums.LicenceStatus('draft'))], default='draft', max_length=32),
        ),
    ]
