# Generated by Django 2.2.13 on 2020-07-03 09:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("licences", "0009_licence_remove_is_complete"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoodOnLicence",
            fields=[
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created_at"
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="updated_at"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("usage", models.FloatField(default=0)),
                ("quantity", models.FloatField()),
                ("value", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "good",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licence",
                        to="applications.GoodOnApplication",
                    ),
                ),
                (
                    "licence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goods",
                        related_query_name="goods",
                        to="licences.Licence",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
