# Generated by Django 2.2.13 on 2020-06-30 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0009_auto_20200629_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licence',
            options={'ordering': ('-created_at',)},
        ),
    ]
