# Generated by Django 2.2.13 on 2020-07-15 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("licences", "0013_auto_20200709_1520"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licence",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="licences", to="cases.Case"
            ),
        ),
    ]
