# Generated by Django 2.2.13 on 2020-07-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0013_auto_20200709_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='status',
            field=models.CharField(choices=[('issued', 'Issued'), ('issued', 'Issued'), ('reinstated', 'Reinstated'), ('revoked', 'Revoked'), ('surrendered', 'Surrendered'), ('exhausted', 'Exhausted'), ('expired', 'Expired'), ('draft', 'Draft'), ('cancelled', 'Cancelled')], default='draft', max_length=32),
        ),
    ]
