# Generated by Django 2.2.13 on 2020-07-16 08:30

from django.db import migrations, models

from conf.helpers import add_months


def migrate(apps, schema_editor):
    Licence = apps.get_model("licences", "Licence")
    licences = Licence.objects.all()

    for licence in licences:
        licence.end_date = add_months(licence.start_date, licence.duration, "%Y-%m-%d")
        licence.save()


def reverse_migrate(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("licences", "0014_auto_20200715_1424"),
    ]

    operations = [
        migrations.AddField(model_name="licence", name="end_date", field=models.DateField(null=True)),
        migrations.RunPython(migrate, reverse_migrate),
        migrations.AlterField(model_name="licence", name="end_date", field=models.DateField(blank=False, null=False)),
    ]
