# Generated by Django 2.2.9 on 2020-01-24 15:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Good",
            fields=[
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created_at"
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="updated_at"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("description", models.TextField(max_length=280)),
                (
                    "is_good_controlled",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No"), ("unsure", "I don't know")],
                        default="unsure",
                        max_length=20,
                    ),
                ),
                ("control_code", models.TextField(blank=True, default="", null=True)),
                ("part_number", models.TextField(blank=True, default="", null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("clc_query", "Control List Classification Query"),
                            ("verified", "Verified"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "missing_document_reason",
                    models.CharField(
                        choices=[
                            ("NO_DOCUMENT", "No document available for the product"),
                            ("OFFICIAL_SENSITIVE", "Document is above official-sensitive"),
                            ("COMMERCIALLY_SENSITIVE", "Document is commercially sensitive"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("comment", models.TextField(blank=True, default=None, null=True)),
                ("report_summary", models.TextField(blank=True, default=None, null=True)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="GoodDocument",
            fields=[
                (
                    "document_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="documents.Document",
                    ),
                ),
                ("description", models.TextField(blank=True, default=None, max_length=280, null=True)),
                ("good", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="goods.Good")),
            ],
            options={"abstract": False,},
            bases=("documents.document",),
        ),
    ]
