# Generated by Django 2.2.2 on 2019-06-28 10:21

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, default=None, max_length=280, null=True)),
                ('is_good_controlled', models.BooleanField(blank=True, default=None, null=True)),
                ('control_code', models.TextField(blank=True, default=None, null=True)),
                ('is_good_end_product', models.BooleanField(blank=True, default=None, null=True)),
                ('part_number', models.TextField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('submitted', 'submitted')], default='draft', max_length=20)),
            ],
        ),
    ]
