# Generated by Django 2.2.4 on 2019-09-10 12:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_auto_20190819_1523'),
        ('documents', '0001_initial'),
        ('organisations', '0001_initial'),
        ('flags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, default=None, max_length=280, null=True)),
                ('is_good_controlled', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unsure', "I don't know")], default='unsure', max_length=20)),
                ('control_code', models.TextField(blank=True, default=None, null=True)),
                ('is_good_end_product', models.BooleanField(blank=True, default=None, null=True)),
                ('part_number', models.TextField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('clc_query', 'Control List Classification Query'), ('verified', 'Verified')], default='draft', max_length=20)),
                ('flags', models.ManyToManyField(related_name='goods', to='flags.Flag')),
                ('organisation', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation')),
            ],
        ),
        migrations.CreateModel(
            name='GoodDocument',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.Document')),
                ('description', models.TextField(blank=True, default=None, max_length=280, null=True)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Good')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organisations.Organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.ExporterUser')),
            ],
            bases=('documents.document',),
        ),
    ]
