# Generated by Django 2.2.4 on 2019-12-05 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("organisations", "0001_initial"),
        ("goods", "0001_initial"),
        ("flags", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gooddocument",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="users.ExporterUser"),
        ),
        migrations.AddField(
            model_name="good", name="flags", field=models.ManyToManyField(related_name="goods", to="flags.Flag"),
        ),
        migrations.AddField(
            model_name="good",
            name="organisation",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="organisations.Organisation"),
        ),
    ]
