# Generated by Django 2.2 on 2019-04-18 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='organisation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation'),
        ),
        migrations.AlterField(
            model_name='good',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=280, null=True),
        ),
    ]
