# Generated by Django 2.2.4 on 2019-10-01 16:03

from django.db import migrations, models

from goods.models import Good
from queries.control_list_classifications.models import ControlListClassificationQuery


def forwards_func(apps, schema_editor):
    ControlListClassificationQuery = apps.get_model("control_list_classifications", "ControlListClassificationQuery")
    for clc in ControlListClassificationQuery.objects.all():
        good = Good.objects.get(pk=clc.good.pk)
        good.comment = clc.comment
        good.report_summary = clc.report_summary
        good.save()


def backwards_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
        ('control_list_classifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='good',
            name='report_summary',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.RunPython(forwards_func, backwards_func)
    ]
