# Generated by Django 2.2.2 on 2019-06-28 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='organisation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation'),
        ),
    ]
