# Generated by Django 2.2.4 on 2019-10-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='good',
            name='report_summary',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
