# Generated by Django 2.2.4 on 2019-11-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20191001_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='control_code',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='part_number',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
