# Generated by Django 2.2.3 on 2019-08-07 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
        ('users', '0003_auto_20190724_1334'),
        ('documents', '0001_initial'),
        ('goods', '0002_good_organisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodDocument',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.Document')),
                ('description', models.TextField(blank=True, default=None, max_length=280, null=True)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Good')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ExporterUser')),
            ],
            bases=('documents.document',),
        ),
    ]
