# Generated by Django 2.2 on 2019-06-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190418_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('submitted', 'submitted')], default='draft', max_length=20),
        ),
    ]
