# Generated by Django 2.2.4 on 2019-12-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0002_auto_20191209_1209"),
    ]

    operations = [
        migrations.AddField(
            model_name="good", name="pv_grading_comment", field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="good", name="pv_grading_date_of_issue", field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="good",
            name="pv_grading_issuing_authority",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="good", name="pv_grading_prefix", field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="good", name="pv_grading_reference", field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="good", name="pv_grading_suffix", field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="good",
            name="holds_pv_grading",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No"), ("grading_required", "Good needs to be graded")],
                default="grading_required",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="good",
            name="pv_grading",
            field=models.CharField(
                blank=True,
                choices=[
                    ("other", "Other"),
                    ("uk_unclassified", "UK unclassified"),
                    ("uk_official", "UK official"),
                    ("uk_official_sensitive", "UK official - sensitive"),
                    ("uk_secret", "UK secret"),
                    ("uk_top_secret", "UK top secret"),
                    ("nato_unclassified", "NATO unclassified"),
                    ("nato_confidential", "NATO confidential"),
                    ("nato_restricted", "NATO restricted"),
                    ("nato_secret", "NATO secret"),
                    ("occar_unclassified", "OCCAR unclassified"),
                    ("occar_confidential", "OCCAR confidential"),
                    ("occar_restricted", "OCCAR restricted"),
                    ("occar_secret", "OCCAR secret"),
                ],
                default=None,
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="good", name="pv_grading_custom", field=models.TextField(blank=True, default="", null=True),
        ),
    ]
