# Generated by Django 2.2.8 on 2019-12-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0003_good_missing_document_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="good",
            name="missing_document_reason",
            field=models.CharField(
                choices=[
                    ("NO_DOCUMENT", "No document available for the product"),
                    ("OFFICIAL_SENSITIVE", "Document is above official-sensitive"),
                    ("COMMERCIALLY_SENSITIVE", "Document is commercially sensitive"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
