# Generated by Django 2.2.2 on 2019-07-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_good_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='is_good_controlled',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unsure', "I don't know")], default='unsure', max_length=20),
        ),
    ]
