# Generated by Django 2.2.4 on 2019-08-19 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_gooddocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gooddocument',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organisations.Organisation'),
        ),
        migrations.AlterField(
            model_name='gooddocument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.ExporterUser'),
        ),
    ]
