# Generated by Django 2.2.4 on 2019-08-22 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20190819_1522'),
        ('goods', '0004_auto_20190821_1034'),
    ]

    operations = [
    ]
