# Generated by Django 2.2.4 on 2019-08-26 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20190821_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gooddocument',
            name='description',
        ),
    ]
