# Generated by Django 2.2.2 on 2019-07-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20190702_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('submitted', 'submitted'), ('clcquery', 'clcquery')], default='draft', max_length=20),
        ),
    ]
