# Generated by Django 2.2.4 on 2019-08-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0001_initial'),
        ('goods', '0004_auto_20190821_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='flags',
            field=models.ManyToManyField(related_name='goods', to='flags.Flag'),
        ),
    ]
