# Generated by Django 2.2.8 on 2019-12-20 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20191218_1731'),
        ('goods', '0004_auto_20191218_1029'),
    ]

    operations = [
    ]
