# Generated by Django 2.2.8 on 2020-01-07 11:36

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0005_merge_20191220_1432"),
    ]

    operations = [
        migrations.RemoveField(model_name="good", name="created",),
        migrations.RemoveField(model_name="good", name="modified",),
        migrations.AddField(
            model_name="good",
            name="created_at",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now, editable=False, verbose_name="created_at"
            ),
        ),
        migrations.AddField(
            model_name="good",
            name="updated_at",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now, editable=False, verbose_name="updated_at"
            ),
        ),
    ]
