# Generated by Django 2.2.8 on 2020-01-07 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_merge_20191220_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='is_good_end_product',
        ),
    ]
