# Generated by Django 2.2.3 on 2019-07-05 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_good_organisation'),
        ('goods', '0005_auto_20190702_1259'),
    ]

    operations = [
    ]
