# Generated by Django 2.2.8 on 2020-01-09 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0006_timestampable"),
    ]

    operations = [
        migrations.RemoveField(model_name="good", name="is_good_end_product",),
    ]
