# Generated by Django 2.2.10 on 2020-02-28 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0006_auto_20200226_1218"),
    ]

    operations = [
        migrations.RemoveField(model_name="gooddocument", name="description",),
    ]
