# Generated by Django 2.2.4 on 2019-08-28 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_merge_20190822_1332'),
        ('goods', '0005_good_flags'),
    ]

    operations = [
    ]
