# Generated by Django 2.2.4 on 2019-09-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_merge_20190828_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('clcquery', 'Control List Classification Query'), ('final', 'Final')], default='draft', max_length=20),
        ),
    ]
