# Generated by Django 2.2.11 on 2020-04-16 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0007_auto_20200303_1516"),
    ]

    operations = [
        migrations.RenameField(model_name="good", old_name="control_code", new_name="control_list_entry",),
        migrations.AlterModelTable(name="good", table="good",),
    ]
