# Generated by Django 2.2.12 on 2020-04-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_list_entries', '0001_initial'),
        ('goods', '0007_auto_20200303_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='control_code',
        ),
        migrations.AddField(
            model_name='good',
            name='control_code',
            field=models.ManyToManyField(related_name='goods', to='control_list_entries.ControlListEntry'),
        ),
    ]
