# Generated by Django 2.2.8 on 2020-01-14 13:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0007_remove_good_is_good_end_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="PvGradingDetails",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("other", "Other"),
                            ("uk_unclassified", "UK unclassified"),
                            ("uk_official", "UK official"),
                            ("uk_official_sensitive", "UK official - sensitive"),
                            ("uk_secret", "UK secret"),
                            ("uk_top_secret", "UK top secret"),
                            ("nato_unclassified", "NATO unclassified"),
                            ("nato_confidential", "NATO confidential"),
                            ("nato_restricted", "NATO restricted"),
                            ("nato_secret", "NATO secret"),
                            ("occar_unclassified", "OCCAR unclassified"),
                            ("occar_confidential", "OCCAR confidential"),
                            ("occar_restricted", "OCCAR restricted"),
                            ("occar_secret", "OCCAR secret"),
                        ],
                        default=None,
                        max_length=30,
                        null=True,
                    ),
                ),
                ("custom_grading", models.TextField(blank=True, default="", null=True)),
                ("prefix", models.TextField(blank=True, default="", null=True)),
                ("suffix", models.TextField(blank=True, default="", null=True)),
                ("issuing_authority", models.TextField(blank=True, default="", null=True)),
                ("reference", models.TextField(blank=True, default="", null=True)),
                ("date_of_issue", models.DateField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, default="", null=True)),
            ],
        ),
        migrations.AddField(
            model_name="good",
            name="is_pv_graded",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No"), ("grading_required", "Good needs to be graded")],
                default="grading_required",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="good",
            name="pv_grading_details",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="goods.PvGradingDetails",
            ),
        ),
    ]
