# Generated by Django 2.2.8 on 2020-01-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0008_auto_20200114_1329"),
    ]

    operations = [
        migrations.AlterField(
            model_name="good",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("query", "Goods Query"),
                    ("verified", "Verified"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
