# Generated by Django 2.2.8 on 2020-01-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0008_auto_20200114_1329"),
    ]

    operations = [
        migrations.AlterField(
            model_name="good",
            name="missing_document_reason",
            field=models.CharField(
                choices=[
                    ("NO_DOCUMENT", "No document available for the product"),
                    ("OFFICIAL_SENSITIVE", "Document is above official-sensitive"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
