# Generated by Django 2.2.8 on 2020-01-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0009_auto_20200124_1227"),
    ]

    operations = [
        migrations.AddField(
            model_name="good", name="Grading_comment", field=models.TextField(blank=True, default="", null=True),
        ),
    ]
