# Generated by Django 2.2.8 on 2020-01-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0009_auto_20200124_1227"),
    ]

    operations = [
        migrations.AddField(
            model_name="good",
            name="grading_comment",
            field=models.TextField(blank=True, default=None, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="good",
            name="comment",
            field=models.TextField(blank=True, default=None, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="good",
            name="control_code",
            field=models.CharField(blank=True, default="", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="good",
            name="part_number",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="good",
            name="report_summary",
            field=models.TextField(blank=True, default=None, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="pvgradingdetails",
            name="issuing_authority",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="pvgradingdetails", name="prefix", field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="pvgradingdetails",
            name="reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="pvgradingdetails", name="suffix", field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
