# Generated by Django 2.2.11 on 2020-04-20 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0009_auto_20200416_0859"),
    ]

    operations = [
        migrations.AlterModelOptions(name="good", options={"ordering": ["-created_at"]},),
    ]
