# Generated by Django 2.2.8 on 2020-01-28 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0010_good_grading_comment"),
    ]

    operations = [
        migrations.RenameField(model_name="good", old_name="Grading_comment", new_name="grading_comment",),
    ]
