# Generated by Django 2.2.13 on 2020-06-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0010_auto_20200420_1430"),
    ]

    operations = [
        migrations.AddField(
            model_name="good",
            name="component_details",
            field=models.TextField(blank=True, default=None, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="good",
            name="information_security_details",
            field=models.TextField(blank=True, default=None, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="good",
            name="is_component",
            field=models.CharField(
                choices=[
                    ("yes_designed", "Yes, it's designed specially for hardware"),
                    ("yes_modified", "Yes, it's been modified for hardware"),
                    ("yes_general", "Yes, it's a general purpose component"),
                    ("no", "No"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="good",
            name="is_military_use",
            field=models.CharField(
                choices=[
                    ("yes_designed", "Yes, designed specifically for military use"),
                    ("yes_modified", "Yes, modified for military use"),
                    ("no", "No"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="good",
            name="item_category",
            field=models.CharField(
                choices=[
                    ("group1_platform", "Platform, vehicle, system or machine"),
                    ("group1_device", "Device, equipment or object"),
                    ("group1_components", "Components, modules or accessories of something"),
                    ("group1_materials", "Materials or substances"),
                    ("group2_firearms", "Firearms"),
                    ("group3_software", "Software"),
                    ("group3_technology", "Technology"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="good",
            name="modified_military_use_details",
            field=models.TextField(blank=True, default=None, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="good", name="uses_information_security", field=models.BooleanField(default=None, null=True),
        ),
    ]
