# Generated by Django 2.2.13 on 2020-06-22 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_auto_20200619_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirearmGoodDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('firearms', 'Firearms'), ('components_for_firearms', 'Components for firearms'), ('ammunition', 'Ammunition'), ('components_for_ammunition', 'Components for ammunition')], max_length=25, null=True)),
                ('year_of_manufacture', models.PositiveSmallIntegerField(null=True)),
                ('calibre', models.TextField(blank=True, default=None, max_length=2000, null=True)),
                ('is_covered_by_firearm_act_section_one_two_or_five', models.BooleanField(default=None, null=True)),
                ('section_certificate_number', models.CharField(max_length=20, null=True)),
                ('section_certificate_date_of_expiry', models.DateField(blank=True, null=True)),
                ('has_identification_markings', models.BooleanField(default=None, null=True)),
                ('identification_markings_details', models.TextField(blank=True, default=None, max_length=2000, null=True)),
                ('no_identification_markings_details', models.TextField(blank=True, default=None, max_length=2000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='good',
            name='firearm_details',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.FirearmGoodDetails'),
        ),
    ]
