# Generated by Django 2.2.13 on 2020-06-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0011_auto_20200619_1449"),
    ]

    operations = [
        migrations.AddField(
            model_name="good",
            name="software_or_technology_details",
            field=models.TextField(blank=True, default=None, max_length=2000, null=True),
        ),
    ]
