# Generated by Django 2.2.13 on 2020-07-02 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0013_auto_20200625_0753"),
    ]

    operations = [
        migrations.CreateModel(
            name="FirearmGoodDetails",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("firearms", "Firearms"),
                            ("components_for_firearms", "Components for firearms"),
                            ("ammunition", "Ammunition"),
                            ("components_for_ammunition", "Components for ammunition"),
                        ],
                        max_length=25,
                    ),
                ),
                ("year_of_manufacture", models.PositiveSmallIntegerField()),
                ("calibre", models.TextField(max_length=15)),
                ("is_covered_by_firearm_act_section_one_two_or_five", models.BooleanField()),
                ("section_certificate_number", models.CharField(blank=True, max_length=100, null=True)),
                ("section_certificate_date_of_expiry", models.DateField(blank=True, null=True)),
                ("has_identification_markings", models.BooleanField()),
                ("identification_markings_details", models.TextField(blank=True, max_length=2000, null=True)),
                ("no_identification_markings_details", models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="good",
            name="firearm_details",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="goods.FirearmGoodDetails",
            ),
        ),
    ]
