# Generated by Django 2.2.4 on 2019-09-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_list_classifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controllistclassificationquery',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='controllistclassificationquery',
            name='report_summary',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
