# Generated by Django 2.2.4 on 2019-09-10 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        ('control_list_classifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controllistclassificationquery',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='clc_query', to='goods.Good'),
        ),
    ]
