# Generated by Django 3.1.8 on 2021-08-09 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("control_list_entries", "0002_controllistentry_controlled"),
        ("goods", "0001_squashed_0028_auto_20210212_1151"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="GoodControlListEntry",
                    fields=[
                        (
                            "id",
                            models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                        ),
                        (
                            "controllistentry",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="controllistentries",
                                to="control_list_entries.controllistentry",
                            ),
                        ),
                        (
                            "good",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE, related_name="goods", to="goods.good"
                            ),
                        ),
                    ],
                    options={
                        "db_table": "good_control_list_entries",
                    },
                ),
                migrations.AlterField(
                    model_name="good",
                    name="control_list_entries",
                    field=models.ManyToManyField(
                        related_name="goods",
                        through="goods.GoodControlListEntry",
                        to="control_list_entries.ControlListEntry",
                    ),
                ),
            ]
        )
    ]
