# Generated by Django 3.1.12 on 2021-11-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("goods", "0002_auto_20210809_1557")]

    operations = [
        migrations.AddField(
            model_name="good",
            name="no_document_comments",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="Comments from applicant reasoning why no document is uploaded",
                null=True,
            ),
        )
    ]
