# Generated by Django 3.1.13 on 2021-11-18 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("goods", "0003_good_no_document_comments")]

    operations = [migrations.RemoveField(model_name="firearmgooddetails", name="is_sporting_shotgun")]
