# Generated by Django 3.1.8 on 2021-11-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0004_remove_firearmgooddetails_is_sporting_shotgun"),
    ]

    operations = [
        migrations.AddField(
            model_name="firearmgooddetails",
            name="no_serial_numbers_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="firearmgooddetails",
            name="serial_numbers_available",
            field=models.TextField(
                blank=True,
                choices=[
                    ("yes_available", "Yes, I can add serial numbers now"),
                    ("yes_later", "Yes, I can add serial numbers later"),
                    ("no", "No"),
                ],
                default="",
            ),
        ),
    ]
