# Generated by Django 2.2.10 on 2020-02-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0004_auto_20200212_1153"),
    ]

    operations = [
        migrations.AlterField(
            model_name="good",
            name="missing_document_reason",
            field=models.CharField(
                choices=[
                    ("NO_DOCUMENT", "No document available"),
                    ("OFFICIAL_SENSITIVE", "Document is above OFFICIAL-SENSITIVE"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
