# Generated by Django 3.2.12 on 2022-02-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0005_auto_20211125_2234"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="firearmgooddetails",
            name="no_serial_numbers_reason",
        ),
        migrations.AlterField(
            model_name="firearmgooddetails",
            name="serial_numbers_available",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AVAILABLE", "Yes, I can add serial numbers now"),
                    ("LATER", "Yes, I can add serial numbers later"),
                    ("NOT_AVAILABLE", "No"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
