# Generated by Django 3.2.12 on 2022-02-25 15:39

from django.db import migrations
from django.db.models import Case, Value, When


def synchronise_having_serial_number_columns(apps, schema_editor):
    FirearmGoodDetails = apps.get_model("goods", "FirearmGoodDetails")

    FirearmGoodDetails.objects.update(
        serial_numbers_available=Case(
            When(has_identification_markings=True, then=Value("AVAILABLE")),
            When(has_identification_markings=False, then=Value("NOT_AVAILABLE")),
        ),
    )


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0006_auto_20220225_1504"),
    ]

    operations = [
        migrations.RunPython(synchronise_having_serial_number_columns, migrations.RunPython.noop),
    ]
