# Generated by Django 3.2.12 on 2022-02-28 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0007_sync_serial_number_columns"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="firearmgooddetails",
            name="has_identification_markings",
        ),
    ]
