# Generated by Django 3.1.8 on 2022-04-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0011_firearmgooddetails_is_covered_by_firearm_act_section_one_two_or_five_explanation"),
    ]

    operations = [
        migrations.AddField(
            model_name="firearmgooddetails",
            name="is_made_before_1938",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
