# Generated by Django 2.2.13 on 2020-06-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0012_good_software_or_technology_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="good",
            name="is_military_use",
            field=models.CharField(
                choices=[
                    ("yes_designed", "Yes, specially designed for military use"),
                    ("yes_modified", "Yes, modified for military use"),
                    ("no", "No"),
                ],
                max_length=15,
                null=True,
            ),
        ),
    ]
