# Generated by Django 3.2.13 on 2022-04-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0013_alter_firearmgooddetails_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="firearmgooddetails",
            name="is_onward_altered_processed",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="firearmgooddetails",
            name="is_onward_altered_processed_comments",
            field=models.TextField(
                blank=True, default="", null=True, help_text="How the product will be processed or altered"
            ),
        ),
        migrations.AddField(
            model_name="firearmgooddetails",
            name="is_onward_exported",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="firearmgooddetails",
            name="is_onward_incorporated",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="firearmgooddetails",
            name="is_onward_incorporated_comments",
            field=models.TextField(
                blank=True, default="", null=True, help_text="what's being incorporated into the product"
            ),
        ),
    ]
