# Generated by Django 3.2.13 on 2022-04-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0014_auto_20220422_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='firearmgooddetails',
            name='not_deactivated_to_standard_comments',
            field=models.TextField(default=''),
        ),
    ]
