# Generated by Django 2.2.16 on 2020-09-25 10:05

from django.db import migrations, models


def nullify_is_good_controled(apps, schema_editor):
    Good = apps.get_model("goods", "Good")
    Good.objects.filter(is_good_controlled="unsure").update(is_good_controlled=None)


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0014_auto_20200702_1113"),
    ]

            migrations.RunPython(nullify_is_good_controled, migrations.RunPython.noop)
