# Generated by Django 3.2.12 on 2022-04-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0014_auto_20220422_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvgradingdetails',
            name='issuing_authority',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
