# Generated by Django 2.2.16 on 2020-11-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0015_auto_20200925_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='firearmgooddetails',
            name='serial_number',
            field=models.TextField(default=''),
        ),
    ]
