# Generated by Django 2.2.16 on 2020-11-23 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0015_auto_20200925_1105"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firearmgooddetails",
            name="type",
            field=models.TextField(
                choices=[
                    ("firearms", "Firearms"),
                    ("components_for_firearms", "Components for firearms"),
                    ("ammunition", "Ammunition"),
                    ("components_for_ammunition", "Components for ammunition"),
                    ("firearms_accessory", "Accessory of a firearm"),
                    ("software_related_to_firearms", "Software relating to a firearm"),
                    ("technology_related_to_firearms", "Technology relating to a firearm"),
                ],
            ),
        ),
        migrations.AlterField(model_name="firearmgooddetails", name="calibre", field=models.TextField(blank=True),),
        migrations.AlterField(
            model_name="firearmgooddetails",
            name="year_of_manufacture",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
