# Generated by Django 3.2.14 on 2022-08-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0016_firearmgooddetails_not_deactivated_to_standard_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="good",
            name="no_part_number_comments",
            field=models.TextField(
                blank=True, default="", help_text="Comments from applicant reasoning why part number is included"
            ),
        ),
    ]
