# Generated by Django 2.2.16 on 2020-11-27 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0016_auto_20201123_0332"),
        ("goods", "0017_auto_20201124_1613"),
    ]

    operations = []
