# Generated by Django 2.2.16 on 2020-11-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0018_merge_20201127_1102"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firearmgooddetails",
            name="no_proof_mark_details",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The reason why `has_proof_mark` is False (which should normally be True).",
            ),
        ),
    ]
