# Generated by Django 3.2.15 on 2022-08-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0019_good_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="good",
            name="item_category",
            field=models.CharField(
                choices=[
                    ("group1_platform", "Complete product"),
                    ("group1_device", "Device, equipment or object"),
                    ("group1_components", "Component, accessory or module"),
                    ("group1_materials", "Material or substance"),
                    ("group2_firearms", "Firearm"),
                    ("group3_software", "Software, information or technology"),
                    ("group3_technology", "Technology"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
