# Generated by Django 3.2.15 on 2022-09-30 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0020_alter_good_item_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="good",
            name="pv_grading_details",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="goods.pvgradingdetails",
            ),
        ),
    ]
