# Generated by Django 2.2.16 on 2020-11-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0020_auto_20201130_0142"),
    ]

    operations = [
        migrations.AddField(
            model_name="firearmgooddetails", name="date_of_deactivation", field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="firearmgooddetails", name="deactivation_standard", field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="firearmgooddetails", name="deactivation_standard_other", field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="firearmgooddetails",
            name="is_deactivated",
            field=models.BooleanField(help_text="Has the firearms been deactivated?", null=True),
        ),
    ]
