# Generated by Django 2.2.16 on 2020-12-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0020_auto_20201130_0142"),
    ]

    operations = [
        migrations.AddField(
            model_name="firearmgooddetails", name="is_replica", field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="firearmgooddetails", name="replica_description", field=models.TextField(blank=True, default=""),
        ),
    ]
