# Generated by Django 2.2.16 on 2020-12-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0021_auto_20201130_1614"),
    ]

    operations = [
        migrations.AddField(
            model_name="firearmgooddetails",
            name="is_deactivated_to_standard",
            field=models.BooleanField(help_text="Has the firearms been deactivated to UK/EU standards?", null=True),
        ),
    ]
