# Generated by Django 2.2.16 on 2020-12-02 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0022_firearmgooddetails_is_deactivated_to_standard"),
        ("goods", "0021_auto_20201201_1027"),
    ]

    operations = []
