# Generated by Django 3.2.16 on 2022-11-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0023_sync_onward_exported_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gooddocument',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
