# Generated by Django 3.2.16 on 2022-11-08 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0023_sync_onward_exported_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="firearmgooddetails",
            name="is_onward_altered_processed",
        ),
        migrations.RemoveField(
            model_name="firearmgooddetails",
            name="is_onward_altered_processed_comments",
        ),
        migrations.RemoveField(
            model_name="firearmgooddetails",
            name="is_onward_exported",
        ),
        migrations.RemoveField(
            model_name="firearmgooddetails",
            name="is_onward_incorporated",
        ),
        migrations.RemoveField(
            model_name="firearmgooddetails",
            name="is_onward_incorporated_comments",
        ),
    ]
