# Generated by Django 3.2.16 on 2022-11-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0024_auto_20221108_1050"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gooddocument",
            name="description",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
