# Generated by Django 3.2.16 on 2023-01-30 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("report_summaries", "0005_update_picklist_casing"),
        ("goods", "0025_alter_gooddocument_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="good",
            name="report_summary_prefix",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="report_summaries.reportsummaryprefix"
            ),
        ),
        migrations.AddField(
            model_name="good",
            name="report_summary_subject",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="report_summaries.reportsummarysubject"
            ),
        ),
    ]
