# Generated by Django 2.2.16 on 2021-02-06 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0026_auto_20210205_1408"),
    ]

    operations = [
        migrations.RemoveField(model_name="good", name="missing_document_reason",),
    ]
