# Generated by Django 4.2.9 on 2024-04-16 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0026_auto_20230201_1536"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="good",
            name="report_summary",
        ),
        migrations.RemoveField(
            model_name="good",
            name="report_summary_prefix",
        ),
        migrations.RemoveField(
            model_name="good",
            name="report_summary_subject",
        ),
    ]
