# Generated by Django 4.2.13 on 2024-06-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0026_auto_20230201_1536"),
    ]

    operations = [
        migrations.AddField(
            model_name="good",
            name="is_archived",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
