# Generated by Django 4.2.17 on 2025-01-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0027_good_is_archived"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="good",
            index=models.Index(fields=["created_at"], name="good_created_c8ec31_idx"),
        ),
    ]
