# Generated by Django 2.2.16 on 2021-02-12 11:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0027_remove_good_missing_document_reason"),
    ]

    operations = [
        migrations.RemoveField(model_name="firearmgooddetails", name="identification_markings_details",),
        migrations.AddField(
            model_name="firearmgooddetails",
            name="number_of_items",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="firearmgooddetails",
            name="serial_numbers",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(default=""), default=list, size=None
            ),
        ),
    ]
