# Generated by Django 2.2.11 on 2020-04-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decisions", "0001_initial"),
        ("licences", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="licence",
            name="decisions",
            field=models.ManyToManyField(related_name="licence", to="decisions.Decision"),
        ),
    ]
