# Generated by Django 2.2.13 on 2020-06-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licences", "0002_licence_decisions"),
    ]

    operations = [
        migrations.AddField(
            model_name="licence",
            name="reference_code",
            field=models.CharField(default=None, editable=False, max_length=30, null=True, unique=True),
        ),
    ]
