# Generated by Django 2.2.13 on 2020-06-16 08:36

from django.db import migrations

from api.licences.helpers import get_licence_reference_code


def set_licence_reference(apps, schema_editor):
    Licence = apps.get_model("licences", "Licence")
    for licence in Licence.objects.all():
        if not licence.reference_code:
            licence.reference_code = get_licence_reference_code(licence.case.reference_code)
            licence.save()


class Migration(migrations.Migration):

    dependencies = [
        ("licences", "0003_licence_reference_code"),
    ]

    operations = [
        migrations.RunPython(set_licence_reference),
    ]
