# Generated by Django 2.2.13 on 2020-06-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licences", "0005_auto_20200616_0837"),
    ]

    operations = [
        migrations.AddField(
            model_name="licence",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
