# Generated by Django 2.2.13 on 2020-07-03 09:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("licences", "0008_map_licence_status"),
    ]

    operations = [
        migrations.RemoveField(model_name="licence", name="is_complete",),
    ]
