# Generated by Django 2.2.13 on 2020-07-09 15:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("licences", "0012_auto_20200707_0820"),
    ]

    operations = [
        migrations.CreateModel(
            name="HMRCIntegrationUsageUpdate",
            fields=[
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created_at"
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="updated_at"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RenameField(
            model_name="licence",
            old_name="sent_at",
            new_name="hmrc_integration_sent_at",
        ),
        migrations.AlterField(
            model_name="licence",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="licences", to="applications.BaseApplication"
            ),
        ),
        migrations.AddField(
            model_name="licence",
            name="hmrc_integration_usage_updates",
            field=models.ManyToManyField(related_name="licences", to="licences.HMRCIntegrationUsageUpdate"),
        ),
    ]
