# Generated by Django 2.2.13 on 2020-07-17 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("licences", "0015_auto_20200715_1529"),
    ]

    operations = [
        migrations.RenameField(model_name="licence", old_name="application", new_name="case",),
    ]
