# Generated by Django 3.1.8 on 2021-05-06 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("licences", "0018_auto_20200717_1526"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HMRCIntegrationUsageUpdate",
            new_name="HMRCIntegrationUsageData",
        ),
    ]
