# Generated by Django 3.1.12 on 2021-10-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0019_auto_20210506_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='reference_code',
            field=models.TextField(editable=False, unique=True),
        ),
    ]
