# Generated by Django 4.2.16 on 2024-11-14 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0084_standardapplication_subject_to_itar_controls"),
        ("licences", "0019_auto_20210506_0340"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="goodonlicence",
            unique_together={("licence", "good")},
        ),
    ]
