# Generated by Django 4.2.17 on 2025-02-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licences", "0020_alter_goodonlicence_unique_together"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="goodonlicence",
            index=models.Index(fields=["created_at"], name="licences_go_created_b65faa_idx"),  # /PS-IGNORE
        ),
    ]
