---
title: Data Workspace ERD
---
erDiagram

    applications

    countries

    destinations

    footnotes

    goods_descriptions

    goods_on_licences

    goods_ratings

    goods

    licence_decisions

    licence_refusal_criteria

    statuses

    units
