# Generated by Django 4.2.16 on 2024-09-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FakeModel",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("thing", models.CharField(max_length=100)),
            ],
        ),
    ]
