# Generated by Django 2.2.11 on 2020-04-08 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("routing_rules", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routingrule",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="routing_rules", to="teams.Team"
            ),
        ),
    ]
