# Generated by Django 2.2.17 on 2020-12-11 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
        ('queues', '0003_auto_20201210_1649'),
        ('users', '0014_auto_20200907_1234'),
        ('statuses', '0004_auto_20201210_1716'),
        ('teams', '0002_auto_20200307_1805'),
        ('routing_rules', '0002_auto_20200408_1023'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='routingrule',
            unique_together={('team', 'queue', 'status', 'tier', 'additional_rules', 'active', 'user', 'country')},
        ),
    ]
