# Generated by Django 2.2.10 on 2020-02-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generated_documents", "0002_generatedcasedocument_template"),
    ]

    operations = [
        migrations.AlterField(model_name="generatedcasedocument", name="text", field=models.TextField(blank=True),),
    ]
