# Generated by Django 4.2.11 on 2024-04-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generated_documents", "0002_alter_generatedcasedocument_advice_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedcasedocument",
            name="advice_type",
            field=models.CharField(
                choices=[
                    ("approve", "Approve"),
                    ("proviso", "Proviso"),
                    ("refuse", "Refuse"),
                    ("no_licence_required", "No Licence Required"),
                    ("not_applicable", "Not Applicable"),
                    ("conflicting", "Conflicting"),
                    ("inform", "Inform"),
                    ("f680", "F680"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
