# Generated by Django 2.2.11 on 2020-03-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generated_documents", "0004_auto_20200311_1124"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedcasedocument",
            name="advice_type",
            field=models.CharField(
                choices=[
                    ("approve", "Approve"),
                    ("proviso", "Proviso"),
                    ("refuse", "Refuse"),
                    ("no_licence_required", "No Licence Required"),
                    ("not_applicable", "Not Applicable"),
                    ("conflicting", "Conflicting"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
