# Generated by Django 2.2.12 on 2020-05-18 14:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0023_auto_20200515_1248'),
        ('countries', '0001_initial'),
        ('control_list_entries', '0002_auto_20200419_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenGeneralLicence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created_at')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='updated_at')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('url', models.URLField(default=None)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Deactivated', 'Deactivated')], default='Active', max_length=20)),
                ('case_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='OpenGeneralLicence', to='cases.CaseType')),
                ('control_list_entries', models.ManyToManyField(related_name='OpenGeneralLicence', to='control_list_entries.ControlListEntry')),
                ('countries', models.ManyToManyField(default=[], related_name='OpenGeneralLicence', to='countries.Country')),
            ],
            options={
                'db_table': 'OpenGeneralLicence',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='opengenerallicence',
            index=models.Index(fields=['status', 'name'], name='OpenGeneral_status_26854e_idx'),
        ),
    ]
