# Generated by Django 2.2.12 on 2020-05-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("open_general_licences", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(model_name="opengenerallicence", name="OpenGeneral_status_26854e_idx",),
        migrations.AddIndex(
            model_name="opengenerallicence",
            index=models.Index(fields=["status", "name"], name="open_genera_status_80e1d9_idx"),
        ),
        migrations.AlterModelTable(name="opengenerallicence", table="open_general_licence",),
    ]
