# Generated by Django 2.2.12 on 2020-05-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("open_general_licences", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opengenerallicence",
            name="countries",
            field=models.ManyToManyField(related_name="OpenGeneralLicence", to="countries.Country"),
        ),
        migrations.AlterField(model_name="opengenerallicence", name="url", field=models.URLField(),),
    ]
