# Generated by Django 2.2.12 on 2020-05-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_general_licences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opengenerallicence',
            name='registration_required',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
