# Generated by Django 2.2.12 on 2020-05-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("open_general_licences", "0002_opengenerallicence_registration_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opengenerallicence", name="name", field=models.CharField(max_length=250, unique=True),
        ),
    ]
