# Generated by Django 2.2.12 on 2020-05-19 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("control_list_entries", "0002_auto_20200419_1827"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controllistentry",
            name="parent",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="control_list_entries.ControlListEntry",
            ),
        ),
    ]
