TRANSHIPMENT_AND_TRADE_CONTROL_BANNED_COUNTRIES = ["GB"]


class F680:
    ADDITIONAL_INFORMATION_FIELDS = (
        "expedited",
        "expedited_date",
        "foreign_technology",
        "foreign_technology_description",
        "locally_manufactured",
        "locally_manufactured_description",
        "mtcr_type",
        "electronic_warfare_requirement",
        "uk_service_equipment",
        "uk_service_equipment_description",
        "uk_service_equipment_type",
        "prospect_value",
    )

    REQUIRED_FIELDS = [
        "expedited",
        "foreign_technology",
        "locally_manufactured",
        "mtcr_type",
        "electronic_warfare_requirement",
        "uk_service_equipment",
        "uk_service_equipment_type",
        "prospect_value",
    ]

    REQUIRED_SECONDARY_FIELDS = {
        "foreign_technology": "foreign_technology_description",
        "expedited": "expedited_date",
        "locally_manufactured": "locally_manufactured_description",
    }


class CryptoOIEL:
    EXCLUDED_COUNTRIES = [
        ("Afghanistan", "AF"),
        ("Angola", "AO"),
        ("Armenia", "AM"),
        ("Australia", "AU"),
        ("Austria", "AT"),
        ("Azerbaijan", "AZ"),
        ("Belgium", "BE"),
        ("Bosnia and Herzegovina", "BA"),
        ("Bulgaria", "BG"),
        ("Burundi", "BI"),
        ("Canada", "CA"),
        ("China", "CN"),
        ("Congo (Democratic Republic)", "CD"),
        ("Croatia", "HR"),
        ("Cyprus", "CY"),
        ("Czechia", "CZ"),
        ("Denmark", "DK"),
        ("Eritrea", "ER"),
        ("Estonia", "EE"),
        ("Ethiopia", "ET"),
        ("Finland", "FI"),
        ("France", "FR"),
        ("Germany", "DE"),
        ("Greece", "GR"),
        ("Hong Kong", "HK"),
        ("Hungary", "HU"),
        ("Iran", "IR"),
        ("Iraq", "IQ"),
        ("Ireland", "IE"),
        ("Italy", "IT"),
        ("Japan", "JP"),
        ("North Korea", "KP"),
        ("Latvia", "LV"),
        ("Lebanon", "LB"),
        ("Liberia", "LR"),
        ("Libya", "LY"),
        ("Lithuania", "LT"),
        ("Luxembourg", "LU"),
        ("Malta", "MT"),
        ("Burma", "MM"),
        ("Netherlands", "NL"),
        ("New Zealand", "NZ"),
        ("Nigeria", "NG"),
        ("Norway", "NO"),
        ("Poland", "PL"),
        ("Portugal", "PT"),
        ("Romania", "RO"),
        ("Russia", "RU"),
        ("Rwanda", "RW"),
        ("Sierra Leone", "SL"),
        ("Slovakia", "SK"),
        ("Slovenia", "SI"),
        ("Somalia", "SO"),
        ("Spain", "ES"),
        ("Sudan", "SD"),
        ("South Sudan", "SS"),
        ("Sweden", "SE"),
        ("Switzerland", "CH"),
        ("Syria", "SY"),
        ("Tanzania", "TZ"),
        ("Uganda", "UG"),
        ("United States", "US"),
        ("Venezuela", "VE"),
        ("Zimbabwe", "ZW"),
    ]
