# Generated by Django 2.2.11 on 2020-03-25 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0009_ecjuquery_query_type"),
        ("cases", "0011_auto_20200320_1315"),
    ]

    operations = []
