# Generated by Django 2.2.11 on 2020-05-07 11:26
import django
from django.db import migrations

from api.cases.enums import AdviceLevel


def copy_data(advice):
    data = {
        "type": advice.type,
        "text": advice.text,
        "note": advice.note,
        "proviso": advice.proviso,
        "case_id": advice.case.id,
        "user_id": advice.user.id,
        "pv_grading": advice.pv_grading,
        "collated_pv_grading": advice.collated_pv_grading,
    }

    if advice.good:
        data["good_id"] = advice.good.id
    if advice.goods_type:
        data["goods_type_id"] = advice.goods_type.id
    if advice.country:
        data["country_id"] = advice.country.id
    if advice.end_user:
        data["end_user_id"] = advice.end_user.id
    if advice.ultimate_end_user:
        data["ultimate_end_user_id"] = advice.ultimate_end_user.id
    if advice.consignee:
        data["consignee_id"] = advice.consignee.id
    if advice.third_party:
        data["third_party_id"] = advice.third_party.id

    if hasattr(advice, "old_team"):
        data["team_id"] = advice.old_team.id

    return data


def migrate(apps, schema_editor):
    Advice = apps.get_model("cases", "Advice")
    TeamAdvice = apps.get_model("cases", "TeamAdvice")
    FinalAdvice = apps.get_model("cases", "FinalAdvice")

    for advice in TeamAdvice.objects.all():
        advice = Advice(**copy_data(advice), level=AdviceLevel.TEAM)
        advice.save()

        if advice.denial_reasons:
            for denial_reason in advice.denial_reasons.all():
                denial_reason.advice = advice
                denial_reason.save()

    for advice in FinalAdvice.objects.all():
        advice = Advice(**copy_data(advice), level=AdviceLevel.FINAL)
        advice.save()

        if advice.denial_reasons:
            for denial_reason in advice.denial_reasons.all():
                denial_reason.advice = advice
                denial_reason.save()


def reverse_migrate(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [("cases", "0019_prep_advice_model"), ("teams", "0002_auto_20200307_1805")]

    operations = [
        migrations.RunPython(migrate, reverse_migrate),
    ]
