# Generated by Django 2.2.12 on 2020-05-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0022_auto_20200513_1023"),
    ]

    operations = [
        migrations.AddField(
            model_name="advice", name="footnote", field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="advice",
            name="footnote_required",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
