# Generated by Django 2.2.12 on 2020-05-22 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_auto_20200505_0942"),
        ("cases", "0025_case_id_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="submitted_by",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="users.ExporterUser"),
        ),
    ]
