# Generated by Django 2.2.12 on 2020-06-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0029_auto_20200601_1432"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enforcementcheckid",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("application", "application"),
                    ("end_user", "end_user"),
                    ("consignee", "consignee"),
                    ("ultimate_end_user", "ultimate_end_user"),
                    ("third_party", "third_party"),
                    ("additional_contact", "additional_contact"),
                    ("site", "site"),
                    ("organisation", "organisation"),
                ],
                max_length=20,
            ),
        ),
    ]
