# Generated by Django 2.2.13 on 2020-06-08 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0031_ecjuquery_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casedocument",
            name="type",
            field=models.CharField(
                choices=[("UPLOADED", "Uploaded"), ("GENERATED", "Generated"), ("AUTO_GENERATED", "Auto Generated")],
                default="UPLOADED",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="casedocument",
            name="user",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="users.GovUser"),
        ),
    ]
