# Generated by Django 2.2.13 on 2020-06-10 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0032_auto_20200608_1433"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceCase",
            fields=[
                (
                    "case_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cases.Case",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("cases.case",),
        ),
        migrations.AlterField(
            model_name="casetype",
            name="reference",
            field=models.CharField(
                choices=[
                    ("oiel", "Open Individual Export Licence"),
                    ("ogel", "Open General Export Licence"),
                    ("oicl", "Open Individual Trade Control Licence"),
                    ("siel", "Standard Individual Export Licence"),
                    ("sicl", "Standard Individual Trade Control Licence"),
                    ("sitl", "Standard Individual Transhipment Licence"),
                    ("f680", "MOD F680 Clearance"),
                    ("exhc", "MOD Exhibition Clearance"),
                    ("gift", "MOD Gifting Clearance"),
                    ("cre", "HMRC Query"),
                    ("gqy", "Goods Query"),
                    ("eua", "End User Advisory Query"),
                    ("ogtcl", "Open General Trade Control Licence"),
                    ("ogtl", "Open General Transhipment Licence"),
                    ("comp", "Compliance"),
                ],
                max_length=5,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="casetype",
            name="sub_type",
            field=models.CharField(
                choices=[
                    ("standard", "Standard Licence"),
                    ("open", "Open Licence"),
                    ("hmrc", "HMRC Query"),
                    ("end_user_advisory", "End User Advisory Query"),
                    ("goods", "Goods Query"),
                    ("exhibition_clearance", "MOD Exhibition Clearance"),
                    ("gifting_clearance", "MOD Gifting Clearance"),
                    ("f680_clearance", "MOD F680 Clearance"),
                    ("compliance", "Compliance"),
                ],
                max_length=35,
            ),
        ),
    ]
