# Generated by Django 2.2.13 on 2020-06-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0034_delete_compliancecase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casetype",
            name="type",
            field=models.CharField(
                choices=[("application", "Application"), ("query", "Query"), ("compliance", "Compliance")],
                max_length=35,
            ),
        ),
    ]
