# Generated by Django 2.2.13 on 2020-06-15 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0037_auto_20200615_0826"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="cases", to="organisations.Organisation"
            ),
        ),
    ]
