# Generated by Django 2.2.13 on 2020-06-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0038_auto_20200615_1400"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casetype",
            name="type",
            field=models.CharField(
                choices=[
                    ("application", "Application"),
                    ("query", "Query"),
                    ("registration", "Registration"),
                    ("compliance", "Compliance"),
                ],
                max_length=35,
            ),
        ),
    ]
