# Generated by Django 2.2.13 on 2020-07-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("countries", "0001_initial"),
        ("goodstype", "0004_auto_20200423_1456"),
        ("cases", "0042_auto_20200707_1310"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodcountrydecision",
            name="approve",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
