# Generated by Django 2.2.16 on 2020-11-02 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200907_1234'),
        ('documents', '0001_initial'),
        ('cases', '0045_auto_20200713_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecjuquery',
            name='missing_document_reason',
            field=models.CharField(choices=[('NO_DOCUMENT', 'No document available'), ('OFFICIAL_SENSITIVE', 'Document is above OFFICIAL-SENSITIVE')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='EcjuQueryDocument',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.Document')),
                ('description', models.TextField(blank=True, default=None, max_length=280, null=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.EcjuQuery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.ExporterUser')),
            ],
            options={
                'abstract': False,
            },
            bases=('documents.document',),
        ),
    ]
