# Generated by Django 3.1.12 on 2021-09-24 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20210924_1241'),
        ('cases', '0049_auto_20210322_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentSLA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sla_days', models.IntegerField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_slas', to='cases.case')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_slas', to='teams.department')),
            ],
        ),
    ]
