# Generated by Django 3.1.12 on 2021-10-15 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_squashed_0018_baseuser_phone_number'),
        ('cases', '0050_departmentsla'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='countersign',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='countersigns', to='users.govuser'),
        ),
    ]
