# Generated by Django 3.1.8 on 2021-11-02 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_squashed_0018_baseuser_phone_number"),
        ("cases", "0050_departmentsla"),
    ]

    operations = [
        migrations.AddField(
            model_name="advice",
            name="countersign_comments",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Reasons provided by the countersigner when they agree/disagree with the advice during countersigning",
            ),
        ),
        migrations.AddField(
            model_name="advice",
            name="countersigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="countersigned_by",
                to="users.govuser",
            ),
        ),
    ]
