# Generated by Django 3.2.16 on 2023-02-27 01:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_default_govuser_queue"),
        ("cases", "0053_auto_20221122_1039"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountersignAdvice",
            fields=[
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created_at"
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="updated_at"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("order", models.PositiveIntegerField(help_text="Indicates countersigning order")),
                ("outcome_accepted", models.BooleanField()),
                (
                    "reasons",
                    models.TextField(
                        help_text="Reasons provided by the countersigner when they agree/disagree with the advice during countersigning"
                    ),
                ),
                (
                    "advice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="countersign", to="cases.advice"
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="countersign_advice", to="cases.case"
                    ),
                ),
                (
                    "countersigned_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="countersigned_user",
                        to="users.govuser",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
