# Generated by Django 3.2.18 on 2023-04-27 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "007_rename_fco"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cases", "0055_countersignadvice_valid"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseNoteMentions",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created_at"
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="updated_at"
                    ),
                ),
                ("is_urgent", models.BooleanField(default=False)),
                ("is_new", models.BooleanField(default=True)),
                ("case", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="cases.case")),
                ("team", models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="teams.team")),
                (
                    "user",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="casenote",
            name="mentions",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_query_name="case_note_mentions",
                to="cases.casenotementions",
            ),
        ),
    ]
