# Generated by Django 3.2.18 on 2023-04-27 15:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_value_for_pending_field"),
        ("teams", "007_rename_fco"),
        ("cases", "0055_countersignadvice_valid"),
    ]

    operations = [
        migrations.AddField(
            model_name="casenote",
            name="is_urgent",
            field=models.BooleanField(default=False, help_text="indicates if a case note mention is urgent"),
        ),
        migrations.CreateModel(
            name="CaseNoteMentions",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created_at"
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="updated_at"
                    ),
                ),
                (
                    "is_new",
                    models.BooleanField(default=True, help_text="indicates if a user has accessed this mention"),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="case_note_mentions",
                        to="cases.case",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="case_note_mentions",
                        to="teams.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="case_note_mentions",
                        to="users.govuser",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="casenote",
            name="mentions",
            field=models.ForeignKey(
                default=None,
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_query_name="case_note",
                to="cases.casenotementions",
            ),
        ),
    ]
