# Generated by Django 3.2.18 on 2023-05-05 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "007_rename_fco"),
        ("users", "0005_value_for_pending_field"),
        ("cases", "0056_auto_20230427_1652"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="casenote",
            name="mentions",
        ),
        migrations.RemoveField(
            model_name="casenotementions",
            name="case",
        ),
        migrations.AddField(
            model_name="casenotementions",
            name="case_note",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="mentions",
                to="cases.casenote",
            ),
        ),
        migrations.AlterField(
            model_name="casenotementions",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="mentions",
                to="teams.team",
            ),
        ),
        migrations.AlterField(
            model_name="casenotementions",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, related_name="mentions", to="users.govuser"
            ),
        ),
    ]
