# Generated by Django 3.2.20 on 2023-09-01 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("statuses", "0006_casesubstatus"),
        ("cases", "0059_alter_advice_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="sub_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_status",
                to="statuses.casesubstatus",
            ),
        ),
    ]
