# Generated by Django 3.2.21 on 2023-09-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0060_case_sub_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="countersignadvice",
            name="valid",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="Indicates whether it is valid or not. Existing countersignatures become invalid if original outcome is edited following countersigning\n        comments. In this case we want to keep the CountersignAdvice object for audit but we do not want to consider this as valid advice anymore, hence we\n        set `valid=False`.",
                null=True,
            ),
        ),
    ]
