# Generated by Django 3.2.23 on 2024-01-05 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0005_value_for_pending_field"),
        ("cases", "0060_case_sub_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ecjuquery",
            name="raised_by_user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="raised_by_user_ecju_query",
                to="users.govuser",
            ),
        ),
        migrations.AlterField(
            model_name="ecjuquery",
            name="responded_by_user",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responded_by_user_ecju_query",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
