# Generated by Django 3.2.22 on 2023-10-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0060_case_sub_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='processing_time',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
