# Generated by Django 3.2.23 on 2024-02-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0062_alter_ecjuquery_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecjuquery',
            name='chaser_email_sent_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
