# Generated by Django 4.2.11 on 2024-04-11 14:51

from django.db import migrations


def update_teams_on_advice(apps, schema_editor):
    Advice = apps.get_model("cases", "Advice")

    teams = set(Advice.objects.values_list("user__team", flat=True))
    for team in teams:
        advice_without_a_team = Advice.objects.filter(team__isnull=True, user__team=team)
        advice_without_a_team.update(team=team)


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0063_ecjuquery_chaser_email_sent_on"),
    ]

    operations = [
        migrations.RunPython(
            update_teams_on_advice,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
