# Generated by Django 4.2.11 on 2024-04-24 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0064_alter_advice_type"),
        ("cases", "0064_update_teams_on_advice"),
    ]

    operations = []
