# Generated by Django 4.2.11 on 2024-04-30 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0009_alter_party_type"),
        ("cases", "0065_merge_20240424_1728"),
    ]

    operations = [
        migrations.AddField(
            model_name="advice",
            name="open_destination",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="open_destination",
                to="parties.party",
            ),
        ),
    ]
