# Generated by Django 4.2.13 on 2024-06-17 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0065_case_amendment_of"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CaseReviewDate",
        ),
    ]
