# Generated by Django 4.2.14 on 2024-08-09 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("denial_reasons", "0007_alter_denialreason_uuid"),
        ("cases", "0066_delete_casereviewdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdviceDenialReason",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("advice", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cases.advice")),
                (
                    "denial_reason",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="denial_reasons.denialreason", to_field="uuid"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="advice",
            name="denial_reasons_uuid",
            field=models.ManyToManyField(
                related_name="advice_set_new", through="cases.AdviceDenialReason", to="denial_reasons.denialreason"
            ),
        ),
    ]
