# Generated by Django 4.2.13 on 2024-05-20 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("cases", "0066_advice_open_destination"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advice",
            name="country",
        ),
        migrations.RemoveField(
            model_name="advice",
            name="goods_type",
        ),
        migrations.AddField(
            model_name="advice",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
    ]
