# Generated by Django 4.2.16 on 2024-11-01 11:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("licences", "0019_auto_20210506_0340"),
        ("cases", "0066_delete_casereviewdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="LicenceDecision",
            fields=[
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created_at"
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="updated_at"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "decision",
                    models.CharField(
                        choices=[("issued", "issued"), ("refused", "refused"), ("revoked", "revoked")], max_length=50
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="licence_decisions",
                        to="cases.case",
                    ),
                ),
                (
                    "licence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="licence_decisions",
                        to="licences.licence",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
