# Generated by Django 4.2.13 on 2024-09-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0066_delete_casereviewdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="advice",
            name="valid",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="Indicates whether it is valid or not. Existing advice become invalid if new advice is given by the user",
                null=True,
            ),
        ),
    ]
