# Generated by Django 4.2.16 on 2024-10-24 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("licences", "0019_auto_20210506_0340"),
        ("cases", "0066_delete_casereviewdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="LicenceDecision",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("issued", "issued"),
                            ("refused", "refused"),
                            ("no_licence_required", "no_licence_required"),
                            ("withdrawn", "withdrawn"),
                            ("revoked", "revoked"),
                        ],
                        max_length=50,
                    ),
                ),
                ("decision_made_at", models.DateTimeField()),
                ("case", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="cases.case")),
                (
                    "licence",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="licences.licence"
                    ),
                ),
            ],
        ),
    ]
