# Generated by Django 4.2.16 on 2024-10-25 14:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("licences", "0019_auto_20210506_0340"),
        ("cases", "0066_delete_casereviewdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="LicenceDecision",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created_at"
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="updated_at"
                    ),
                ),
                ("decision", models.CharField(choices=[("issued", "issued")], max_length=50)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="licence_decisions",
                        to="cases.case",
                    ),
                ),
                (
                    "licence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="licence_decisions",
                        to="licences.licence",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
