# Generated by Django 4.2.13 on 2024-05-20 13:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_userorganisationrelationship_user"),
        ("teams", "0009_update_beis_to_desnz"),
        ("applications", "0085_alter_opendestination_application"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("cases", "0067_remove_advice_country_remove_advice_goods_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenAdvice",
            fields=[
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created_at"
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="updated_at"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("proviso", "Proviso"),
                            ("refuse", "Refuse"),
                            ("no_licence_required", "No Licence Required"),
                            ("not_applicable", "Not Applicable"),
                            ("conflicting", "Conflicting"),
                            ("inform", "Inform"),
                            ("f680", "F680"),
                        ],
                        max_length=30,
                    ),
                ),
                ("text", models.TextField(blank=True, default=None, null=True)),
                ("note", models.TextField(blank=True, default=None, null=True)),
                ("is_refusal_note", models.BooleanField(default=False)),
                (
                    "level",
                    models.CharField(choices=[("user", "User"), ("team", "Team"), ("final", "Final")], max_length=30),
                ),
                ("footnote", models.TextField(blank=True, default=None, null=True)),
                ("footnote_required", models.BooleanField(blank=True, default=None, null=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="open_advice", to="cases.case"
                    ),
                ),
                (
                    "open_destinations",
                    models.ManyToManyField(related_name="open_advice", to="applications.opendestination"),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
                ("team", models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="teams.team")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="users.govuser")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
