# Generated by Django 4.2.16 on 2024-11-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0068_populate_licence_decisions"),
    ]

    operations = [
        migrations.AddField(
            model_name="licencedecision",
            name="excluded_from_statistics_reason",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
