# Generated by Django 4.2.16 on 2024-11-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("denial_reasons", "0006_populate_uuid_field"),
        ("cases", "0068_populate_licence_decisions"),
    ]

    operations = [
        migrations.AddField(
            model_name="licencedecision",
            name="denial_reasons",
            field=models.ManyToManyField(to="denial_reasons.denialreason"),
        ),
    ]
