# Generated by Django 4.2.13 on 2024-05-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0085_alter_opendestination_application"),
        ("cases", "0070_backfill_advice_ctype"),
    ]

    operations = [
        migrations.AddField(
            model_name="openadvice",
            name="good_on_applications",
            field=models.ManyToManyField(related_name="open_advice", to="applications.goodonapplication"),
        ),
    ]
