# Generated by Django 4.2.16 on 2024-11-26 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0069_licencedecision_denial_reasons"),
        ("cases", "0072_alter_decision_populate_issued_on_appeal"),
    ]

    operations = []
