# Generated by Django 4.2.16 on 2024-11-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("denial_reasons", "0006_populate_uuid_field"),
        ("cases", "0072_alter_decision_populate_issued_on_appeal"),
        ("countries", "0006_update_trading_country_code"),
        ("organisations", "0014_alter_organisation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="licencedecision",
            name="denial_reasons",
            field=models.ManyToManyField(to="denial_reasons.denialreason"),
        ),
    ]
