# Generated by Django 4.2.16 on 2024-12-16 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0073_licencedecision_denial_reasons"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advice",
            name="goods_type",
        ),
        migrations.DeleteModel(
            name="GoodCountryDecision",
        ),
    ]
