# Generated by Django 4.2.16 on 2025-02-03 11:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("queues", "0007_populate_lu_countersigning_queues_alias"),
        ("cases", "0075_update_licence_decision_denial_reasons"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseQueueMovement",
            fields=[
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created_at"
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="updated_at"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("exit_date", models.DateTimeField(blank=True, null=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="casequeuemovements",
                        to="cases.case",
                    ),
                ),
                (
                    "queue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="casequeuemovements",
                        to="queues.queue",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
