# Generated by Django 4.2.17 on 2025-02-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0075_update_licence_decision_denial_reasons"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="licencedecision",
            index=models.Index(fields=["created_at"], name="cases_licen_created_850df1_idx"),
        ),
    ]
