# Generated by Django 4.2.16 on 2025-02-03 11:33

from django.db import migrations, transaction


from api.audit_trail.enums import AuditType


@transaction.atomic
def populate_case_queue_movements(apps, schema_editor):
    Audit = apps.get_model("audit_trail", "Audit")
    CaseQueueMovement = apps.get_model("cases", "CaseQueueMovement")

    case_queue_movements = []

    # Some of the early events doesn't have queue_ids in the payload so they are ignored
    move_case_qs = Audit.objects.filter(verb=AuditType.MOVE_CASE, payload__queue_ids__isnull=False)
    for event in move_case_qs:
        case_id = event.action_object_object_id
        queue_id = event.payload["queue_ids"][0]

        case_queue_movements.append(
            CaseQueueMovement(
                case_id=case_id,
                queue_id=queue_id,
            )
        )

    CaseQueueMovement.objects.bulk_create(case_queue_movements)


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0076_casequeuemovement"),
    ]

    operations = [
        migrations.RunPython(
            populate_case_queue_movements,
            migrations.RunPython.noop,
        ),
    ]
