# Generated by Django 4.2.17 on 2025-02-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0077_populate_case_queue_movements"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="case",
            index=models.Index(fields=["created_at"], name="cases_case_created_a9dee7_idx"),
        ),
    ]
