# Generated by Django 4.2.16 on 2025-02-11 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cases", "0079_licencedecision_cases_licen_created_850df1_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="casequeuemovement",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="casequeuemovements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
