# Generated by Django 4.2.19 on 2025-03-13 15:03

from django.db import migrations


def update_security_clearance_case_type_hierarchy(apps, schema_editor):
    CaseType = apps.get_model("cases", "CaseType")
    f680_case_type = CaseType.objects.get(reference="f680")
    f680_case_type.type = "security_clearance"
    f680_case_type.save()


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0080_alter_casetype_type"),
    ]

    operations = [migrations.RunPython(update_security_clearance_case_type_hierarchy, migrations.RunPython.noop)]
