# Generated by Django 4.2.19 on 2025-03-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0080_delete_unused_applications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casetype",
            name="type",
            field=models.CharField(
                choices=[
                    ("application", "Application"),
                    ("query", "Query"),
                    ("registration", "Registration"),
                    ("compliance", "Compliance"),
                    ("security_clearance", "Security Clearance"),
                ],
                max_length=35,
            ),
        ),
    ]
