# Generated by Django 4.2.16 on 2025-02-11 16:39

from django.db import migrations, transaction

from api.users.enums import SystemUser


@transaction.atomic
def populate_user_case_queue_movements(apps, schema_editor):
    CaseQueueMovement = apps.get_model("cases", "CaseQueueMovement")

    # looking at all MOVE_CASE events in UAT, all of the users are SystemUser
    # so we can just update user for all instances of CaseQueueMovement
    # as SystemUser without iterating through MOVE_CASE events.
    CaseQueueMovement.objects.all().update(user_id=SystemUser.id)


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0080_casequeuemovement_user"),
    ]

    operations = [
        migrations.RunPython(
            populate_user_case_queue_movements,
            migrations.RunPython.noop,
        ),
    ]
