# Generated by Django 4.2.19 on 2025-03-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0082_update_security_clearance_case_type_hierarchy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casetype",
            name="reference",
            field=models.CharField(
                choices=[
                    ("oiel", "Open Individual Export Licence"),
                    ("ogel", "Open General Export Licence"),
                    ("oicl", "Open Individual Trade Control Licence"),
                    ("siel", "Standard Individual Export Licence"),
                    ("sicl", "Standard Individual Trade Control Licence"),
                    ("sitl", "Standard Individual Transhipment Licence"),
                    ("f680", "MOD F680 Clearance"),
                    ("exhc", "MOD Exhibition Clearance"),
                    ("gift", "MOD Gifting Clearance"),
                    ("cre", "HMRC Query"),
                    ("gqy", "Goods Query"),
                    ("eua", "End User Advisory Query"),
                    ("ogtcl", "Open General Trade Control Licence"),
                    ("ogtl", "Open General Transhipment Licence"),
                    ("comp_c", "Compliance Site Case"),
                    ("comp_v", "Compliance Visit Case"),
                    ("export_licence", "Export Licence"),
                ],
                max_length=255,
                unique=True,
            ),
        ),
    ]
