# Generated by Django 4.2.19 on 2025-03-20 15:25

from django.db import migrations


def add_export_licence_case_type(apps, schema_editor):
    CaseType = apps.get_model("cases", "CaseType")
    CaseType.objects.create(
        id="00000000-0000-0000-0000-000000000017",
        type="application",
        reference="export_licence",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0084_alter_casetype_sub_type"),
    ]

    operations = [
        migrations.RunPython(
            add_export_licence_case_type,
            migrations.RunPython.noop,
        ),
    ]
