# Generated by Django 2.2 on 2019-05-20 12:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, default=None)),
                ('website', models.TextField(blank=True, default=None)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enduser', to='addresses.Address')),
            ],
        ),
    ]
