# Generated by Django 2.2 on 2019-05-25 15:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0003_add_sites_no_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, default=None)),
                ('address', models.TextField(blank=True, default=None)),
                ('country', models.TextField(blank=True, default=None)),
                ('website', models.URLField(blank=True, default=None)),
                ('type', models.CharField(choices=[('government', 'Government'), ('commercial', 'Commercial Organisation'), ('individual', 'Individual'), ('other', 'Other')], default='other', max_length=20)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enduser', to='organisations.Organisation')),
            ],
        ),
    ]
