# Generated by Django 2.2.2 on 2019-06-28 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('end_user', '0001_initial'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduser',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisation_end_user', to='organisations.Organisation'),
        ),
    ]
