# Generated by Django 2.2.3 on 2019-07-17 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        ('end_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduser',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisation_end_user', to='organisations.Organisation'),
        ),
    ]
