# Generated by Django 2.2 on 2019-05-20 13:57

from django.db import migrations
import end_user.models
import enumchoicefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('end_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduser',
            name='type',
            field=enumchoicefield.fields.EnumChoiceField(default=end_user.models.EndUserType(3), enum_class=end_user.models.EndUserType, max_length=10),
        ),
    ]
