# Generated by Django 2.2.2 on 2019-06-28 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('end_user', '0002_enduser_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enduser',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.Country'),
        ),
    ]
