# Generated by Django 2.2 on 2019-05-21 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_add_sites_no_constraint'),
        ('end_user', '0002_enduser_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduser',
            name='country',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='enduser',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enduser', to='organisations.Organisation'),
        ),
        migrations.AlterField(
            model_name='enduser',
            name='address',
            field=models.TextField(blank=True, default=None),
        ),
    ]
