# Generated by Django 2.2.4 on 2019-09-03 11:26

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
        ('end_user', '0002_enduser_organisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EUAEQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('details', models.TextField(blank=True, default=None, null=True)),
                ('raised_reason', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('end_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='euae_query', to='end_user.EndUser')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='euae_query_status', to='statuses.CaseStatus')),
            ],
        ),
    ]
