# Generated by Django 2.2 on 2019-05-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_user', '0003_auto_20190521_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enduser',
            name='website',
            field=models.URLField(blank=True, default=None),
        ),
    ]
