# Generated by Django 2.2.4 on 2019-09-04 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('end_user', '0003_euaequery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EUAEQuery',
        ),
    ]
