# Generated by Django 2.2.16 on 2020-12-08 16:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0014_auto_20200907_1234"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created_at"
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="updated_at"
                    ),
                ),
                ("text", models.TextField()),
                (
                    "object_pk",
                    models.TextField(help_text="The LITE or SPIRE product pk. Not the pk of this model instance"),
                ),
                (
                    "source",
                    models.TextField(
                        choices=[("SPIRE", "SPIRE"), ("LITE", "LITE")], help_text="Is the product from LITE or SPIRE?"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="product_comments", to="users.GovUser"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
