from django.db import models


class RecommendationChoiceType(models.TextChoices):
    VERY_DISSATISFIED = "VERY_DISSATISFIED", "VERY_DISSATISFIED"
    DISSATISFIED = "DISSATISFIED", "DISSATISFIED"
    NEUTRAL = "NEUTRAL", "NEUTRAL"
    SATISFIED = "SATISFIED", "SATISFIED"
    VERY_SATISFIED = "VERY_SATISFIED", "VERY_SATISFIED"


class SatisfactionRatingEnum(models.TextChoices):
    STRONGLY_DISAGREE = "STRONGLY DISAGREE", "STRONGLY DISAGREE"
    DISAGREE = "DISAGREE", "DISAGREE"
    NEITHER_AGREE_NOR_DISAGREE = "NEUTRAL", "NEUTRAL"
    AGREE = "AGREE", "AGREE"
    STRONGLY_AGREE = "STRONGLY AGREE", "STRONGLY AGREE"


class UserAccountEnum(models.TextChoices):
    VERY_DIFFICULT = "VERY DIFFICULT", "VERY DIFFICULT"
    DIFFICULT = "DIFFICULT", "DIFFICULT"
    NEITHER_DIFFICULT_NOR_EASY = "NEUTRAL", "NEUTRAL"
    EASY = "EASY", "EASY"
    VERY_EASY = "VERY EASY", "VERY EASY"


class ExperiencedIssueEnum(models.TextChoices):
    NO_ISSUE = "NO_ISSUE", "NO_ISSUE"
    UNCLEAR = "UNCLEAR", "UNCLEAR"
    NAVIGATION = "NAVIGATION", "NAVIGATION"
    FEATURE = "FEATURE", "FEATURE"
    SLOW = "SLOW", "SLOW"
    OTHER = "OTHER", "OTHER"
