# Generated by Django 2.2.4 on 2019-09-04 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controllistclassificationquery',
            name='status',
        ),
        migrations.AddField(
            model_name='query',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='query_status', to='statuses.CaseStatus'),
        ),
    ]
