# Generated by Django 2.2.4 on 2019-09-05 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20190905_1111'),
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ControlListClassificationQuery',
        ),
    ]
