# Generated by Django 3.2.20 on 2023-08-18 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_alter_document_safe"),
        ("appeals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppealDocument",
            fields=[
                (
                    "document_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="documents.document",
                    ),
                ),
                (
                    "appeal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="documents", to="appeals.appeal"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("documents.document",),
        ),
    ]
