# Generated by Django 2.2.2 on 2019-06-14 13:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, default=None, max_length=280, null=True)),
                ('is_good_controlled', models.BooleanField(blank=True, default=None, null=True)),
                ('control_code', models.TextField(blank=True, default=None, null=True)),
                ('is_good_end_product', models.BooleanField(blank=True, default=None, null=True)),
                ('object_id', models.UUIDField()),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'applications'), ('model', 'application')), models.Q(('app_label', 'drafts'), ('model', 'draft')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
