# Generated by Django 2.2.2 on 2019-06-21 10:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('goodstype', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsTypeOnApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, default=None, max_length=280, null=True)),
                ('is_good_controlled', models.BooleanField(blank=True, default=None, null=True)),
                ('control_code', models.TextField(blank=True, default=None, null=True)),
                ('is_good_end_product', models.BooleanField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsTypeOnDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, default=None, max_length=280, null=True)),
                ('is_good_controlled', models.BooleanField(blank=True, default=None, null=True)),
                ('control_code', models.TextField(blank=True, default=None, null=True)),
                ('is_good_end_product', models.BooleanField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='GoodsType',
        ),
    ]
