# Generated by Django 2.2.10 on 2020-03-02 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goodstype", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="goodstypedocument", name="description",),
    ]
