# Generated by Django 2.2.4 on 2019-08-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0001_initial'),
        ('goodstype', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodstype',
            name='flags',
            field=models.ManyToManyField(related_name='goods_type', to='flags.Flag'),
        ),
    ]
