# Generated by Django 2.2.11 on 2020-04-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goodstype", "0002_auto_20200402_1302"),
    ]

    operations = [
        migrations.AddField(model_name="goodstype", name="usage", field=models.FloatField(default=0),),
    ]
