# Generated by Django 2.2.4 on 2019-10-30 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("goodstype", "0002_goodstype_countries"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodstype",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="base_application",
                to="applications.BaseApplication",
            ),
        ),
    ]
