# Generated by Django 2.2.12 on 2020-04-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_list_entries", "0001_initial"),
        ("goodstype", "0002_auto_20200402_1302"),
    ]

    operations = [
        migrations.RemoveField(model_name="goodstype", name="control_code",),
        migrations.AddField(
            model_name="goodstype",
            name="control_code",
            field=models.ManyToManyField(related_name="goods", to="control_list_entries.ControlListEntry"),
        ),
    ]
