# Generated by Django 2.2.8 on 2020-01-09 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodstype', '0002_timestampable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodstype',
            old_name='is_good_end_product',
            new_name='is_good_incorporated',
        ),
    ]
