# Generated by Django 2.2.4 on 2019-09-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_auto_20190628_1252'),
        ('goodstype', '0002_goodstype_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodstype',
            name='countries',
            field=models.ManyToManyField(related_name='goods_type', to='countries.Country'),
        ),
    ]
