# Generated by Django 2.2.8 on 2020-01-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goodstype", "0002_timestampable"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodstype", name="comment", field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="goodstype", name="report_summary", field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
