# Generated by Django 2.2.8 on 2020-01-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodstype', '0003_auto_20200109_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodstype',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='goodstype',
            name='report_summary',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
