# Generated by Django 2.2.4 on 2019-11-04 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('goodstype', '0003_auto_20191030_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsTypeDocument',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.Document')),
                ('description', models.TextField(blank=True, default=None, max_length=280, null=True)),
                ('goods_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodstype.GoodsType')),
            ],
            bases=('documents.document',),
        ),
    ]
