# Generated by Django 2.2.12 on 2020-04-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_list_entries", "0002_auto_20200419_1827"),
        ("goodstype", "0003_goodstype_usage"),
    ]

    operations = [
        migrations.AlterModelOptions(name="goodstype", options={"ordering": ["-created_at"]},),
        migrations.RemoveField(model_name="goodstype", name="control_code",),
        migrations.AddField(
            model_name="goodstype",
            name="control_list_entries",
            field=models.ManyToManyField(related_name="goods_types", to="control_list_entries.ControlListEntry"),
        ),
        migrations.AlterModelTable(name="goodstype", table="goods_type",),
    ]
