# Generated by Django 2.2.11 on 2020-04-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goodstype", "0003_goodstype_usage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodstype", name="usage", field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
