# Generated by Django 2.2.11 on 2020-04-16 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goodstype", "0004_auto_20200415_1224"),
    ]

    operations = [
        migrations.AlterModelTable(name="goodstype", table="goods_type",),
    ]
