# Generated by Django 2.2.11 on 2020-04-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goodstype", "0004_auto_20200416_1345"),
    ]

    operations = [
        migrations.AlterField(model_name="goodstype", name="usage", field=models.FloatField(default=0),),
    ]
