# Generated by Django 2.2.11 on 2020-04-20 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goodstype", "0005_auto_20200416_0844"),
    ]

    operations = [
        migrations.AlterModelOptions(name="goodstype", options={"ordering": ["-created_at"]},),
    ]
