# Generated by Django 3.1.8 on 2021-06-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_list_entries", "0001_squashed_0005_auto_20200519_1617"),
    ]

    operations = [
        migrations.AddField(model_name="controllistentry", name="controlled", field=models.BooleanField(default=True),),
    ]
