# Generated by Django 3.1.8 on 2021-06-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    def populate_control_list_entries(apps, schema_editor):
        ratings = ("END", "MEND1", "MEND2", "MEND3")
        ControlListEntry = apps.get_model("control_list_entries", "ControlListEntry")
        for rating in ratings:
            ControlListEntry.objects.create(
                rating=rating,
                text="placeholder text for " + rating,
                parent_id=None,
                category="Non-military",
                controlled=True
            )


    dependencies = [
        ("control_list_entries", "0002_controllistentry_controlled"),
    ]

    operations = [
        migrations.RunPython(populate_control_list_entries, migrations.RunPython.noop),
    ]
