# Generated by Django 2.1.7 on 2019-03-21 16:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, default=None)),
                ('eori_number', models.TextField(blank=True, default=None)),
                ('sic_number', models.TextField(blank=True, default=None)),
                ('vat_number', models.TextField(blank=True, default=None)),
                ('registration_number', models.TextField(blank=True, default=None)),
                ('address', models.TextField(blank=True, default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
