# Generated by Django 2.2.9 on 2020-01-31 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        ('users', '0001_initial'),
        ('flags', '0001_initial'),
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='users',
            field=models.ManyToManyField(related_name='sites', to='users.UserOrganisationRelationship'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='flags',
            field=models.ManyToManyField(related_name='organisations', to='flags.Flag'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='primary_site',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisation_primary_site', to='organisations.Site'),
        ),
        migrations.AddField(
            model_name='externallocation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.Country'),
        ),
        migrations.AddField(
            model_name='externallocation',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_location', to='organisations.Organisation'),
        ),
    ]
