# Generated by Django 2.2.4 on 2019-12-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("organisations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="users",
            field=models.ManyToManyField(related_name="sites", to="users.UserOrganisationRelationship"),
        ),
    ]
