# Generated by Django 2.1.7 on 2019-03-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='address',
            field=models.TextField(blank=True, default=None),
        ),
    ]
