# Generated by Django 2.2 on 2019-05-01 08:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('organisations', '0002_remove_organisation_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(default=None)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site', to='addresses.Address')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site', to='organisations.Organisation')),
            ],
        ),
        migrations.AddField(
            model_name='organisation',
            name='primary_site',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='organisation_site', to='organisations.Site'),
        ),
    ]
