# Generated by Django 2.2.4 on 2019-09-26 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_lt_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['name']},
        ),
    ]
