# Generated by Django 2.2 on 2019-05-07 12:21

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('organisations', '0003_add_sites'), ('organisations', '0004_auto_20190507_1112')]

    dependencies = [
        ('organisations', '0002_remove_organisation_address'),
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(default=None)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site', to='addresses.Address')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site', to='organisations.Organisation')),
            ],
        ),
        migrations.AddField(
            model_name='organisation',
            name='primary_site',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisation_primary_site', to='organisations.Site'),
        ),
    ]
