# Generated by Django 2.2.8 on 2019-12-19 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0002_site_users"),
    ]

    operations = [
        migrations.AlterModelOptions(name="site", options={"ordering": ["name"]},),
    ]
