# Generated by Django 2.1.7 on 2019-03-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_organisation_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewOrganisationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default=None)),
                ('eori_number', models.TextField(blank=True, default=None)),
                ('sic_number', models.TextField(blank=True, default=None)),
                ('address', models.TextField(blank=True, default=None)),
                ('admin_user_email', models.EmailField(blank=True, default=None, max_length=254)),
            ],
        ),
    ]
