# Generated by Django 2.2.4 on 2019-09-27 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0003_auto_20190926_0952"),
    ]

    operations = [
        migrations.AlterModelOptions(name="site", options={},),
    ]
