# Generated by Django 2.2 on 2019-05-07 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_add_sites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='primary_site',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisation_primary_site', to='organisations.Site'),
        ),
    ]
