# Generated by Django 2.2 on 2019-05-29 13:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_add_sites_no_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(default=None)),
                ('address', models.TextField(default=None)),
                ('country', models.TextField(default=None)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_location', to='organisations.Organisation')),
            ],
        ),
    ]
