# Generated by Django 2.1.7 on 2019-03-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_neworganisationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='neworganisationrequest',
            name='vat_number',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='organisation',
            name='vat_number',
            field=models.TextField(blank=True, default=None),
        ),
    ]
