# Generated by Django 2.2 on 2019-05-01 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_auto_20190501_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='primary_site',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='organisation_primary_site', to='organisations.Site'),
        ),
    ]
