# Generated by Django 2.2.11 on 2020-03-19 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0002_foreignaddress"),
        ("organisations", "0004_auto_20200307_1805"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="foreign_address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="site",
                to="addresses.ForeignAddress",
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="address",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="site", to="addresses.Address"
            ),
        ),
    ]
