# Generated by Django 2.2.11 on 2020-03-22 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0005_auto_20200319_1409"),
    ]

    operations = [
        migrations.AlterModelTable(name="organisation", table="organisation",),
        migrations.AlterModelTable(name="site", table="site",),
    ]
