# Generated by Django 2.2.11 on 2020-04-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_auto_20200326_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='externallocation',
            name='location_type',
            field=models.CharField(blank=True, choices=[('land_based', 'Land based'), ('sea_based', 'Vessel (sea) based')], max_length=20, null=True),
        ),
    ]
