# Generated by Django 2.2.4 on 2019-10-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0001_initial'),
        ('organisations', '0006_auto_20191004_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='flags',
            field=models.ManyToManyField(related_name='organisations', to='flags.Flag'),
        ),
    ]
