# Generated by Django 2.2.11 on 2020-03-22 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0006_auto_20200322_1549"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="address",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="site", to="addresses.Address"
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="foreign_address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="site",
                to="addresses.ForeignAddress",
            ),
        ),
    ]
