# Generated by Django 2.2.12 on 2020-05-27 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0007_auto_20200505_1542"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="site_records_located_at",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="records",
                to="organisations.Site",
            ),
        ),
    ]
