# Generated by Django 2.2.12 on 2020-06-01 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0007_auto_20200505_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='is_used_on_application',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='site_records_located_at',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='records', to='organisations.Site'),
        ),
    ]
