# Generated by Django 2.2.12 on 2020-05-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0008_site_site_records_located_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="site", name="is_used_on_application", field=models.BooleanField(default=None, null=True),
        ),
    ]
