# Generated by Django 2.2.13 on 2020-06-12 14:21

from django.db import migrations
from django.db.models import F

from compliance.helpers import generate_compliance_site_case


def forward_migration(apps, schema_editor):
    Site = apps.get_model("organisations", "Site")
    Case = apps.get_model("cases", "Case")

    no_record_sites = list(Site.objects.filter(site_records_located_at__isnull=True).values_list("id", flat=True))

    cases = Case.objects.filter(
        baseapplication__application_sites__site_id__in=no_record_sites, baseapplication__licence__is_complete=True
    ).distinct()

    Site.objects.filter(id__in=no_record_sites).update(site_records_located_at=F("id"))

    for case in cases:
        generate_compliance_site_case(case)


def backwards_migration(apps, schema_editor):
    pass
    # I made this pass since we would lose data for backwards migrating this step regardless.


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0008_auto_20200601_0814"),
        ("compliance", "0002_compliancesitecase"),
    ]

    operations = [
        migrations.RunPython(forward_migration, backwards_migration),
    ]
