# Generated by Django 2.2.11 on 2020-03-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_trail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='visible',
            field=models.NullBooleanField(default=True),
        ),
    ]
