# Generated by Django 2.2.12 on 2020-04-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_trail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='hidden',
            field=models.NullBooleanField(),
        ),
    ]
