# Generated by Django 2.2.2 on 2019-06-12 08:42
import json

from django.db import migrations, models
import django.db.models.deletion
import uuid

from conf.settings import env
from teams.models import Team


def init(apps, schema_editor):
    GovUser = apps.get_model('gov_users', 'GovUser')
    Team = apps.get_model('teams', 'Team')
    if not GovUser.objects.all():
        for email in json.loads(env('SEED_USERS')):
            gov_user = GovUser(email=email,
                               team=Team.objects.get())
            gov_user.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Deactivated', 'Deactivated')], default='Active', max_length=20)),
                ('first_name', models.CharField(blank=True, default="Internal", max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, default="User", max_length=30, null=True)),
                ('email', models.EmailField(default=None, max_length=254, unique=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team', to='teams.Team')),
            ],
        ),
        migrations.RunPython(init),
    ]
