# Generated by Django 2.2.2 on 2019-06-12 08:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated')], default='active', max_length=20)),
                ('first_name', models.CharField(default=None, max_length=30)),
                ('last_name', models.CharField(default=None, max_length=30)),
                ('email', models.EmailField(default=None, max_length=254, unique=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team', to='teams.Team')),
            ],
        ),
    ]
