# Generated by Django 2.2.2 on 2019-07-15 08:25

import uuid

from django.db import migrations, models


def init(apps, schema_editor):
    # We can't import the Team model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Role = apps.get_model('gov_users', 'Role')
    if not Role.objects.all():
        role = Role(id='00000000-0000-0000-0000-000000000001',
                    name='Default')
        role.save()

    Permission = apps.get_model('gov_users', 'Permission')
    if not Permission.objects.all():
        permission = Permission(id='MAKE_FINAL_DECISIONS',
                                name='Make final decisions')
        permission.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gov_users', '0002_govuserrevisionmeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.CharField(editable=False, primary_key=True, serialize=False, max_length=30)),
                ('name', models.CharField(blank=True, default=None, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('permissions', models.ManyToManyField(related_name='roles', to='gov_users.Permission')),
            ],
        ),
        migrations.RunPython(init),
    ]
