# Generated by Django 2.2.2 on 2019-07-15 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gov_users', '0003_permission_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='govuser',
            name='role',
            field=models.ForeignKey(default='00000000-0000-0000-0000-000000000001', on_delete=django.db.models.deletion.PROTECT, related_name='role', to='gov_users.Role'),
        ),
    ]
