# Generated by Django 3.1.7 on 2021-02-24 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_trail', '0027_auto_20210222_1115'),
        ('audit_trail', '0027_auto_20210223_1815'),
    ]

    operations = [
    ]
