# Generated by Django 4.2.16 on 2024-11-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit_trail", "0027_alter_audit_verb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audit",
            name="action_object_object_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="audit",
            name="actor_object_id",
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name="audit",
            name="target_object_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
