# Generated by Django 4.2.16 on 2025-01-27 21:38

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit_trail", "0029_add_create_bulk_approval_audit_verb"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="audit",
            index=django.contrib.postgres.indexes.GinIndex(fields=["payload"], name="AuditPayloadIndex"),
        ),
    ]
