# Generated by Django 4.2.16 on 2025-01-28 17:02

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit_trail", "0030_audit_auditpayloadindex"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="audit",
            name="AuditPayloadIndex",
        ),
        migrations.AddIndex(
            model_name="audit",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["payload"], name="AuditPayloadFieldIndex", opclasses=["jsonb_path_ops"]
            ),
        ),
    ]
