# Generated by Django 2.2.3 on 2019-07-30 18:40

import uuid
from django.db import migrations, models
from static.statuses.enums import CaseStatusEnum


def populate_statuses(apps, schema_editor):
    CaseStatus = apps.get_model('statuses', 'CaseStatus')

    for status, priority in CaseStatusEnum.priorities.items():
        case_status = CaseStatus(status=status, priority=priority)
        case_status.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50, blank=False, null=False, unique=True)),
                ('priority', models.IntegerField(null=False, blank=False)),
            ],
        ),
        migrations.RunPython(populate_statuses),
    ]
