# Generated by Django 2.2.4 on 2019-12-03 09:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('priority', models.IntegerField()),
                ('is_read_only', models.BooleanField(null=True)),
                ('is_terminal', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseStatusCaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('application', 'Application'), ('clc_query', 'CLC Query'), ('end_user_advisory_query', 'End User Advisory Query'), ('hmrc_query', 'HMRC Query')], max_length=35)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statuses.CaseStatus')),
            ],
            options={
                'unique_together': {('type', 'status')},
            },
        ),
    ]
