# Generated by Django 2.2.4 on 2019-10-23 18:25

from django.db import migrations, models

from cases.views.search.service import get_case_status_list


def initialize(apps, schema_editor):
    CaseStatus = apps.get_model('statuses', 'CaseStatus')
    CaseStatus.objects.all().delete()

    for case_status in get_case_status_list():
        CaseStatus(status=case_status['status'], priority=case_status['priority']).save()


def destroy(apps, schema_editor):
    CaseStatus = apps.get_model('statuses', 'CaseStatus')
    CaseStatus.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0002_auto_20190919_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestatus',
            name='priority',
            field=models.IntegerField(choices=[('submitted', 1), ('resubmitted', 2), ('more_information_required', 3), ('under_review', 4), ('under_final_review', 5), ('withdrawn', 6), ('finalised', 7)]),
        ),
        migrations.AlterUniqueTogether(
            name='casestatus',
            unique_together={('status', 'priority')},
        ),
        migrations.RunPython(initialize, destroy),
    ]
