# Generated by Django 2.2.9 on 2020-02-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statuses", "0003_exhibition_clearance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casestatuscasetype",
            name="type",
            field=models.CharField(
                choices=[
                    ("application", "Application"),
                    ("goods_query", "Goods Query"),
                    ("end_user_advisory_query", "End User Advisory Query"),
                    ("hmrc_query", "HMRC Query"),
                    ("exhibition_clearance", "MOD Exhibition Clearance"),
                ],
                max_length=35,
            ),
        ),
    ]
