# Generated by Django 2.2.4 on 2019-10-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0003_auto_20191014_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestatus',
            name='priority',
            field=models.IntegerField(choices=[('submitted', 1), ('resubmitted', 2), ('more_information_required', 3), ('under_review', 4), ('under_final_review', 5), ('withdrawn', 6), ('finalised', 7), ('applicant_editing', 8)]),
        ),
        migrations.AlterUniqueTogether(
            name='casestatus',
            unique_together={('status', 'priority')},
        ),
    ]
