# Generated by Django 2.2.4 on 2019-11-01 15:59

from django.db import migrations, models

from static.statuses.enums import CaseStatusEnum


def initialize(apps, schema_editor):
    CaseStatus = apps.get_model('statuses', 'CaseStatus')

    for choice in CaseStatusEnum.choices:
        if not CaseStatus.objects.filter(status=choice[0]).exists():
            case_status = CaseStatus(status=choice[0],
                                     priority=CaseStatusEnum.priority[choice[0]],
                                     is_read_only=CaseStatusEnum.is_read_only[choice[0]]
                                     )
            case_status.save()


def destroy(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0003_auto_20191014_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestatus',
            name='is_read_only',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='casestatus',
            name='status',
            field=models.CharField(choices=[('applicant_editing', 'Applicant editing'), ('finalised', 'Finalised'), ('initial_checks', 'Initial checks'), ('resubmitted', 'Resubmitted'), ('submitted', 'Submitted'), ('under_final_review', 'Under final review'), ('under_review', 'Under review'), ('withdrawn', 'Withdrawn')], max_length=50),
        ),
        migrations.RunPython(initialize, destroy),
    ]
