# Generated by Django 2.2.4 on 2019-10-31 12:12

from django.db import migrations, models

from static.statuses.enums import CaseStatusEnum


def initialize(apps, schema_editor):
    CaseStatus = apps.get_model('statuses', 'CaseStatus')

    for choice in CaseStatusEnum.choices:
        if not CaseStatus.objects.filter(status=choice[0]).exists():
            case_status = CaseStatus(status=choice[0], priority=CaseStatusEnum.priorities[choice[0]])
            case_status.save()


def destroy(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0003_auto_20191014_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestatus',
            name='priority',
            field=models.IntegerField(choices=[('submitted', 1), ('resubmitted', 2), ('more_information_required', 3), ('under_review', 4), ('under_final_review', 5), ('withdrawn', 6), ('finalised', 7), ('applicant_editing', 8)]),
        ),
        migrations.RunPython(initialize, destroy),
    ]
