# Generated by Django 2.2.4 on 2019-10-30 11:19

from django.db import migrations, models

from static.statuses.enums import CaseStatusEnum


def initialize(apps, schema_editor):
    CaseStatus = apps.get_model('statuses', 'CaseStatus')

    for choice in CaseStatusEnum.choices:
        if not CaseStatus.objects.filter(status=choice[0]).exists():
            case_status = CaseStatus(status=choice[0], priority=CaseStatusEnum.priorities[choice[0]],
                                     is_read_only=CaseStatusEnum.is_read_only[choice[0]])
            case_status.save()


def destroy(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0003_auto_20191014_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestatus',
            name='is_read_only',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(initialize, destroy),
    ]
