# Generated by Django 2.2.10 on 2020-02-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statuses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casestatuscasetype",
            name="type",
            field=models.CharField(
                choices=[
                    ("oiel", "OIEL"),
                    ("ogel", "OGEL"),
                    ("oicl", "OICL"),
                    ("siel", "SIEL"),
                    ("sicl", "SICL"),
                    ("sitl", "SITL"),
                    ("f680", "F680"),
                    ("exhc", "EXHC"),
                    ("gift", "GIFT"),
                    ("cre", "CRE"),
                    ("gqy", "GQY"),
                    ("eua", "EUA"),
                ],
                max_length=35,
            ),
        ),
    ]
