# Generated by Django 2.2.4 on 2019-11-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0005_auto_20191108_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestatus',
            name='is_terminal',
            field=models.BooleanField(null=True),
        ),
    ]
