# Generated by Django 2.2.4 on 2019-11-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0005_auto_20191108_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestatus',
            name='id',
        ),
        migrations.AddField(
            model_name='casestatus',
            name='display_value',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='casestatus',
            name='status',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
