# Generated by Django 2.2.4 on 2019-11-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statuses", "0005_auto_20191108_1648"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casestatus", name="priority", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="casestatus",
            name="status",
            field=models.CharField(max_length=50),
        ),
    ]
