# Generated by Django 2.2.4 on 2019-11-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0006_casestatus_is_terminal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestatus',
            name='priority',
            field=models.IntegerField(choices=[('submitted', 1), ('applicant_editing', 2), ('resubmitted', 3), ('initial_checks', 4), ('under_review', 5), ('under_final_review', 6), ('finalised', 7), ('withdrawn', 8), ('closed', 9)]),
        ),
        migrations.AlterField(
            model_name='casestatus',
            name='status',
            field=models.CharField(choices=[('applicant_editing', 'Applicant editing'), ('closed', 'Closed'), ('finalised', 'Finalised'), ('initial_checks', 'Initial checks'), ('resubmitted', 'Resubmitted'), ('submitted', 'Submitted'), ('under_final_review', 'Under final review'), ('under_review', 'Under review'), ('withdrawn', 'Withdrawn')], max_length=50),
        ),
    ]
