# Generated by Django 2.2.4 on 2019-11-19 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("statuses", "0006_auto_20191118_1206"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casestatuscasetype",
            name="status",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="statuses.CaseStatus"),
        ),
    ]
