# Generated by Django 2.2.4 on 2019-08-27 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('end_user', '0002_enduser_organisation'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndUserDocument',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.Document')),
                ('end_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='end_user.EndUser')),
            ],
            bases=('documents.document',),
        ),
    ]
