# Generated by Django 2.2.4 on 2019-08-21 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('end_user', '0002_enduser_organisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndUserDocument',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.Document')),
                ('description', models.TextField(blank=True, default=None, max_length=280, null=True)),
                ('end_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='end_user.EndUser')),
            ],
            bases=('documents.document',),
        ),
    ]
