# Generated by Django 2.2.4 on 2019-08-26 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enduserdocument',
            name='description',
        ),
    ]
