# Generated by Django 2.2.4 on 2019-12-05 16:06

from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
        ("picklists", "0001_initial"),
        ("letter_layouts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LetterTemplate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=35, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified_at", models.DateTimeField(auto_now=True)),
                ("case_types", models.ManyToManyField(related_name="letter_templates", to="cases.CaseType")),
                (
                    "layout",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="letter_layouts.LetterLayout"),
                ),
                (
                    "letter_paragraphs",
                    sortedm2m.fields.SortedManyToManyField(help_text=None, to="picklists.PicklistItem"),
                ),
            ],
            options={"ordering": ["name"],},
        ),
    ]
