# Generated by Django 2.2.4 on 2019-10-04 15:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('letter_layouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letter_layouts.LetterLayout')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
