# Generated by Django 2.2.4 on 2019-11-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0005_auto_20191127_1435"),
        ("letter_templates", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="lettertemplate", name="restricted_to",),
        migrations.AddField(
            model_name="lettertemplate",
            name="case_types",
            field=models.ManyToManyField(related_name="letter_templates", to="cases.CaseType"),
        ),
    ]
