# Generated by Django 2.2.4 on 2019-12-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_types", "0002_auto_20191204_1621"),
        ("letter_templates", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="lettertemplate", name="restricted_to",),
        migrations.AddField(
            model_name="lettertemplate",
            name="case_types",
            field=models.ManyToManyField(related_name="letter_templates", to="case_types.CaseType"),
        ),
    ]
