# Generated by Django 2.2.4 on 2019-11-14 11:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letter_templates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lettertemplate",
            name="restricted_to",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(
                    choices=[
                        ("application", "Application"),
                        ("clc_query", "CLC Query"),
                        ("end_user_advisory_query", "End User Advisory Query"),
                        ("hmrc_query", "HMRC Query"),
                    ]
                ),
                default=list,
                size=None,
            ),
        ),
    ]
