# Generated by Django 2.2.10 on 2020-02-18 17:07

from django.db import migrations
import separatedvaluesfield.models


class Migration(migrations.Migration):

    dependencies = [
        ("letter_templates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lettertemplate",
            name="decisions",
            field=separatedvaluesfield.models.SeparatedValuesField(
                blank=True,
                choices=[
                    ("approve", "Approve"),
                    ("proviso", "Proviso"),
                    ("deny", "Deny"),
                    ("no_licence_required", "No Licence Required"),
                ],
                default=None,
                max_length=150,
                null=True,
            ),
        ),
    ]
