# Generated by Django 2.2.4 on 2019-10-07 16:04

import conf.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letter_templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lettertemplate',
            name='restricted_to',
            field=conf.fields.ListField(default=1),
            preserve_default=False,
        ),
    ]
