# Generated by Django 2.2.4 on 2019-10-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter_templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettertemplate',
            name='restricted_to',
            field=models.TextField(),
        ),
    ]
