# Generated by Django 2.2.10 on 2020-03-04 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("letter_templates", "0002_lettertemplate_decisions"),
    ]

    operations = [
        migrations.RemoveField(model_name="lettertemplate", name="decisions",),
    ]
