# Generated by Django 2.2.4 on 2019-11-22 11:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("letter_templates", "0002_auto_20191114_1113"),
    ]

    operations = [
        migrations.RemoveField(model_name="lettertemplate", name="restricted_to",),
        migrations.CreateModel(
            name="TemplateCaseTypes",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "case_type",
                    models.CharField(
                        choices=[
                            ("application", "Application"),
                            ("clc_query", "CLC Query"),
                            ("end_user_advisory_query", "End User Advisory Query"),
                            ("hmrc_query", "HMRC Query"),
                        ],
                        default="application",
                        max_length=35,
                    ),
                ),
                (
                    "letter_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="letter_templates.LetterTemplate"
                    ),
                ),
            ],
        ),
    ]
