# Generated by Django 2.2.4 on 2019-10-25 11:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter_templates', '0002_sort_letter_paragraphs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lettertemplate',
            name='restricted_to',
        ),
        migrations.AddField(
            model_name='lettertemplate',
            name='restricted_to',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(choices=[('application', 'Application'), ('clc_query', 'CLC Query'), ('end_user_advisory_query', 'End User Advisory Query')]), default=list, size=None),
        ),
    ]
