# Generated by Django 2.2.4 on 2019-11-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter_templates', '0002_restricted_to_as_arrayfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettertemplate',
            name='name',
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
