# Generated by Django 4.2.10 on 2024-02-28 14:23

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "feedback_submission_date",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="feedback_submission_date"
                    ),
                ),
                ("url", models.TextField(blank=True, default="N/A")),
                (
                    "user_journey",
                    models.CharField(
                        blank=True, choices=[("APPLICATION_SUBMISSION", "APPLICATION_SUBMISSION")], default=""
                    ),
                ),
                (
                    "satisfaction_rating",
                    models.CharField(
                        choices=[
                            ("VERY_SATISFIED", "VERY_SATISFIED"),
                            ("SATISFIED", "SATISFIED"),
                            ("NEITHER", "NEITHER"),
                            ("DISSATISFIED", "DISSATISFIED"),
                            ("VERY_DISSATISFIED", "VERY_DISSATISFIED"),
                        ]
                    ),
                ),
                (
                    "experienced_issue",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("NO_ISSUE", "NO_ISSUE"),
                                ("NOT_FIND_LOOKING_FOR", "NOT_FIND_LOOKING_FOR"),
                                ("DIFFICULT_TO_NAVIGATE", "DIFFICULT_TO_NAVIGATE"),
                                ("SYSTEM_LACKS_FEATURE", "SYSTEM_LACKS_FEATURE"),
                                ("UNABLE_TO_LOAD_REFRESH_ENTER", "UNABLE_TO_LOAD_REFRESH_ENTER"),
                                ("OTHER", "OTHER"),
                                ("SYSTEM_SLOW", "SYSTEM_SLOW"),
                                ("SUBMITTING_APPLICATION_UNCLEAR", "SUBMITTING_APPLICATION_UNCLEAR"),
                            ]
                        ),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("other_detail", models.TextField(blank=True, default="")),
                ("service_improvements_feedback", models.TextField(blank=True, default="")),
                (
                    "guidance_application_process_helpful",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("STRONGLY_DISAGREE", "STRONGLY_DISAGREE"),
                            ("DISAGREE", "DISAGREE"),
                            ("NEITHER", "NEITHER"),
                            ("AGREE", "AGREE"),
                            ("STRONGLY_AGREE", "STRONGLY_AGREE"),
                        ],
                        default="",
                    ),
                ),
                (
                    "process_of_creating_account",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ALREADY_HAD_ACCOUNT", "ALREADY_HAD_ACCOUNT"),
                            ("VERY_DIFFICULT", "VERY_DIFFICULT"),
                            ("DIFFICULT", "DIFFICULT"),
                            ("NEITHER", "NEITHER"),
                            ("EASY", "EASY"),
                            ("VERY_EASY", "VERY_EASY"),
                        ],
                        default="",
                    ),
                ),
            ],
        ),
    ]
