# Generated by Django 4.2.9 on 2024-02-12 11:50

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created_at"
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="updated_at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "recommendation",
                    models.TextField(
                        choices=[
                            ("VERY_DISSATISFIED", "VERY_DISSATISFIED"),
                            ("DISSATISFIED", "DISSATISFIED"),
                            ("NEUTRAL", "NEUTRAL"),
                            ("SATISFIED", "SATISFIED"),
                            ("VERY_SATISFIED", "VERY_SATISFIED"),
                        ]
                    ),
                ),
                ("other_detail", models.TextField(blank=True, null=True)),
                (
                    "experienced_issue",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("NO_ISSUE", "NO_ISSUE"),
                                ("UNCLEAR", "UNCLEAR"),
                                ("NAVIGATION", "NAVIGATION"),
                                ("FEATURE", "FEATURE"),
                                ("SLOW", "SLOW"),
                                ("OTHER", "OTHER"),
                            ]
                        ),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "helpful_guidance",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("STRONGLY DISAGREE", "STRONGLY DISAGREE"),
                            ("DISAGREE", "DISAGREE"),
                            ("NEITHER AGREE NOR DISAGREE", "NEITHER AGREE NOR DISAGREE"),
                            ("AGREE", "AGREE"),
                            ("STRONGLY AGREE", "STRONGLY AGREE"),
                        ],
                        default="",
                    ),
                ),
                (
                    "user_account_process",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("VERY DIFFICULT", "VERY DIFFICULT"),
                            ("DIFFICULT", "DIFFICULT"),
                            ("NEITHER DIFFICULT NOR EASY", "NEITHER DIFFICULT NOR EASY"),
                            ("EASY", "EASY"),
                            ("VERY EASY", "VERY EASY"),
                        ],
                        default="",
                    ),
                ),
                ("service_improvements_feedback", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
