# Generated by Django 4.2.20 on 2025-05-21 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0085_add_export_licence_case_type"),
        ("survey", "0002_surveyresponse_case_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyresponse",
            name="case_type",
            field=models.ForeignKey(
                blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to="cases.casetype"
            ),
        ),
    ]
