# Generated by Django 3.2.15 on 2022-10-03 14:23

from django.db import migrations, transaction


def deactivate_previous_tau_picklist_items(PicklistItem):
    PicklistItem.objects.filter(
        team__alias="TAU",
        type="report_summary",
    ).update(status="deactivated")


def create_tau_picklist_items(
    Team,
    PicklistItem,
    ReportSummaryPrefix,
    ReportSummarySubject,
):
    tau = Team.objects.get(alias="TAU")
    prefixes = [prefix.capitalize() for prefix in ReportSummaryPrefix.objects.values_list("name", flat=True)]
    subjects = [subject for subject in ReportSummarySubject.objects.values_list("name", flat=True)]
    picklist_items = []
    for prefix in prefixes:
        for subject in subjects:
            item = PicklistItem(
                team=tau,
                name=f"{prefix} {subject}",
                type="report_summary",
                status="active",
            )
            picklist_items.append(item)
    PicklistItem.objects.bulk_create(picklist_items)


@transaction.atomic
def update_picklist(apps, schema_editor):
    PicklistItem = apps.get_model("picklists", "PicklistItem")
    deactivate_previous_tau_picklist_items(PicklistItem)

    Team = apps.get_model("teams", "Team")
    ReportSummaryPrefix = apps.get_model("report_summaries", "ReportSummaryPrefix")
    ReportSummarySubject = apps.get_model("report_summaries", "ReportSummarySubject")
    create_tau_picklist_items(
        Team,
        PicklistItem,
        ReportSummaryPrefix,
        ReportSummarySubject,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("report_summaries", "0002_add_report_summaries"),
        ("picklists", "0002_auto_20220110_1430"),
        ("teams", "0007_auto_20220531_1344"),
        ("lite_routing", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            update_picklist,
            migrations.RunPython.noop,
        ),
    ]
