# Generated by Django 3.2.15 on 2022-10-14 08:34

from django.db import migrations, transaction


@transaction.atomic
def create_non_prefixed_items(apps, schema_editor):
    PicklistItem = apps.get_model("picklists", "PicklistItem")
    Team = apps.get_model("teams", "Team")
    ReportSummarySubject = apps.get_model("report_summaries", "ReportSummarySubject")

    tau = Team.objects.get(alias="TAU")

    picklist_items = []
    for subject in ReportSummarySubject.objects.values_list("name", flat=True):
        item = PicklistItem(
            team=tau,
            name=f"{subject.capitalize()}",
            type="report_summary",
            status="active",
        )
        picklist_items.append(item)
    PicklistItem.objects.bulk_create(picklist_items)


class Migration(migrations.Migration):

    dependencies = [
        ("report_summaries", "0003_update_tau_picklist"),
    ]

    operations = [
        migrations.RunPython(
            create_non_prefixed_items,
            migrations.RunPython.noop,
        ),
    ]
