# Generated by Django 3.2.15 on 2022-10-17 09:04
from django.db import migrations, transaction


@transaction.atomic
def update_report_summaries(apps, schema_editor):
    ReportSummaryPrefix = apps.get_model("report_summaries", "ReportSummaryPrefix")
    ReportSummarySubject = apps.get_model("report_summaries", "ReportSummarySubject")

    PicklistItem = apps.get_model("picklists", "PicklistItem")
    Team = apps.get_model("teams", "Team")

    tau = Team.objects.get(alias="TAU")

    PicklistItem.objects.filter(
        status="active",
        type="report_summary",
        team=tau,
    ).delete()

    prefixes = [prefix for prefix in ReportSummaryPrefix.objects.values_list("name", flat=True)]
    subjects = [subject for subject in ReportSummarySubject.objects.values_list("name", flat=True)]
    picklist_items = []
    for prefix in prefixes:
        for subject in subjects:
            item = PicklistItem(
                team=tau,
                name=f"{prefix} {subject}",
                type="report_summary",
                status="active",
            )
            picklist_items.append(item)
    for subject in subjects:
        item = PicklistItem(
            team=tau,
            name=subject,
            type="report_summary",
            status="active",
        )
        picklist_items.append(item)
    PicklistItem.objects.bulk_create(picklist_items)


class Migration(migrations.Migration):

    dependencies = [
        ("report_summaries", "0004_update_tau_non_prefixed_entries"),
    ]

    operations = [
        migrations.RunPython(
            update_report_summaries,
            migrations.RunPython.noop,
        ),
    ]
