# Generated by Django 4.2.11 on 2024-05-03 16:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("report_summaries", "0005_update_picklist_casing"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportSummary",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "prefix",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="prefix",
                        to="report_summaries.reportsummaryprefix",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="subject",
                        to="report_summaries.reportsummarysubject",
                    ),
                ),
            ],
            options={
                "unique_together": {("prefix", "subject")},
            },
        ),
    ]
