# Generated by Django 4.2.11 on 2024-05-07 21:13

import django.db.models.deletion

from django.db import migrations, models, transaction


@transaction.atomic
def populate_report_summaries(apps, schema_editor):
    ReportSummaryPrefix = apps.get_model("report_summaries", "ReportSummaryPrefix")
    ReportSummarySubject = apps.get_model("report_summaries", "ReportSummarySubject")
    ReportSummary = apps.get_model("report_summaries", "ReportSummary")

    prefix_ids = [None] + [str(prefix_id) for prefix_id in ReportSummaryPrefix.objects.values_list("id", flat=True)]
    subject_ids = [str(subject_id) for subject_id in ReportSummarySubject.objects.values_list("id", flat=True)]

    report_summary_combinations = [(prefix, subject) for prefix in prefix_ids for subject in subject_ids]

    rs_to_create = [
        ReportSummary(prefix_id=prefix_id, subject_id=subject_id)
        for prefix_id, subject_id in report_summary_combinations
    ]

    ReportSummary.objects.bulk_create(rs_to_create)


class Migration(migrations.Migration):

    dependencies = [
        ("lite_routing", "0037_update_report_summary_prefix_subject_ids"),
        ("report_summaries", "0006_reportsummary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportsummary",
            name="prefix",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prefix",
                to="report_summaries.reportsummaryprefix",
            ),
        ),
        migrations.AlterField(
            model_name="reportsummary",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subject",
                to="report_summaries.reportsummarysubject",
            ),
        ),
        migrations.RunPython(
            populate_report_summaries,
            migrations.RunPython.noop,
        ),
    ]
