# Generated by Django 2.2 on 2019-04-30 15:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0002_remove_organisation_address'),
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(default=None)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site', to='addresses.Address')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site', to='organisations.Organisation')),
            ],
        ),
    ]
