# Generated by Django 2.2.13 on 2020-06-10 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0032_auto_20200608_1433"),
        ("organisations", "0008_auto_20200601_0814"),
        ("open_general_licences", "0002_auto_20200522_1410"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenGeneralLicenceCase",
            fields=[
                (
                    "case_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cases.Case",
                    ),
                ),
                (
                    "open_general_licence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="open_general_licences.OpenGeneralLicence"
                    ),
                ),
                ("site", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="organisations.Site")),
            ],
            options={"db_table": "open_general_licence_case",},
            bases=("api.cases.case",),
        ),
    ]
