# Generated by Django 2.2.13 on 2020-07-17 13:18

from django.db import migrations, models

from api.cases.enums import CaseTypeEnum


def add_ogl_licence(apps, schema_editor):
    from api.open_general_licences.helpers import issue_open_general_licence

    Licence = apps.get_model("licences", "Licence")
    OpenGeneralLicenceCase = apps.get_model("open_general_licences", "OpenGeneralLicenceCase")

    ogels_with_licences = Licence.objects.filter(
        case__case_type__id__in=CaseTypeEnum.OPEN_GENERAL_LICENCE_IDS
    ).values_list("case_id", flat=True)
    ogels_without_licences = OpenGeneralLicenceCase.objects.all().exclude(id__in=ogels_with_licences)

    for ogel in ogels_without_licences:
        issue_open_general_licence(ogel)


def reverse_add_ogl_licence(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("open_general_licences", "0004_auto_20200610_1547"),
        ("licences", "0015_auto_20200715_1529"),
    ]

    operations = [
        migrations.RunPython(add_ogl_licence, reverse_code=reverse_add_ogl_licence),
    ]
