# Generated by Django 2.2.3 on 2019-08-14 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        ('documents', '0001_initial'),
        ('end_user', '0002_enduser_organisation'),
        ('users', '0003_auto_20190724_1334'),
        ('drafts', '0003_draft_ultimate_end_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndUserDocument',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.Document')),
                ('description', models.TextField(blank=True, default=None, max_length=280, null=True)),
                ('end_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='end_user.EndUser')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ExporterUser')),
            ],
            bases=('documents.document',),
        ),
        migrations.CreateModel(
            name='DraftEndUserDocument',
            fields=[
                ('enduserdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='end_user_document.EndUserDocument')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drafts.Draft')),
            ],
            bases=('end_user_document.enduserdocument',),
        ),
    ]
