# Generated by Django 2.2.4 on 2019-08-15 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_document', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enduserdocument',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='enduserdocument',
            name='user',
        ),
        migrations.DeleteModel(
            name='DraftEndUserDocument',
        ),
    ]
