# Generated by Django 2.2.10 on 2020-03-04 13:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Decision",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("proviso", "Proviso"),
                            ("deny", "Deny"),
                            ("no_licence_required", "No Licence Required"),
                        ],
                        max_length=45,
                    ),
                ),
            ],
        ),
    ]
