# Generated by Django 3.1.13 on 2021-11-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("documents", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="document",
            name="includes_company_letterhead",
            field=models.NullBooleanField(
                help_text="Does the document include at least one page on company letterhead?"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="is_content_english",
            field=models.NullBooleanField(help_text="Is the document in English?"),
        ),
    ]
