# Generated by Django 2.2.4 on 2019-09-16 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('parties', '0002_auto_20190916_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyDocument',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.Document')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.Party')),
            ],
            bases=('documents.document',),
        ),
    ]
