# Generated by Django 2.2.4 on 2019-11-18 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("document", "0001_initial"),
        ("parties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="partydocument",
            name="party",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="parties.Party"),
        ),
    ]
