# Generated by Django 2.2.4 on 2019-09-11 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0001_initial'),
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduserdocument',
            name='end_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.EndUser'),
        ),
    ]
