# Generated by Django 2.2.10 on 2020-03-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0002_auto_20200210_1326"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="status",
            field=models.CharField(
                choices=[("active", "active"), ("in_review", "in_review")], default="in_review", max_length=20
            ),
        ),
    ]
