# Generated by Django 2.2.11 on 2020-05-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0005_auto_20200326_1420"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("in_review", "In review"), ("rejected", "Rejected")],
                default="in_review",
                max_length=20,
            ),
        ),
    ]
