# Generated by Django 2.2.12 on 2020-06-01 08:14

from django.db import migrations, models
import django.db.models.deletion

from api.applications.models import SiteOnApplication
from cases.models import Case
from api.organisations.models import Site


def set_site_used_on_application(apps, schema_editor):
    draft_application_ids = Case.objects.filter(status__status="draft").values_list("id", flat=True)

    for site in Site.objects.all():
        if (
            SiteOnApplication.objects.filter(site_id=site.id).exclude(application_id__in=draft_application_ids).count()
            > 0
        ):
            site.is_used_on_application = True
        else:
            site.is_used_on_application = False

        site.save()


def reverse_set_site_used_on_application(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0007_auto_20200505_1542"),
    ]

    operations = [
        migrations.AddField(
            model_name="site", name="is_used_on_application", field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="site_records_located_at",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="records",
                to="organisations.Site",
            ),
        ),
        migrations.RunPython(set_site_used_on_application, reverse_code=reverse_set_site_used_on_application),
    ]
