# Generated by Django 2.2.13 on 2020-06-12 14:21
from django.core.management import call_command
from django.db import migrations
from django.db.models import F

from api.cases.enums import CaseTypeEnum
from api.cases.models import CaseType
from api.compliance.helpers import generate_compliance_site_case
from api.licences.enums import LicenceStatus

from api.static.statuses.enums import CaseStatusEnum
from api.static.statuses.models import CaseStatus


def forward_migration(apps, schema_editor):
    # Manual migration to ensure that all current sites have their "records held at" property set and all sites that are
    #   linked to licences have a compliance case where there should be one already.
    Site = apps.get_model("organisations", "Site")
    Case = apps.get_model("cases", "Case")

    no_record_sites = Site.objects.filter(site_records_located_at__isnull=True)
    no_record_sites.update(site_records_located_at=F("id"))

    cases = Case.objects.filter(
        baseapplication__application_sites__site__site_records_located_at__compliance__isnull=True,
        baseapplication__licences__status__in=[LicenceStatus.ISSUED, LicenceStatus.REINSTATED],
    ).distinct()

    # Get or create case type & status because seeding may not have run yet
    if not CaseType.objects.filter(id=CaseTypeEnum.COMPLIANCE_SITE.id).exists():
        call_command("seedcasetypes")

    if not CaseStatus.objects.filter(status=CaseStatusEnum.OPEN).exists():
        call_command("seedcasestatuses")

    for case in cases:
        generate_compliance_site_case(case)


def backwards_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0008_auto_20200601_0814"),
        ("compliance", "0002_compliancesitecase"),
        ("statuses", "0003_auto_20200318_1730"),
    ]

    operations = [
        migrations.RunPython(forward_migration, backwards_migration),
    ]
