# Generated by Django 2.2.17 on 2021-02-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0010_documentonorganisatio"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentonorganisation",
            name="reference_code",
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
