# Generated by Django 2.2.17 on 2021-02-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0011_documentonorganisation_reference_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentonorganisation",
            name="document_type",
            field=models.TextField(
                choices=[
                    ("section-one-certificate", "Firearm Section 1 certificate"),
                    ("section-two-certificate", "Firearm Section 2 certificate"),
                    ("section-five-certificate", "Firearm Section 5 certificate"),
                    ("rfd-certificate", "Registered Firearm Dealer certificate"),
                ]
            ),
        ),
    ]
