# Generated by Django 3.2.13 on 2022-07-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0013_auto_20210412_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('in_review', 'In review'), ('rejected', 'Rejected'), ('draft', 'Draft')], default='in_review', max_length=20),
        ),
    ]
