# Generated by Django 4.2.11 on 2024-04-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0014_alter_organisation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="registration_number",
            field=models.TextField(blank=True, default=None, null=True, unique=True),
        ),
    ]
