# Generated by Django 4.2.13 on 2024-06-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0014_alter_organisation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="website",
            field=models.TextField(blank=True, default=""),
        ),
    ]
