# Generated by Django 4.2.16 on 2024-10-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0014_alter_organisation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="royal_charter_number",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
