# Generated by Django 2.2.10 on 2020-02-13 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0004_auto_20200211_1459"),
        ("statuses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="casestatuscasetype",
            name="case_type",
            field=models.ForeignKey(
                default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="cases.CaseType"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="casestatuscasetype",
            unique_together={("case_type", "status")},
        ),
        migrations.RemoveField(model_name="casestatuscasetype", name="type"),
    ]
