# Generated by Django 2.2.17 on 2020-12-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0003_auto_20200318_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestatus',
            name='status',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
