# Generated by Django 3.1.7 on 2021-02-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0003_auto_20200318_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestatus',
            name='status',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
