# Generated by Django 3.2.20 on 2023-09-01 15:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("statuses", "0005_casestatus_next_workflow_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseSubStatus",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "parent_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_statuses",
                        to="statuses.casestatus",
                    ),
                ),
            ],
        ),
    ]
