# Generated by Django 3.2.20 on 2023-09-19 11:50

from django.db import migrations


def rename_ogd_advice_name(apps, schema_editor):
    CaseStatus = apps.get_model("statuses", "CaseStatus")
    CaseSubStatus = apps.get_model("statuses", "CaseSubStatus")

    SUB_STATUS__UNDER_APPEAL__OGD_ADVICE = "00000000-0000-0000-0000-000000000010"

    sub_status = CaseSubStatus.objects.get(id=SUB_STATUS__UNDER_APPEAL__OGD_ADVICE)
    sub_status.name = "OGD advice"
    sub_status.save()


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0007_add_case_sub_status_records'),
    ]

    operations = [
        migrations.RunPython(rename_ogd_advice_name, migrations.RunPython.noop),
    ]
