# Generated by Django 3.2.20 on 2023-09-19 11:50

from django.db import migrations


def rename_request_received_name(apps, schema_editor):
    CaseStatus = apps.get_model("statuses", "CaseStatus")
    CaseSubStatus = apps.get_model("statuses", "CaseSubStatus")

    SUB_STATUS__UNDER_APPEAL__REQUEST_RECEIVED = "00000000-0000-0000-0000-000000000007"

    sub_status = CaseSubStatus.objects.get(id=SUB_STATUS__UNDER_APPEAL__REQUEST_RECEIVED)
    sub_status.name = "Appeal received"
    sub_status.save()


class Migration(migrations.Migration):

    dependencies = [
        ("statuses", "0008_update_ogd_advice_name"),
    ]

    operations = [
        migrations.RunPython(rename_request_received_name, migrations.RunPython.noop),
    ]
