# Generated by Django 3.2.20 on 2023-09-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statuses", "0009_update_request_received_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="casesubstatus",
            name="order",
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
