# Generated by Django 4.2.13 on 2024-07-01 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("statuses", "0013_add_superseded_by_amendment_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="casestatus",
            name="is_read_only",
        ),
        migrations.RemoveField(
            model_name="casestatus",
            name="is_terminal",
        ),
    ]
