from enum import Enum


# TODO: Compress verbs.
class Verb(Enum):
    ADDED_PARTY = 'added party'
    REMOVED_PARTY = 'removed party'
    ADDED_NOTE = 'added note'
    REMOVED_NOTE = 'removed note'
    ADDED_QUEUES = 'added queues'
    REMOVED_QUEUES = 'removed queues'
    ADDED_ADVICE = 'added advice'
    REMOVED_ADVICE = 'removed advice'
    CREATED_FINAL_ADIVCE = 'created final advice'
    CLEARED_FINAL_ADVICE = 'cleared final advice'
    ADDED_ECJU = 'added ecju'
    ADDED_FLAGS = 'added flags'
    REMOVED_FLAGS = 'removed flags'
    UPLOADED_DOCUMENT = 'uploaded document'
    DELETED_DOCUMENT = 'deleted document'
    UPDATED_CONTROL_CODE = 'updated'
    UPDATED_STATUS = 'updated status'
    UPDATED_APPLICATION = 'updated application'
    CLC_RESPONSE = 'clc response'
    ADDED_GOOD_TO_APPLICATION = 'added good to app'
    REMOVED_GOOD_TO_APPLICATION = 'removed good to app'
    ADD_GOOD_TYPE_TO_APPLICATION = 'add good type to app'
    REMOVED_SITES_FROM_APPLICATION = 'removed sites from app'
    REMOVED_EXTERNAL_LOCATIONS_FROM_APPLICATION = 'removed external locations from application'
    ADDED_EXTERNAL_LOCATIONS_FROM_APPLICATION = 'removed external locations from application'
    ADDED_SITES_TO_APPLICATION = 'added sites to application'
    ADDED_COUNTRIES = 'added countries'
    REMOVED_COUNTRIES = 'removed countries'
    GOOD_REVIEWED = 'good reviewed'
    GENERATE_CASE_DOCUMENT = 'generate case document'
