# Generated by Django 2.2.11 on 2020-04-19 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("control_list_entries", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(name="controllistentry", table="control_list_entry",),
    ]
