# Generated by Django 2.2.12 on 2020-05-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_list_entries", "0004_remove_decontrolled_entries"),
    ]

    operations = [
        migrations.RemoveField(model_name="controllistentry", name="is_decontrolled",),
        migrations.AddField(
            model_name="controllistentry", name="category", field=models.CharField(default="", max_length=100),
        ),
    ]
