# Generated by Django 2.2.2 on 2019-06-28 15:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('end_user', '0003_auto_20190628_1026'),
        ('countries', '0002_auto_20190628_1252'),
        ('organisations', '0002_auto_20190628_1441'),
        ('goods', '0002_good_organisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, default=None, null=True)),
                ('activity', models.TextField(blank=True, default=None, null=True)),
                ('usage', models.TextField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now_add=True)),
                ('licence_type', models.CharField(choices=[('standard_licence', 'Standard Licence'), ('open_licence', 'Open Licence')], default=None, max_length=50)),
                ('export_type', models.CharField(choices=[('permanent', 'Permanent'), ('temporary', 'Temporary')], default=None, max_length=50)),
                ('reference_number_on_information_form', models.TextField(blank=True, null=True)),
                ('end_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_end_user', to='end_user.EndUser')),
                ('organisation', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation')),
            ],
        ),
        migrations.CreateModel(
            name='SiteOnDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_sites', to='drafts.Draft')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites_on_draft', to='organisations.Site')),
            ],
        ),
        migrations.CreateModel(
            name='GoodOnDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.FloatField(blank=True, default=None, null=True)),
                ('unit', models.CharField(choices=[('Gram(s)', 'Gram(s)'), ('Kilogram(s)', 'Kilogram(s)'), ('Number of articles', 'Number of articles'), ('Square metre(s)', 'Square metre(s)'), ('Metre(s)', 'Metre(s)'), ('Litre(s)', 'Litre(s)'), ('Cubic metre(s)', 'Cubic metre(s)')], default='Gram(s)', max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=256)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='drafts.Draft')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_on_draft', to='goods.Good')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalLocationOnDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_external_locations', to='drafts.Draft')),
                ('external_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_locations_on_draft', to='organisations.ExternalLocation')),
            ],
        ),
        migrations.CreateModel(
            name='CountryOnDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries_on_draft', to='countries.Country')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_countries', to='drafts.Draft')),
            ],
        ),
    ]
