# Generated by Django 2.2.3 on 2019-07-17 08:51

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryOnDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, default=None, null=True)),
                ('activity', models.TextField(blank=True, default=None, null=True)),
                ('usage', models.TextField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now_add=True)),
                ('licence_type', models.CharField(choices=[('standard_licence', 'Standard Licence'), ('open_licence', 'Open Licence')], default=None, max_length=50)),
                ('export_type', models.CharField(choices=[('permanent', 'Permanent'), ('temporary', 'Temporary')], default=None, max_length=50)),
                ('have_you_been_informed', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default=None, max_length=50)),
                ('reference_number_on_information_form', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalLocationOnDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='GoodOnDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.FloatField(blank=True, default=None, null=True)),
                ('unit', models.CharField(choices=[('GRM', 'Gram(s)'), ('KGM', 'Kilogram(s)'), ('NAR', 'Number of articles'), ('MTK', 'Square metre(s)'), ('MTR', 'Metre(s)'), ('LTR', 'Litre(s)'), ('MTQ', 'Cubic metre(s)')], default='GRM', max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=256)),
            ],
        ),
        migrations.CreateModel(
            name='SiteOnDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_sites', to='drafts.Draft')),
            ],
        ),
    ]
