# Generated by Django 2.2.2 on 2019-06-23 18:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
        ('drafts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryOnDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries_on_draft', to='countries.Country')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_countries', to='drafts.Draft')),
            ],
        ),
    ]
