# Generated by Django 2.2.4 on 2019-09-10 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0002_auto_20190628_1252'),
        ('organisations', '0001_initial'),
        ('goods', '0001_initial'),
        ('end_user', '0004_delete_euaequery'),
        ('drafts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodondraft',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_on_draft', to='goods.Good'),
        ),
        migrations.AddField(
            model_name='externallocationondraft',
            name='draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_external_locations', to='drafts.Draft'),
        ),
        migrations.AddField(
            model_name='externallocationondraft',
            name='external_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_locations_on_draft', to='organisations.ExternalLocation'),
        ),
        migrations.AddField(
            model_name='draft',
            name='end_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_end_user', to='end_user.EndUser'),
        ),
        migrations.AddField(
            model_name='draft',
            name='organisation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation'),
        ),
        migrations.AddField(
            model_name='draft',
            name='ultimate_end_users',
            field=models.ManyToManyField(related_name='drafts', to='end_user.EndUser'),
        ),
        migrations.AddField(
            model_name='countryondraft',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries_on_draft', to='countries.Country'),
        ),
        migrations.AddField(
            model_name='countryondraft',
            name='draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_countries', to='drafts.Draft'),
        ),
    ]
