# Generated by Django 2.2.4 on 2019-09-11 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drafts', '0001_initial'),
        ('parties', '0001_initial'),
        ('organisations', '0001_initial'),
        ('countries', '0002_auto_20190628_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='consignee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_consignee', to='parties.Consignee'),
        ),
        migrations.AddField(
            model_name='draft',
            name='end_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_end_user', to='parties.EndUser'),
        ),
        migrations.AddField(
            model_name='draft',
            name='organisation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation'),
        ),
        migrations.AddField(
            model_name='draft',
            name='third_parties',
            field=models.ManyToManyField(related_name='draft_third_parties', to='parties.ThirdParty'),
        ),
        migrations.AddField(
            model_name='draft',
            name='ultimate_end_users',
            field=models.ManyToManyField(related_name='draft_ultimate_end_users', to='parties.UltimateEndUser'),
        ),
        migrations.AddField(
            model_name='countryondraft',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries_on_draft', to='countries.Country'),
        ),
        migrations.AddField(
            model_name='countryondraft',
            name='draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_countries', to='drafts.Draft'),
        ),
    ]
