# Generated by Django 2.1.7 on 2019-02-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='draft',
            name='last_modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
