# Generated by Django 2.2.2 on 2019-06-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='licence_type',
            field=models.CharField(choices=[('standard_licence', 'Standard Licence'), ('open_licence', 'Open Licence')], default=None, max_length=50),
        ),
    ]
