# Generated by Django 2.2 on 2019-04-23 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
        ('drafts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draft',
            name='control_code',
        ),
        migrations.RemoveField(
            model_name='draft',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='draft',
            name='user_id',
        ),
        migrations.AddField(
            model_name='draft',
            name='organisation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation'),
        ),
    ]
