# Generated by Django 2.1.7 on 2019-03-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='name',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
