# Generated by Django 2.2 on 2019-05-29 13:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_externalsite'),
        ('drafts', '0002_auto_20190530_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSiteOnDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_external_sites', to='drafts.Draft')),
                ('external_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_sites_on_draft', to='organisations.ExternalSite')),
            ],
        ),
    ]
