# Generated by Django 2.2.4 on 2019-09-09 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
        ('drafts', '0002_auto_20190909_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='consignee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_consignee', to='parties.Consignee'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='ultimate_end_users',
            field=models.ManyToManyField(related_name='draft_ultimate_end_users', to='parties.UltimateEndUser'),
        ),
    ]
