# Generated by Django 2.2.2 on 2019-06-26 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0002_countryondraft'),
        ('drafts', '0002_auto_20190614_1332'),
    ]

    operations = [
    ]
