# Generated by Django 2.2.4 on 2019-09-20 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('drafts', '0002_auto_20190918_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftDocuments',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.Document')),
                ('description', models.TextField(blank=True, default=None, max_length=280, null=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drafts.Draft')),
            ],
            bases=('documents.document',),
        ),
    ]
