# Generated by Django 2.1.7 on 2019-03-18 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0002_draft_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='draft',
            table=None,
        ),
    ]
