# Generated by Django 2.2 on 2019-04-25 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0003_goodondraft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodondraft',
            name='end_use_case',
        ),
    ]
