# Generated by Django 2.2 on 2019-05-20 13:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('end_user', '0002_enduser_type'),
        ('drafts', '0006_auto_20190517_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndUserOnDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_end_users', to='drafts.Draft')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_user_on_draft', to='end_user.EndUser')),
            ],
        ),
    ]
