# Generated by Django 2.2 on 2019-05-20 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0006_auto_20190517_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draft',
            name='destination',
        ),
    ]
