# Generated by Django 2.2 on 2019-05-21 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0007_enduserondraft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enduserondraft',
            old_name='site',
            new_name='end_user',
        ),
    ]
