# Generated by Django 2.2 on 2019-05-21 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0008_auto_20190521_0919'),
        ('drafts', '0007_remove_draft_destination'),
    ]

    operations = [
    ]
