# Generated by Django 2.2 on 2019-05-21 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0007_auto_20190521_0843'),
        ('drafts', '0009_merge_20190521_1021'),
    ]

    operations = [
    ]
